README.md

This could help start setting the expectation that we are following semver.

proposed readme warning update

---

config/crd/patches/cainjection_in_apimservices.yaml
config/crd/patches/cainjection_in_azuresqlmanagedusers.yaml

Looks like I missed a couple files with the cert manager annotation fix

Bug: Missed couple files with the cert manager annotation fix

---

config/samples/azure_v1alpha1_rediscacheaction.yaml

Updates the rediscacheaction sample to include optional fields and descriptions

Add optional fields to rediscacheaction sample

---

README.md

Project is no longer experimental.

Remove experimental wording

---

azure-pipelines.yml
pkg/resourcemanager/keyvaults/keyops.go

Don't run devops pipeline if the only changes are docs changes

---

Makefile
controllers/azuresql_combined_test.go
controllers/suite_test.go
pkg/errhelp/errors.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_manager.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go
pkg/resourcemanager/azuresql/azuresqlserver/azuresqlserver_reconcile.go
pkg/resourcemanager/cosmosdbs/cosmosdb_reconcile.go
pkg/resourcemanager/mysql/server/reconcile.go
pkg/resourcemanager/pollclient/pollclient.go
pkg/resourcemanager/psql/server/server_reconcile.go
pkg/resourcemanager/storages/storageaccount/storageaccount_reconcile.go

Closes #1229
Adds support for updating SQL Databases
Also improved test resource cleanup and usage of the ARM LRO polling client a bit

Add support for SKU Database to support updates

---

README.md

Adds info on community call 
- [x ] this PR contains documentation

Include community call info

---

Makefile
controllers/azuresql_combined_test.go
main.go
pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser.go
pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go
pkg/resourcemanager/config/config.go

Closes #1254
**What this PR does / why we need it**: A few makefile cleanups and fixing a bug causing resource to get stuck in deleting state.
We currently cannot write an automated test for this scenario because the SqlManagedIdentity user only works in a real AKS cluster on Azure (due to how ManagedIdentity works). I tested it manually before sending the PR.

[Bug fix] Azure SQL Managed Identity can get stuck in deleting when the database the user is in is deleted

---

README.md
SUPPORT.md

The Microsoft Open Source Program Office is recommending the use of a `SUPPORT.md` file to make it easy for users to see what level of support each repo provides.
I've taken their supplied template and customized it with information already present in our `README.md`.
Are there any other support resources/routes that should be included?

Add standard SUPPORT.md file

---

Makefile

Makefile should specify PHONY for targets which don't produce a file of the given name (in this case, that's all of them).

Makefile targets should be PHONY

---

README.md

Fixes the internal link for the samples.

fixes samples link

---

docs/faq.md

Fix broken link to the new operator guide

---

docs/services/appinsights/appinsights.md

Update to the correct URL

---

docs/services/postgresql/postgresql.md

Fixing broken link to secrets

---

azure-pipelines.yml
devops/release/scripts/step1_releasepackage.sh
devops/release/scripts/step2_pushdockerimage.sh
devops/release/scripts/step3_pushhelmchart.sh
docs/howto/release.md

Improve release process for ASO

---

devops/release/scripts/step1_releasepackage.sh
devops/release/scripts/step2_pushdockerimage.sh
devops/release/scripts/step3_pushhelmchart.sh

Fix release scripts

---

pkg/resourcemanager/azuresql/azuresqluser/azuresqluser_reconcile.go

- It already was best effort in most places but we missed one.

Make AzureSQL KeyVault secret deletion best effort

---

Makefile

The [PR checklist](https://github.com/operator-framework/community-operators/blob/master/docs/pull_request_template.md) for operator bundle updates in the community-operators repo includes checks that the bundle has a ci.yaml file and that the new version of the bundle `ClusterServiceVersion` has a `replaces` property pointing to the previous version. Extend the make target to include that - the `PREVIOUS_BUNDLE_VERSION` variable can be passed in on the command line, but it would probably be better to update it in the ASO repo each time we do a release so it's less error-prone.

Include the replaces directive in ClusterServiceVersion

---

hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_array_properties.json
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_array_properties_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_array_properties_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_map_properties.json
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_map_properties_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_map_properties_crossplane.golden

https://github.com/Azure/k8s-infra/pull/454 fixed #1457, but didn't actually add any tests to ensure that the generated code was correct.
Adds some new golden file tests in order to ensure we don't regress this fix.

Add more complex ARM nested map and array tests

---

Taskfile.yml

Tests on master timed out due to exceeding 30 minute limit.

Extend live test timeout

---

hack/generated/controllers/crd_virtualnetwork_test.go
hack/generated/controllers/recordings/Test_VirtualNetwork_CRUD.yaml
hack/generated/pkg/testcommon/test_context.go
hack/generator/azure-arm.yaml

Add Create/Delete test for Virtual Networks in codegen controller.
Ref: #1192

Add v2 VNet CRUD test

---

hack/generated/controllers/crd_networking_publicip_test.go
hack/generated/controllers/crd_resourcegroup_test.go
hack/generated/controllers/recordings/Test_PublicIP_CRUD.yaml
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generator/azure-arm.yaml
hack/generator/pkg/codegen/pipeline_add_cross_resource_references.go

Adds PublicIPAddress, and fixes existing ResourceGroup test to use Patch rather than Update.

Add v2 PublicIPAddress resource and CRUD test

---

hack/generated/pkg/testcommon/counting_roundtripper.go

Fix race in counting_roundtripper

---

hack/generated/controllers/recordings/Test_CosmosDB_CRUD.yaml
hack/generated/controllers/recordings/Test_Disk_CRUD.yaml
hack/generated/controllers/recordings/Test_LoadBalancer_CRUD.yaml
hack/generated/controllers/recordings/Test_PublicIP_CRUD.yaml
hack/generated/controllers/recordings/Test_ResourceGroup_CRUD.yaml
hack/generated/controllers/recordings/Test_ServiceBus_Basic_CRUD.yaml
hack/generated/controllers/recordings/Test_ServiceBus_Standard_CRUD.yaml
hack/generated/controllers/recordings/Test_StorageAccount_CRUD.yaml
hack/generated/controllers/recordings/Test_VirtualNetwork_CRUD.yaml
hack/generated/pkg/armclient/recordings/Test_NewResourceGroupDeployment.yaml
hack/generated/pkg/armclient/recordings/Test_NewResourceGroupDeployment_Error.yaml
hack/generated/pkg/armclient/template_client_test.go
hack/generated/pkg/testcommon/error_translating_roundtripper.go
hack/generated/pkg/testcommon/kube_per_test_context.go
hack/generated/pkg/testcommon/test_context.go

- Move region to WestUS2 since some resources have a default quota of
0 in West US (VMs in particular).
- Wait for resource group deletion at the end of each test (this is important
for reproducibility as well as making sure we don't leak resources.
- Re-record tests.

Some small test improvements

---

Taskfile.yml

Dont use -v for envtest-live either

---

.devcontainer/install-dependencies.sh

This caused CI failure recently due to new linters being added.

Pin golangci-lint version

---

hack/generated/_apis/microsoft.resources/v1alpha1api20200601/resourcegroup_arm_types.go
hack/generated/_apis/microsoft.resources/v1alpha1api20200601/resourcegroup_types.go
hack/generated/controllers/crd_resourcegroup_test.go
hack/generated/pkg/armclient/template_client_test.go

- Fix a few other minor issues too

Flatten ResourceGroup properties in Status

---

hack/generator/pkg/astmodel/armconversion/arm_conversion_function.go
hack/generator/pkg/astmodel/armconversion/convert_from_arm_function_builder.go
hack/generator/pkg/astmodel/armconversion/convert_to_arm_function_builder.go
hack/generator/pkg/astmodel/armconversion/shared.go
hack/generator/pkg/codegen/pipeline/add_arm_conversion_interface.go

Replace boolean isSpecType with enum

---

Taskfile.yml
hack/generated/config/manager/manager_image_patch.yaml
scripts/deploy_testing_secret.sh
scripts/kind-with-registry.sh

- Also fix localhost docker registry

Move kind targets to Taskfile

---

hack/generated/go.mod
hack/generated/go.sum
hack/generated/pkg/genruntime/conditions/conditions.go
hack/generated/pkg/genruntime/conditions/conditions_test.go
hack/generated/pkg/genruntime/conditions/positive_condition_builder.go
hack/generated/pkg/genruntime/conditions/positive_condition_builder_test.go
hack/generated/pkg/genruntime/conditions/ready_condition_builder.go

Adds the `Conditions` types discussed in #1614

Add new conditions type

---

.devcontainer/install-dependencies.sh
Taskfile.yml

This was recently added: https://github.com/go-task/task/issues/53

Update go-task to 3.7 and use deduplication

---

hack/generated/_apis/microsoft.resources/v1alpha1api20200601/resourcegroup_types.go
hack/generated/controllers/deployment_reconciler_negative_test.go
hack/generated/controllers/edge_case_test.go
hack/generated/controllers/generic_controller.go
hack/generated/controllers/suite_test.go
hack/generated/pkg/genruntime/base_types.go
hack/generated/pkg/genruntime/helpers.go
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generated/pkg/reconcilers/deployment_error_classifier.go
hack/generated/pkg/reconcilers/deployment_error_classifier_test.go
hack/generated/pkg/reconcilers/deployment_error_translator.go
hack/generated/pkg/reconcilers/deployment_error_translator_test.go
hack/generated/pkg/reflecthelpers/reflect_helpers.go
hack/generated/pkg/testcommon/be_provisioned_matcher.go
hack/generated/pkg/testcommon/ensure.go
hack/generated/pkg/testcommon/kube_matcher.go
hack/generated/pkg/testcommon/kube_per_test_context.go
hack/generated/pkg/testcommon/kube_test_context.go

Use Conditions rather than annotations to determine reconcile state

---

.github/workflows/create-release.yml

Validated that releases are pushed correctly, now change endpoint.

Push releases to public MCR

---

hack/generated/_apis/microsoft.resources/v1alpha1api20200601/resourcegroup_types.go
hack/generator/pkg/astmodel/resource_type.go
hack/generator/pkg/astmodel/resource_type_test.go
hack/generator/pkg/codegen/pipeline/add_status_conditions.go
hack/generator/pkg/codegen/pipeline/testdata/TestAddStatusConditions/microsoft.person-v20200101.golden

Add printcolumns support on generated resources

---

hack/generated/pkg/testcommon/be_deleted_matcher.go
hack/generated/pkg/testcommon/be_provisioned_matcher.go
hack/generated/pkg/testcommon/kube_matcher.go
hack/generated/pkg/testcommon/kube_per_test_context.go
hack/generated/pkg/testcommon/verify.go
hack/generator/pkg/astmodel/armconversion/convert_from_arm_function_builder.go
hack/generator/pkg/astmodel/armconversion/convert_to_arm_function_builder.go
hack/generator/pkg/astmodel/armconversion/shared.go
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_has_embedded_resource_inside_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_removed_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_id_resource_reference_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_required_and_optional_resource_references_azure.golden

Fixes a few small issues which had come up in previous PRs but I had put off fixing in that PR due to the size of the change.
I believe @theunrepentantgeek had requested both of these at some point in the past, so tagging him.

Code generator code gardening

---

hack/generated/config/samples/microsoft.network/v1alpha120201101_networksecuritygroup.yaml
hack/generated/config/samples/microsoft.network/v1alpha120201101_networksecuritygroupssecurityrule.yaml
hack/generated/controllers/crd_networking_nsg_test.go
hack/generated/controllers/recordings/Test_NetworkSecurityGroup_CRUD.yaml
hack/generated/pkg/testcommon/kube_per_test_context.go
hack/generator/azure-arm.yaml

Adds support for NetworkSecurityGroup and NetworkSecurityGroupRules

Add NSG and NSG Rule support

---

docs/v2/adding-new-codegenerated-resource.md
hack/README.md

- Add additional documentation on the common error where a property of a newly generated type needs reference confirmation and editing of the newKnownReferencesMap.
- Update v2 README to list supported resources and link to the samples directory.

Documentation improvements

---

Taskfile.yml
hack/generated/pkg/genruntime/resource_reference.go

It's still not perfect but this is certainly closer to correct

Fix ResourceReference ARMID regex

---

hack/generated/pkg/reconcilers/azure_deployment_reconciler.go

Log what we're interested in.
This _mostly_ closes #1762. There is one remaining item which should probably be addressed as part of this PR and I'd like people's opinions on, and that's this log:
`r.log.V(Debug).Info("Got ARM status", "status", string(statusBytes))`
This results in logs that look like the following:
> azure_deployment_reconciler.go:808: I2021-09-17T14:56:42-07:00] ResourceGroupController "msg"="Got ARM status" name="asotest-rg-ytfqcd" namespace="aso-test-ns" azureName="asotest-rg-ytfqcd" status="{\"id\":\"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/asotest-rg-ytfqcd\",\"name\":\"asotest-rg-ytfqcd\",\"location\":\"westus2\",\"tags\":{\"CreatedAt\":\"2001-02-03T04:05:06Z\"},\"properties\":{\"provisioningState\":\"Succeeded\"}}"
> …

Stop logging the entire resource

---

hack/generator/pkg/codegen/pipeline/testdata/TestGolden_InjectConvertibleInterface/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestGolden_InjectConvertibleInterface/microsoft.person-v20211231.golden
hack/generator/pkg/codegen/pipeline/testdata/TestGolden_InjectResourceConversionTestCases/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestGolden_InjectResourceConversionTestCases/microsoft.person-v20211231.golden
hack/generator/pkg/functions/resource_conversion_function.go
hack/generator/pkg/functions/testdata/TestGolden_ResourceConversionFunction_DirectConversion_GeneratesExpectedCode/ResourceConversionFunction.golden

A really simple tweak to generated code, mostly to reduce the size of an upcoming PR by a smidge.

Super simple code gardening for conversion functions

---

v2/cmd/controller/main.go
v2/go.mod
v2/go.sum
v2/internal/genericarmclient/generic_client.go
v2/internal/testcommon/mock_token_cred.go
v2/internal/testcommon/test_context.go

* Resolves memory leak in Poller.

Update go SDK dependency

---

v2/internal/reconcilers/azure_generic_arm_reconciler.go

Avoids possible situation where we have created an Azure resource but not set the finalizer.

Move finalizer

---

.devcontainer/install-dependencies.sh
.github/workflows/ok-to-test.yml
.github/workflows/pr-validation-with-secrets.yml
.github/workflows/pr-validation.yml
Taskfile.yml
docs/hugo/content/contributing/contributing/index.md
scripts/delete-old-resourcegroups.sh
v2/cmd/controller/main.go
v2/internal/genericarmclient/suite_test.go
v2/internal/testcommon/creds.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/kube_test_context.go
v2/internal/testcommon/resource_namer.go
v2/internal/testcommon/test_context.go
v2/test/managedidentity_test.go
v2/test/suite_test.go

- Add a single test to this infrastructure to showcase its use.
- E2E tests (in Kind) are run as part of CI on each PR.
Closes #1941.

Add E2E test infrastructure

---

.github/workflows/pr-validation.yml
Taskfile.yml
scripts/delete-old-resourcegroups.sh

* Fix bug where live envtests were failing.
* Improve "task" behavior to run required kustomize for envtests
to make it easier to run envtests from IDE without need to call
specific target.

Improve CI behavior

---

v2/tools/generator/internal/astmodel/types.go
v2/tools/generator/internal/astmodel/types_test.go
v2/tools/generator/internal/codegen/pipeline/remove_status_property_validations.go

Add FindAllSpecTypes and FindAllStatusTypes

---

v2/internal/reflecthelpers/reflect_helpers.go
v2/internal/reflecthelpers/reflect_helpers_test.go

Refactor reflect_helpers a bit to support other types

---

v2/tools/generator/internal/codegen/pipeline/create_arm_types.go

Simplified by breaking out property specific handling
into their own handlers. This paves the way for future handlers as
well, which will be required for supporting secrets.

Simplify createARMTypes method

---

v2/api/compute/v1alpha1api20201201/virtual_machine_scale_set_types_gen.go
v2/api/compute/v1alpha1api20201201/virtual_machine_scale_set_types_gen_test.go
v2/api/compute/v1alpha1api20201201/virtual_machine_types_gen.go
v2/api/compute/v1alpha1api20201201/virtual_machine_types_gen_test.go
v2/api/compute/v1alpha1api20201201/zz_generated.deepcopy.go
v2/api/compute/v1alpha1api20201201storage/virtual_machine_scale_set_types_gen.go
v2/api/compute/v1alpha1api20201201storage/virtual_machine_scale_set_types_gen_test.go
v2/api/compute/v1alpha1api20201201storage/virtual_machine_types_gen.go
v2/api/compute/v1alpha1api20201201storage/virtual_machine_types_gen_test.go
v2/api/compute/v1alpha1api20201201storage/zz_generated.deepcopy.go
v2/azure-arm.yaml
v2/internal/controllers/crd_compute_vm_test.go
v2/internal/controllers/recordings/Test_Compute_VM_CRUD.yaml
v2/internal/testcommon/resource_namer.go
v2/tools/generator/internal/codegen/pipeline/add_secrets.go
v2/tools/generator/internal/config/configuration.go
v2/tools/generator/internal/config/group_configuration.go
v2/tools/generator/internal/config/object_model_configuration.go
v2/tools/generator/internal/config/property_configuration.go
v2/tools/generator/internal/config/property_configuration_test.go
v2/tools/generator/internal/config/type_configuration.go
v2/tools/generator/internal/config/version_configuration.go

* Mark VM/VMSS password field as secret.
* Note that VM/VMSS/AKS KeyData is NOT secret as it's just
a public key.

Support secret overloading in the config

---

README.md
docs/v1/README.md

Add warning to ASOv1 documentation

---

v2/azure-arm.yaml

Adds some documentation to our configuration file to help someone new to understand what they're reading. 
To Do

Add documentation to config file

---

v2/api/dbforpostgresql/v1alpha1api20210601/flexible_server_types_gen.go
v2/api/dbforpostgresql/v1alpha1api20210601/flexible_server_types_gen_test.go
v2/api/dbforpostgresql/v1alpha1api20210601/flexible_servers__spec_arm_types_gen.go
v2/api/dbforpostgresql/v1alpha1api20210601/flexible_servers__spec_arm_types_gen_test.go
v2/api/dbforpostgresql/v1alpha1api20210601/zz_generated.deepcopy.go
v2/api/dbforpostgresql/v1alpha1api20210601storage/flexible_server_types_gen.go
v2/api/dbforpostgresql/v1alpha1api20210601storage/flexible_server_types_gen_test.go
v2/api/dbforpostgresql/v1alpha1api20210601storage/zz_generated.deepcopy.go
v2/api/signalrservice/v1alpha1api20211001/signal_r__spec_arm_types_gen.go
v2/api/signalrservice/v1alpha1api20211001/signal_r_types_gen.go

Updating to get access to latest ContainerRegistry api-version for use in #2074

Update azure-resource-manager-schemas submodule

---

v2/internal/controllers/crd_aks_managedcluster_test.go
v2/internal/controllers/crd_cache_redis_test.go
v2/internal/controllers/crd_cache_redisenterprise_test.go
v2/internal/controllers/crd_compute_disk_test.go
v2/internal/controllers/crd_compute_vm_test.go
v2/internal/controllers/crd_compute_vmss_test.go
v2/internal/controllers/crd_cosmosdb_mongodb_test.go
v2/internal/controllers/crd_cosmosdb_sql_test.go
v2/internal/controllers/crd_dbformysql_flexibleserver_test.go
v2/internal/controllers/crd_dbforpostgresql_flexibleserver_test.go
v2/internal/controllers/crd_eventgrid_topic_test.go
v2/internal/controllers/crd_eventhub_namespace_test.go
v2/internal/controllers/crd_insights_component_test.go
v2/internal/controllers/crd_managedidentity_userassignedidentity_test.go
v2/internal/controllers/crd_networking_nsg_test.go
v2/internal/controllers/crd_networking_publicip_test.go
v2/internal/controllers/crd_networking_virtualnetwork_test.go
v2/internal/controllers/crd_networking_virtualnetworkpeering_test.go
v2/internal/controllers/crd_operationalinsights_workspace_test.go
v2/internal/controllers/crd_resources_resourcegroup_test.go
v2/internal/controllers/crd_signalr_test.go
v2/internal/controllers/deployment_reconciler_negative_test.go
v2/internal/controllers/edge_case_test.go
v2/internal/controllers/operatormode_test.go
v2/internal/testcommon/be_provisioned_matcher.go
v2/internal/testcommon/kube_matcher.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/verify.go

Use ObservedGeneration to make Patch easier to use

Improve Patch test helper

---

docs/hugo/content/contributing/generator-overview.md

To aid in onboarding of new developers, we want to have an overview that gives them a few good places to start understanding how things work.

Code structure overview for the Code Generator

---

docs/hugo/content/contributing/add-a-new-code-generated-resource.md

Signed-off-by: vaspahomov <vas2142553@gmail.com>
* Fix for invalid (404) link in docs.

Fix link on CRUD test

---

v2/internal/controllers/crd_batch_account_test.go
v2/internal/controllers/recordings/Test_Batch_Account_CRUD.yaml

Add missing Batch Account test

---

v2/api/cache/v1alpha1api20201201/redis_types_gen.go
v2/api/documentdb/v1alpha1api20210515/database_account_types_gen.go
v2/api/storage/v1alpha1api20210401/storage_account_types_gen.go
v2/internal/controllers/secrets_from_azure_test.go
v2/internal/testcommon/kube_per_test_context.go
v2/pkg/genruntime/secrets.go
v2/pkg/genruntime/secrets_test.go
v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/pipeline/apply_defaulter_and_validator_interfaces.go
v2/tools/generator/internal/codegen/testdata/TestGolden_NewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewTestCodeGeneratorCreatesRightPipeline.golden
v2/tools/generator/internal/functions/kubernetes_admissions_validations.go
v2/tools/generator/internal/interfaces/validator_interface.go

Webhook to validate []genruntime.SecretDestination

---

README.md
docs/hugo/content/introduction/conditions.md
docs/hugo/content/introduction/diagnosing-problems-with-aso.md
v2/README.md

- Add page documenting conditions.
- Add page for diagnosing problems with ASO. This can be expanded
on later.
Closes #1264 

Docs updates

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/pkg/genruntime/extensions/secret_retrieval.go

Makes calling a resource with the extension a bit cleaner

Add extension wrapper for Secrets

---

docs/hugo/content/introduction/diagnosing-problems.md

It was a bit long before and didn't render well

Simplify article title

---

.github/CODEOWNERS

Approval of PRs by @super-harsh should be enough.
**How does this PR make Harsh feel**:

Add Harshdeep to CODEOWNERS

---

.github/workflows/api-docs-repo.yaml
.github/workflows/build-devcontainer-image.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create-release.yml
.github/workflows/deploy-site.yml
.github/workflows/helm-chart-repo.yaml
.github/workflows/live-validation.yml
.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/visualize-repo.yml
config/operator-bundle/bases/azure-service-operator.clusterserviceversion.yaml
docs/v1/howto/quickstart.md

We had a few outstanding references from when our primary branch was called `master` instead of `main`.
Also updates our workflows to use `actions/checkout@v3` consistently.
Closes #2144

Fix last references to old primary branch

---

.github/stale.yml

Stalebot unexpectedly triggered and did things we do not want. Tightening the leash.

Reconfigure stalebot

---

docs/issue-management.md

Updates our docs on how we handle stale issues.

Update Issue Management Docs

---

scripts/generate-helm-manifest.sh
v2/charts/azure-service-operator/values.yaml

Closes #1367 
This PR adds support for having pod annotations for ASOv2 helm chart. 
Didn't include new helm `.tgz` bundle in this PR, considering including it in the beta.1 release helm chart.

Add pod annotationfor ASOv2 helm chart

---

scripts/generate-helm-manifest.sh
v2/charts/azure-service-operator/values.yaml

The example for creating the service principal should be updated to remove the quotes of the service principal name, or the command will not be accepted. 

Correct the example syntax in the readme document

---

hack/crossplane/apis/cache/v1beta20200601/redis_types_gen.go
hack/crossplane/apis/sql/v1beta20201101preview/server_types_gen.go
hack/crossplane/apis/sql/v1beta20201101preview/servers_database_types_gen.go

Updates the generated files in `/hack/crossplane` as changed by #2264
Needs to be merged first, so that #2264 will build.

Update generated Crossplane files for #2264

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go

On the off chance Azure returns us something we don't understand, 
we should still return that to users in the Ready condition.

Protect against malformed errors

---

.devcontainer/install-dependencies.sh
.github/workflows/pr-validation.yml
Taskfile.yml
v2/tools/mangle-test-json/main.go

Take advantage of this [new feature](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) to make test passes/failures easier to find.

Produce Markdown test-run summary for Github

---

v2/tools/generator/internal/codegen/code_generator.go

Total execution time is getting longer; this will allow us to informally see where the majority of execution time is being spent.

Display execution of each stage

---

v2/cmd/controller/main.go
v2/internal/controllers/controller_resources.go
v2/internal/controllers/crd_cache_redis_test.go
v2/internal/controllers/generic_controller.go
v2/internal/controllers/targetnamespace_test.go
v2/internal/reconcilers/action.go
v2/internal/reconcilers/annotations.go
v2/internal/reconcilers/arm/annotations.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/reconcilers/client_helpers.go
v2/internal/reconcilers/common.go
v2/internal/reconcilers/reconcile_policy.go
v2/internal/resolver/resolver.go
v2/internal/resolver/resolver_test.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/testcommon/resolver.go
v2/pkg/genruntime/base_types.go
v2/pkg/genruntime/conditions/ready_condition_builder.go
v2/pkg/genruntime/kubernetes_resource.go
v2/pkg/genruntime/registration/registration.go
v2/pkg/genruntime/resolved_secrets.go
v2/test/reconcile_policy_test.go

This is moving us in a positive direction but doesn't get us all the way there.
There will be further changes needed, but rather than build them all up and get it perfect, 
I'm instead sending pieces so that it's merged faster and also is somewhat more digestible.

Refactor reconciler to further cater to non-ARM resources

---

v2/config/manager/manager.yaml

Make manager container the default for logs

---

v2/azure-arm.yaml
v2/tools/generator/internal/codegen/pipeline/add_secrets.go
v2/tools/generator/internal/config/configuration.go

Closes #2341 
Added fix for verifying if the secret is consumed or not before adding secrets in generator

Add verifier for IsSecret property modifier 

---

v2/api/resources/v1beta20200601/resourcegroup_types.go
v2/internal/testcommon/kube_per_test_context.go
v2/test/storage_write_secret_test.go

Add missing sercret permissions to ASO service account

---

Taskfile.yml
docs/hugo/content/contributing/create-a-new-release.md
docs/hugo/content/introduction/uninstalling.md
docs/hugo/content/introduction/upgrading.md
scripts/generate-helm-manifest.sh
v2/README.md

Helm updates and upgrade documentation updates

---

v2/internal/controllers/generic_controller.go
v2/internal/controllers/targetnamespace_test.go
v2/internal/genericarmclient/generic_client.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/reconcilers/common.go
v2/internal/reconcilers/mysql/mysql_user_reconciler.go
v2/internal/util/kubeclient/utilities.go
v2/pkg/genruntime/base_types.go
v2/pkg/genruntime/reconciler.go

Refactor generic controller to share more code between reconcilers

---

v2/README.md

Fix broken link

---

docs/v1/services/postgresql/postgresql.md

https://github.com/Azure/azure-service-operator/blob/main/docs/v1/services/postgresql/postgresql.md
#PingMSFTDocs

Typo "Postgre SQL"→"PostgreSQL"

---

Makefile
charts/azure-service-operator/values.yaml
config/default/manager_auth_proxy_patch.yaml
go.mod
go.sum
pkg/errhelp/errors.go
pkg/resourcemanager/eventhubs/consumergroup.go
pkg/resourcemanager/eventhubs/hub.go
v2/charts/azure-service-operator/values.yaml
v2/config/manager/manager_auth_proxy_patch.yaml
v2/go.mod
v2/go.sum

This impacts both ASOv1 and ASOv2. This fixes #2374

Update to latest version of a few packages to take CVE fixes

---

v2/tools/generator/internal/config/configuration.go

Error when parsing configuration finds unknown fields

---

Taskfile.yml

Add recording target to the Taskfile

---

.github/workflows/helm-chart-repo.yaml

Allow Helm generation job to be run manually

---

v2/internal/controllers/crd_networking_publicip_test.go
v2/internal/controllers/crd_networking_virtualnetwork_test.go
v2/internal/controllers/crd_networking_virtualnetworkgateway_test.go
v2/internal/controllers/crd_networking_virtualnetworkpeering_test.go
v2/internal/controllers/recordings/Test_Networking_VirtualNetworkGateway_CRUD.yaml

Closes #2410 
Added test for VirtualNetworkGateway
This resource had no controller tests.

Add VirtualNetworkGateway controller test

---

v2/internal/controllers/crd_cache_redis_test.go
v2/internal/genericarmclient/generic_client.go
v2/internal/util/mysql/mysql.go

The linter in our base container image has been updated, and it detected a couple of things we need to address.

Fix lint issues

---

v2/charts/azure-service-operator/templates/secret.yaml
v2/charts/azure-service-operator/values.yaml
v2/cmd/controller/main.go
v2/config/manager/manager.yaml
v2/config/manager/manager_image_patch.yaml
v2/internal/config/vars.go
v2/internal/config/vars_test.go
v2/internal/controllers/operatormode_test.go
v2/internal/genericarmclient/generic_client.go
v2/internal/genericarmclient/generic_client_test.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/test_context.go

Support national clouds

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/pkg/genruntime/extensions/claimer.go
v2/pkg/genruntime/extensions/deleter.go
v2/pkg/genruntime/extensions/successful_resource_modifier.go

- Hook for deletion
- Hook for after-successful-creation
- Hook for claim

Support new extension points for ARM resources

---

v2/internal/testcommon/test_context.go

Fix recordings

---

v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Managedidentity_v1alpha1api_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Managedidentity_v1beta_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Sqldatabase_v1alpha1api_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Sqldatabase_v1beta_CreationAndDeletion.yaml
v2/internal/controllers/samples_test.go
v2/internal/testcommon/samples_tester.go

Improve Samples test ignore filter

---

v2/api/resources/v1alpha1api20200601/resourcegroup_types.go
v2/api/resources/v1beta20200601/resourcegroup_types.go

Improve ResourceGroup AzureName validation

---

v2/azure-arm.yaml
v2/tools/generator/internal/astmodel/primitive_type.go
v2/tools/generator/internal/codegen/pipeline/add_cross_resource_references.go
v2/tools/generator/internal/codegen/pipeline/status_augment.go
v2/tools/generator/internal/jsonast/jsonast.go

Use Swagger as first source of truth for ARM references

---

v2/internal/reflecthelpers/reflect_helpers.go
v2/internal/resolver/config_map_resolver.go
v2/internal/resolver/errors.go
v2/internal/resolver/resolver.go
v2/internal/resolver/resolver_test.go
v2/pkg/genruntime/arm_transformer.go

Part of ongoing work related to #2317 and #2435.

Add ConfigMap resolver

---

v2/api/appconfiguration/customizations/configuration_store_extensions.go
v2/api/cache/customizations/redis_extensions.go
v2/api/containerservice/customizations/managed_cluster_extensions.go
v2/api/dbformariadb/customizations/server_extensions.go
v2/api/dbformysql/customizations/flexible_server_extensions.go
v2/api/dbforpostgresql/customizations/flexible_server_extensions.go
v2/api/documentdb/customizations/database_account_extensions.go
v2/api/machinelearningservices/customizations/workspace_extension.go
v2/api/servicebus/customizations/namespace_extensions.go
v2/api/storage/customizations/storage_account_extensions.go
v2/pkg/genruntime/configmaps/collector.go
v2/pkg/genruntime/configmaps/collector_test.go
v2/pkg/genruntime/merger/merger.go
v2/pkg/genruntime/merger/merger_test.go
v2/pkg/genruntime/secrets/collector.go
v2/pkg/genruntime/secrets/collector_test.go

Add configmap Collector and generic Merger

---

v2/tools/generator/internal/astmodel/object_type.go
v2/tools/generator/internal/astmodel/property_set.go
v2/tools/generator/internal/astmodel/property_set_test.go

Add FindAll function for PropertySet

---

v2/internal/reflecthelpers/reflect_helpers.go
v2/internal/reflecthelpers/reflect_helpers_test.go
v2/pkg/genruntime/configmaps.go
v2/tools/generator/internal/codegen/pipeline/apply_defaulter_and_validator_interfaces.go
v2/tools/generator/internal/functions/kubernetes_admissions_validations.go

Webhook for validating ConfigMapReference pairs

---

README.md
SUPPORT.md

Update support to reference Kubernetes Slack

---

docs/hugo/content/introduction/authentication.md
docs/hugo/content/introduction/frequently-asked-questions.md
v2/README.md

* Improve authentication documentation: Discuss how to restrict ASO permissions
* FAQ: Compare ASO and Crossplane

More documentation clarifications

---

docs/hugo/content/introduction/frequently-asked-questions.md
v2/internal/config/vars.go

15m is a bit too aggressive.
Fixes #2577.

Increase default AZURE_SYNC_PERIOD from 15m to 1h

---

v2/internal/reconcilers/arm/arm_client_cache.go
v2/internal/reconcilers/arm/arm_client_cache_test.go

Closes #1173 
**Special notes for your reviewer:**
Follow up PR would include usage docs and updated design doc

Add support for per resource credential

---

.github/CODEOWNERS

I'm getting pinged on every PR 😆

Removing self from CODEOWNERS

---

docs/hugo/content/introduction/diagnosing-problems.md
docs/hugo/content/introduction/metrics.md

Add title to metrics.md and make it reachable from diagnosing

---

docs/hugo/content/contributing/add-a-new-code-generated-resource.md
docs/hugo/content/introduction/upgrading.md
docs/hugo/content/reference/breaking-changes.md
docs/v1/README.md
docs/v1/services/mysql/mysql.md
v2/README.md

Closes off a few documentation needs we've previously noted.
Closes #1463 #2091 #2656 

Documentation updates for the beta.4 release

---

docs/hugo/content/introduction/breaking-changes.md
docs/hugo/content/reference/breaking-changes.md

Integrates our breaking changes notes into our documentation site so they can be linked from the `beta.4` release notes.

Integrate breaking changes into our site

---

.github/workflows/visualize-repo.yml

Generates a code structure diagram for `asoctl`. Once that tool is a little more complete, we should write some docs that reference the new diagram.
Also updated a few action versions.

Update code visualizations to include asoctl

---

v2/azure-arm.yaml
v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/golden_files_test.go
v2/tools/generator/internal/codegen/pipeline/remove_empty_objects.go
v2/tools/generator/internal/codegen/testdata/AdditionalProperties/Generates_nothing_if_set_to_false.golden
v2/tools/generator/internal/codegen/testdata/AdditionalProperties/Generates_nothing_if_set_to_false.json
v2/tools/generator/internal/codegen/testdata/ArmResource/Arm_oneof_resource_conversion_on_arm_type_only_crossplane.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewCrossplaneCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewTestCodeGeneratorCreatesRightPipeline.golden

Ensure we prune empty types

---

v2/internal/controllers/recordings/Test_Compute_Image_20210701_CRUD.yaml
v2/internal/controllers/recordings/Test_Compute_VMSS_20201201_CRUD.yaml
v2/internal/controllers/recordings/Test_Compute_VM_20201201_CRUD.yaml
v2/internal/controllers/recordings/Test_DBForPostgreSQL_FlexibleServer_20220120preview_CRUD.yaml
v2/internal/controllers/recordings/Test_MachineLearning_Workspaces_CRUD.yaml
v2/internal/controllers/recordings/Test_MissingSecret_ReturnsError_ReconcilesSuccessfullyWhenSecretAdded.yaml
v2/internal/controllers/recordings/Test_OperationRejected.yaml
v2/internal/controllers/recordings/Test_OperationRejected_SucceedsAfterUpdate.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Compute_v1alpha1api_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Compute_v1beta_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Dbforpostgresql_v1beta20220120preview_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Machinelearningservices_v1beta_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_UserSecretInDifferentNamespace_ShouldNotTriggerReconcile.yaml
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go

Use correct API version for DELETE requests

---

v2/tools/generator/internal/codegen/pipeline/add_cross_resource_references.go

This is nonbreaking and will put us in a good position going forward. I will deal with the transformations required as part of the new ManagedCluster version.
This fixes #2501

Fix ARM ID case miss

---

v2/tools/generator/internal/astmodel/interface_type.go
v2/tools/generator/internal/astmodel/interface_type_test.go
v2/tools/generator/internal/astmodel/resource_type.go
v2/tools/generator/internal/astmodel/type_visitor.go
v2/tools/generator/internal/astmodel/type_visitor_builder.go
v2/tools/generator/internal/astmodel/type_visitor_test.go
v2/tools/generator/internal/codegen/pipeline/convert_allof_and_oneof_to_objects.go
v2/tools/generator/internal/codegen/pipeline/remove_type_aliases.go
v2/tools/generator/internal/reporting/testdata/Test_TypeCatalogReport_GivenInterface_ShowsExpectedDetails.golden
v2/tools/generator/internal/reporting/type_catalog_report.go
v2/tools/generator/internal/reporting/type_catalog_report_test.go

Add InterfaceType

---

v2/cmd/controller/main.go
v2/internal/controllers/controller_resources.go
v2/internal/controllers/targetnamespace_test.go
v2/internal/reconcilers/generic/generic_reconciler.go
v2/internal/reconcilers/generic/register.go
v2/internal/testcommon/kube_test_context_envtest.go

Credit to @super-harsh who was the one who had the idea to make this change.

Refactor generic_controller out of internal/controllers

---

Makefile
charts/azure-service-operator/values.yaml
config/default/manager_auth_proxy_patch.yaml
v2/charts/azure-service-operator/values.yaml
v2/config/manager/manager_auth_proxy_patch.yaml

Update kube-rbac-proxy version

---

.github/workflows/api-docs-repo.yaml
.github/workflows/create-release.yml
.github/workflows/deploy-site.yml
.github/workflows/helm-chart-repo.yaml
.github/workflows/live-validation.yml
.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml
.github/workflows/scan-controller-image.yaml

Update set-output for github actions

---

v2/tools/generator/internal/kustomization/conversion_patch_file.go

Noticed this while I was doing the CRD work

Update conversion patch version

---

v2/internal/controllers/controller_resources.go
v2/internal/reconcilers/generic/register.go
v2/internal/reconcilers/predicates.go
v2/internal/util/predicates/name_predicate.go
v2/internal/util/predicates/name_predicate_test.go
v2/internal/util/predicates/namespace_predicate.go
v2/internal/util/predicates/namespace_predicate_test.go
v2/internal/util/predicates/object_predicate.go
v2/internal/util/predicates/select_annotations_predicate.go
v2/internal/util/predicates/select_annotations_predicate_test.go
v2/pkg/genruntime/registration/registration.go

Also added namespace and name predicates

Predicate shouldn't be hardcoded for all reconcilers

---

.devcontainer/Dockerfile
.devcontainer/install-dependencies.sh
.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml

This release of Go-Task includes my fix for the deadlock race condition that was causing us grief.

Upgrade Go-Task to v3.22

---

v2/api/appconfiguration/customizations/configuration_store_extensions.go
v2/api/cache/customizations/redis_extensions.go
v2/api/containerservice/customizations/managed_cluster_extensions.go
v2/api/documentdb/customizations/database_account_extensions.go
v2/api/machinelearningservices/customizations/workspace_extension.go
v2/api/storage/customizations/storage_account_extensions.go
v2/cmd/controller/main.go
v2/internal/genericarmclient/generic_client.go
v2/internal/genericarmclient/generic_client_test.go
v2/internal/metrics/arm_client_metrics.go
v2/internal/metrics/metrics.go
v2/internal/metrics/metrics_policy.go
v2/internal/reconcilers/arm/arm_client.go
v2/internal/reconcilers/arm/arm_client_cache.go
v2/internal/reconcilers/arm/arm_client_cache_test.go
v2/internal/reconcilers/arm/arm_client_factory.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/testcommon/test_context.go

Refactor generic client to remove SubscriptionID and make metrics optional

---

docs/hugo/content/contributing/_index.md
docs/hugo/content/design/_index.md
docs/hugo/content/tools/_index.md
docs/hugo/content/tools/asoctl.md
docs/hugo/content/tools/generator.md

We need to provide good documentation for `asoctl`, as well as improving what we have for our code generator. This PR adds scaffolding for where these docs should go.

Add scaffolding for Tools documentation

---

docs/hugo/link-checker.json

This should unblock updates to our docs site; the suppression can be removed once the update is complete and the URLs are now valid.
(It was this or a gif of a slight-of-hand card trick. 😁)

Suppress references to new folder

---

.github/workflows/pr-validation-docs.yml
Taskfile.yml
docs/hugo/content/guide/upgrading.md

Adds a workflow to validate documentation links on PRs.

Create workflow to validate documentation links in PRs

---

v2/cmd/asoctl/cmd/import_azure_resource.go
v2/cmd/asoctl/cmd/log.go
v2/cmd/asoctl/cmd/root.go
v2/cmd/asoctl/internal/crd/cleaner.go
v2/cmd/asoctl/internal/importing/importable_arm_resource.go
v2/cmd/asoctl/internal/importing/resource_importer.go
v2/cmd/asoctl/internal/importing/resource_importer_report.go

Add --quiet flag to suppress most logging 
Add summary of what was imported (or not) #2904
Fixes for --verbose not working.  #2900
Fix for partial progress bars remaining on screen
Closes #2868 
Closes #2900
Closes #2904 
**Prerequisites**

Improve UX for asoctl import azure-resource

---

v2/test/single_operator_multitenant_test.go

It should not be set in the global secret case. This test just ensures that.

Assert the PerResourceSecret annotation is not set

---

v2/internal/testcommon/kube_test_context_envtest.go

Trying this to see if it makes the tests pass more reliably.

Limit test concurrency

---

docs/hugo/content/design/ADR-2023-05-Installing-Only-Selected-CRDs.md

Create ADR for installing only selected CRDs

---

docs/hugo/content/contributing/_index.md
docs/hugo/content/design/images/pls-pe-differences.dot

I discovered two broken links on our Contributing page.
Need to also work out why this wasn't caught by our prior checks.

Fix two broken links

---

docs/hugo/content/guide/authentication/credential-format.md
docs/hugo/content/guide/authentication/multitenant-deployment.md
docs/hugo/content/guide/crd-management.md
v2/README.md
v2/charts/azure-service-operator/values.yaml

CRD installation docs

---

Taskfile.yml

Make taskfile indentation consistent

---

.github/workflows/pr-validation-fast.yml
.github/workflows/pr-validation.yml

This is I think difficult to test without just trying it. I will test it once this merges

Don't run long CI when the change is only a docs change

---

.github/workflows/pr-validation.yml

Run PR validation even on docs changes again

---

.github/workflows/pr-validation.yml

Fix integration test CI

---

.github/workflows/pr-validation-fork.yml

With the upgrade of `actions/github-script` to **v6**, some properties have been moved to the subproperty `rest`. 
I missed this one when doing the upgrade.

Fix PR Validation workflow for forks

---

docs/hugo/content/guide/authentication/_index.md
docs/hugo/content/guide/authentication/credential-format.md
v2/README.md

- Clarify that Workload Identity is recommended for production.
- Mention Workload Identity in the getting started section.
This fixes #1326.

Update managed identity documentation some

---

v2/internal/controllers/reconcile_policy_test.go
v2/internal/controllers/recordings/Test_ReconcilePolicySkip_CreatesSecretAndConfigMap.yaml
v2/internal/reconcilers/arm/azure_generic_arm_reconciler.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go

Emit ConfigMaps/Secrets even if reconcile-policy is skip

---

docs/hugo/content/guide/breaking-changes/_index.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.2.0.md

Adds breaking changes documentation and steps for upgrading.

Add breaking changes doc for v2.2.0

---

v2/charts/azure-service-operator/templates/networkpolicies.yaml

Fix issue with egress network policy blocking DNS

---

.github/workflows/codeql-analysis.yml
.github/workflows/merge-queue-cla.yaml
.github/workflows/pr-validation-docs.yml

Allows more actions to be triggered by merge groups.

Allow merge group triggering

---

.github/workflows/merge-queue-cla.yaml

When running as a part of a merge queue, the individual PRs will already satisfy the license/cla check.

Use script for license/cla

---

.github/workflows/merge-queue-cla.yaml

Fix syntax error

---

.github/workflows/merge-queue-cla.yaml

Fix workflow

---

docs/hugo/content/guide/authentication/credential-format.md

A couple of Azure CLI pages have moved - this PR updates the links, along with a bit of markdown tidyup triggered by a plugin.

Fix broken links

---

.github/workflows/live-validation.yml
.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml
scripts/v2/linux-docker-use-ssd.sh

Log disk stuff

---

.github/workflows/deploy-site.yml

Only run the workflow to update our website if some of the content has changed.
This should reduce the level of spam notifications by only running the site workflow when there's something to publish.

Only push site when content changed

---

v2/api/apimanagement/v1api20220801/service_spec_arm_types_gen.go
v2/api/apimanagement/v1api20220801/service_status_arm_types_gen.go
v2/api/apimanagement/v1api20220801/service_status_arm_types_gen_test.go
v2/api/apimanagement/v1api20220801/service_types_gen.go
v2/api/apimanagement/v1api20220801/service_types_gen_test.go
v2/api/apimanagement/v1api20220801/structure.txt
v2/api/apimanagement/v1api20220801/zz_generated.deepcopy.go
v2/api/apimanagement/v1api20220801storage/service_types_gen.go
v2/api/apimanagement/v1api20220801storage/service_types_gen_test.go
v2/api/apimanagement/v1api20220801storage/structure.txt
v2/api/apimanagement/v1api20220801storage/zz_generated.deepcopy.go
v2/azure-arm.yaml
v2/internal/controllers/controller_resources_gen.go
v2/internal/controllers/crd_apimanagement_20220801_test.go

Small APIM fixups

---

.github/workflows/pr-validation.yml

Adds retries to the `go get` phase to make it more resilient.

Make go get more resilient

---

.github/workflows/pr-validation.yml

Unconditionally run the step for merge queues

Tweak skip condition again

---

v2/api/cache/v1api20230401/redis_spec_arm_types_gen.go
v2/api/cache/v1api20230401/redis_status_arm_types_gen.go
v2/api/cache/v1api20230401/redis_types_gen.go
v2/api/containerservice/v1api20230315preview/fleets_update_run_spec_arm_types_gen.go
v2/api/containerservice/v1api20230315preview/fleets_update_run_status_arm_types_gen.go
v2/api/containerservice/v1api20230315preview/fleets_update_run_types_gen.go
v2/api/containerservice/v1api20230315previewstorage/fleets_update_run_types_gen.go
v2/api/synapse/v1api20210601/workspace_spec_arm_types_gen.go
v2/api/synapse/v1api20210601/workspace_status_arm_types_gen.go
v2/api/synapse/v1api20210601/workspace_types_gen.go
v2/azure-arm.yaml

Updates the submodule to the latest `main` so we can import (in later PRs) the latest API versions.
Needed to add configuration to avoid a sibling name collision.
As a side effect, some documentation comments are updated.

Update Spec reference submodule

---

docs/hugo/content/guide/breaking-changes/breaking-changes-v2.2.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.4.0.md

* Describes how to use asoctl clean crds to remove beta resources.

Add v2.4.0 breaking change documentation

---

docs/hugo/content/guide/configmaps.md

Fixes broken links in our guide.

Update links to use non-beta resources

---

Taskfile.yml
scripts/v2/wait-for-operator-ready.sh

* Stops using the old CRD label for discovery and starts using the new one.

Fix upgrade test

---

docs/hugo/content/guide/configmaps.md

Caused by changes in samples directory in #3606

Fix broken link for UAI sample in docs

---

scripts/v2/clean-orphan-role-assignments.sh
scripts/v2/delete-kind-wi-storage.sh
scripts/v2/make-mi-fic.sh

Had been meaning to make something like this for a while.

Orphan role assignment cleanup script

---

.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml

Publish the images using the beefier build agents

---

.github/workflows/api-docs-repo.yaml
.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml
.github/workflows/helm-chart-repo.yaml
.github/workflows/live-validation.yml
.github/workflows/pr-validation-fork.yml
.github/workflows/pre-release-tests.yaml
.github/workflows/visualize-repo.yml

Add permissions section to workflows

---

v2/internal/genericarmclient/generic_client_test.go
v2/internal/reconcilers/azuresql/local_user.go
v2/internal/reconcilers/mysql/local_user.go
v2/internal/reconcilers/postgresql/postgresql_user_reconciler.go
v2/internal/resolver/config_map_resolver.go
v2/internal/resolver/resolver.go
v2/internal/resolver/secret_resolver.go
v2/pkg/genruntime/arm_transformer.go
v2/pkg/genruntime/configmaps.go
v2/pkg/genruntime/resolved.go

This is needed to support resolving a map[string]string for collections of secrets (part of #3435)

Make Resolver generic in value parameter too

---

.github/workflows/create-release-experimental.yml

Relates to https://github.com/Azure/azure-service-operator/issues/3719
Include note about crdPattern for experimental releases to make sure people know what to expect
N/A

chore: Include note about crdPattern for experimental releases

---

v2/internal/reconcilers/generic/generic_reconciler.go

Avoid superfluous error log in DELETE case

---

ROADMAP.md
scripts/check-changes.sh

Adds `ROADMAP.md` as suggested in #3648 to make our roadmap more visible to users.
Closes #3648

Create ROADMAP file 

---

.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml

Ensure that the release pipelines dont hit disk full

---

docs/hugo/content/contributing/create-a-new-release.md

A recent documentation change introduced a broken link, though it's unclear how that change made it through CI (a problem to solve separately).
Currently that broken link is blocking all PRs as the CI checks fail.

Fix broken internal link

---

docs/hugo/content/design/ADR-2024-02-Upstream-Deletion/_index.md
docs/hugo/content/design/_index.md

If/when a resource included in ASO is deleted from the Azure OpenAPI repo, what happens to ASO? 
In this ADR, I document the effects.
Closes #2373 

Document the effects of upstream deletion

---

v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Kubernetesconfiguration_v1api_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Managedidentity_v1api20181130_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Managedidentity_v1api20220131preview_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Managedidentity_v1api20230131_CreationAndDeletion.yaml
v2/internal/controllers/samples_test.go
v2/internal/testcommon/samples_tester.go

Closes #3544 
This PR adds a separate methods to set ownership for refs and samples. Added check in `setSamplesOwnershipAndReferences` to lookup for owner in refs.

Allow samples to use random names when owner exists in refs directory

---

.github/workflows/ok-to-test.yml

Updating the workflow to use latest version

Update peter-evans/slash-command-dispatch to v4

---

Makefile
controllers/apimgmt_controller_test.go
controllers/azuresql_combined_test.go
controllers/blobcontainer_controller_test.go
controllers/cosmosdb_controller_test.go
controllers/eventhub_storageaccount_controller_test.go
controllers/mysql_combined_test.go
controllers/secret_naming_version_test.go

Fix ASOv1 pipeline

---

azure-pipelines.yml

Fix ADO pipeline auth issues

---

v2/api/documentdb/customizations/database_account_extensions.go

Mark capacity errors for documentdb as fatal

---

docs/hugo/content/guide/asov1-asov2-migration/databaseusers.md
docs/hugo/content/guide/secrets.md

Fix broken docs links

---

.github/workflows/create-release-experimental.yml
docs/hugo/content/guide/installing-from-yaml.md
docs/hugo/content/tools/asoctl.md
v2/cmd/asoctl/cmd/export.go
v2/cmd/asoctl/cmd/root.go
v2/cmd/asoctl/cmd/template.go
v2/cmd/asoctl/internal/template/template.go
v2/cmd/asoctl/internal/template/template_test.go
v2/cmd/asoctl/internal/template/testdata/local.yaml

Add asoctl template command

---

v2/charts/azure-service-operator/templates/networkpolicies.yaml
v2/config/certmanager/certificate.yaml

Also, amend the webhook self signed certificate to have an issuer

Fix Ingress network policy to work with cilium

---

.github/workflows/create-release-experimental.yml

I hit a few different errors trying the command in the release notes of the experimental release to install ASO. These changes should fix those.

Update install command for experimental releases

---

docs/hugo/content/contributing/add-a-new-code-generated-resource.md
v2/internal/testcommon/kube_per_test_context.go

Fixes a documentation link broken by a recent PR.
Also improves the log headers generated by our recorded tests, including the resource type in each one.

Fix broken documentation link

---

.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml
Taskfile.yml

Ensure that az-login has been run before docker login and push

---

.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml

We missed including the subscription ID in the docker push command

Fix release part 2

---

.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml

Fix release part 3

---

scripts/v2/create-kind-wi-storage.sh

Use Azure Storage static web serving rather than public access

---

docs/hugo/content/tools/generator.md

Clarify documentation of code generator

---

docs/hugo/content/contributing/testing.md

Document required secrets

---

docs/hugo/content/guide/breaking-changes/breaking-changes-v2.0.0-beta.4.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.0.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.1.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.2.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.4.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.6.0.md

Fix breaking changes documentation ordering to be consistent

---

docs/hugo/content/reference/_index.md
docs/hugo/content/reference/alertsmanagement/_index.md
docs/hugo/content/reference/monitor/_index.md

After merging #4052, we ran our CRD documentation generator and merged #4068. 
Now CI builds are broken because new runs of our code generator are linking to the new files, and this shows as changes.

Update docs with links to resources

---

docs/v1/services/azuresql/azuresql.md

Note that this password was never valid, but we're redacting it anyway just so folks don't copy it or get confused and think that it is/was valid.

Redact password

---

.github/workflows/live-validation.yml
.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml

Also use -e consistently rather than --env in docker cmds for actions

Fix prerelease tests by passing HOSTROOT

---

docs/hugo/content/guide/secrets.md

Improve secret rotation documentation, based on user pattern

---

docs/hugo/content/guide/breaking-changes/breaking-changes-v2.8.0.md

Breaking changes docs

---

v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_azureserviceoperator-crd-reader-rolebinding.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_azureserviceoperator-manager-rolebinding.yaml
v2/charts/azure-service-operator/values.yaml

Closes #3837 
This PR adds support to specify image pull secrets in the helm chart. Also, refactors the helm chart to fix indentations.

Add support to specify image pull secrets in ASOv2 helm chart

---

docs/hugo/content/_index.md

Added default namespace as option.

---

.github/workflows/create-release-official.yml

Add a missing AZURE_SUBSCRIPTION_ID var injection

Fix official release workflow

---

ROADMAP.md

ROADMAP update

---

Taskfile.yml

Temporarily disable KIND tests in CI

---

docs/hugo/content/guide/aso-controller-settings-options.md
v2/pkg/common/config/config.go

Add missing aso-controller-settings documentation

---

v2/api/documentdb/v1api20231115/database_account_spec_arm_types_gen.go
v2/api/documentdb/v1api20231115/database_account_status_arm_types_gen.go
v2/api/documentdb/v1api20231115/database_account_types_gen.go

Update Swagger submodule version

---

docs/hugo/content/_index.md
docs/hugo/content/guide/_index.md

Details for how to contact the ASO team are not as easy to find as we would like, so this PR adds details to two key places we think users might look.
Closes #4183 

Add contact details to our documentation site

---

.golangci.yml
v2/internal/controllers/crd_redhatopenshift_openshiftcluster_20230401_test.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/util/postgresql/roles.go
v2/tools/generator/internal/codegen/pipeline/remove_status_property_validations.go
v2/tools/generator/internal/conversions/property_conversions.go
v2/tools/generator/internal/reporting/structure_report_test.go

Fix new lint errors

---

v2/charts/azure-service-operator/templates/aadpodidentity.yaml
v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/values.yaml

Allows to override some hardcodes for deployment object.
Comparing with default values, these changes bring nothing except one default.
```diff
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app.kubernetes.io/name: azure-service-operator
app.kubernetes.io/version: v2.8.0
control-plane: controller-manager
name: azureserviceoperator-controller-manager
namespace: default
spec:
replicas: 1
+ revisionHistoryLimit: 10
selector:
matchLabels:
control-plane: controller-manager
template:
metadata:
annotations:
kubectl.kubernetes.io/default-container: manager
labels:
-       aadpodidbinding: aso-manager-binding
app.kubernetes.io/name: azure-service-operator
app.kubernetes.io/version: v2.8.0
control-plane: …
```

feat(helm): allow hardcodes to be configurable

---

v2/charts/azure-service-operator/values.yaml
v2/config/manager/manager.yaml

Improve security context restrictions

---

v2/cmd/controller/app/setup.go

Release lease when the pod is terminated

---

.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml

Prep integration-tests CI for being re-enabled

---

docs/hugo/content/contributing/create-a-new-release.md
docs/hugo/content/guide/breaking-changes/_index.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.9.0.md
docs/hugo/content/guide/conditions.md
docs/hugo/content/guide/upgrading.md

I spotted that we'd missed documenting our breaking changes for _several releases_. 
Docs are now up to date, and I've added an item to our checklist.
Also clarified our _Conditions_ page on when a reconciliation will next occur.

Add documentation of Breaking Changes

---

.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml

Actually read the CI env variables

---

docs/hugo/content/contributing/create-a-new-release.md
docs/hugo/content/guide/conditions.md

Hugo is logging an error while building our docs:
```
[doc:build-site] Error: Error building site: "/workspace/docs/hugo/content/guide/conditions.md:15:130": 
unrecognized character in shortcode action: U+007D '}'. Note: Parameters with non-alphanumeric args must be quoted
```
This PR fixes this syntax problem. #4267 is so we fix the underlying issue.

Fix site building

---

.github/workflows/pre-release-tests.yaml
Taskfile.yml
docs/hugo/content/contributing/add-a-new-code-generated-resource.md
docs/hugo/content/contributing/testing.md
scripts/v2/create-kind-wi-storage.sh
scripts/v2/delete-kind-wi-storage.sh
scripts/v2/workloadidentitystorage/deploy.sh
scripts/v2/workloadidentitystorage/vars.sh

Use a static storage account for OIDC issuer and re-enable KIND-based integration tests

---

Taskfile.yml
v2/cmd/asoctl/cmd/export_template.go
v2/cmd/asoctl/cmd/import_azure_resource.go
v2/cmd/asoctl/pkg/importresources/importable_arm_resource.go
v2/cmd/asoctl/pkg/importresources/importable_resource.go

For some reason this isn't failing CI but it's constantly reformatting on my local

Fix gofumpt formatting

---

docs/hugo/content/guide/frequently-asked-questions.md

In #4285 @neil-111 reported that a simple LUA script can make ASO resources show up properly in ArgoCD. Promoting this information in to our FAQ for discoverability.

Add ArgoCD FAQ item

---

.golangci.yml

Default in switch is exhaustive

---

docs/hugo/content/contributing/add-a-new-code-generated-resource.md

Adds to the docs on using our code generator, documenting what to do when newly added object model configuration has no effect.

Extend new resource troubleshooting with another case

---

.devcontainer/Dockerfile
.devcontainer/install-dependencies.sh

Update Go version and versions of tools in the container. Staying up to date is useful. 

Update container dependencies

---

docs/hugo/content/guide/breaking-changes/breaking-changes-v2.10.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.9.0.md

This PR adds breaking changes docs for v2.10.0

Add 2.10 breaking changes doc

---

Taskfile.yml

Fix issue with upgrade Taskfile target

---

.devcontainer/install-dependencies.sh

Fix incorrect Trivy download link

---

v2/api/dbforpostgresql/v1/user_types.go

Clarify some PostgreSQL User documentation

---

docs/hugo/content/contributing/chatgpt-release-template.md

Not sure if it'll be useful or not but worth a try

Template for chatgpt to help format release notes

---

docs/hugo/content/guide/_index.md
docs/hugo/content/tutorials/_index.md

Somewhere in a recent package update, rendering of cards on our documentation site broke - I think because we were using them wrong and now docsy has become increasingly strict.

Fix display of cards

---

docs/hugo/content/contributing/_index.md
docs/hugo/content/contributing/hints-and-tips/_index.md

Captures some advice recently given to a contributor for reference by others.

Capture recent advice in our docs

---

docs/hugo/content/guide/breaking-changes/breaking-changes-v2.10.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.9.0.md

Fix breaking change documentation sidebar ordering

---

v2/api/dbforpostgresql/v1api20221201/arm/flexible_servers_configuration_spec_types_gen.go
v2/api/dbforpostgresql/v1api20221201/arm/flexible_servers_configuration_status_types_gen.go
v2/api/dbforpostgresql/v1api20221201/flexible_servers_configuration_types_gen.go

Update rest-api-specs submodule

---

docs/hugo/content/guide/breaking-changes/breaking-changes-v2.11.0.md
docs/hugo/content/guide/configmaps.md
docs/hugo/content/guide/expressions.md
docs/hugo/content/guide/secrets.md

Documentation for upcoming v2.11.0 release

---

v2/cmd/asoctl/pkg/importresources/importable_arm_resource.go

While doing other testing, I discovered that the `Microsoft.Insights` uses a different error code (`ResourceTypeNotSupported`) to other resource providers when attempting to list `DiagnosticSetting` child resources. 
This PR adds the new error code to our list of suppressions.

Add ResourceTypeNotSupported to list of skipped error codes

---

v2/api/network/customizations/virtual_network_subnet_extensions.go

Elide subnet IPConfiguration field when it passes 2000 entries

---

v2/cmd/asoctl/cmd/import_azure_resource.go

Adds the commandline switch `--simple-logging` to turn off the progress bars and just use normal text logging when importing.

Add asoctl commandline switch for simpler logging

---

v2/internal/duration/duration.go
v2/internal/genericarmclient/cloud_error.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/test_logger.go
v2/pkg/genruntime/conditions/conditions.go
v2/pkg/genruntime/configmaps.go
v2/pkg/genruntime/core/destination_expression.go
v2/pkg/genruntime/resource_reference.go
v2/pkg/genruntime/secrets.go
v2/tools/generator/internal/astmodel/allof_type.go
v2/tools/generator/internal/astmodel/oneof_type.go
v2/tools/generator/internal/astmodel/type_set.go
v2/tools/generator/internal/astmodel/validated_type.go

This PR fixes issues raised by linter after update

Fix recvcheck linter issues

---

docs/hugo/content/design/ADR-2025-01-ARM-References/_index.md
docs/hugo/content/design/_index.md

Design document for making improvements to the way we handle ARM references. 
Key value is in allowing us to correct earlier mistakes where a property wasn't identified as an ARM reference prior to release.

ADR for improving ARM references

---

Taskfile.yml
v2/internal/testcommon/vcr/v3/test_recorder_test.go

Increase integration test timeout

---

v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/values.yaml
v2/cmd/controller/app/setup.go
v2/config/manager/manager.yaml
v2/config/manager/manager_image_patch.yaml
v2/internal/crdmanagement/manager.go
v2/internal/crdmanagement/manager_test.go

- Also set GOMEMLIMIT (which helps avoid OOMKill)

Prevent OOMKill while listing CRDs

---

docs/hugo/.htmltest.yml
docs/hugo/content/_index.md
docs/hugo/content/guide/authentication/_index.md
docs/hugo/content/guide/best-practices/security.md

Fixes some broken links and updates the suppressions in .htmltest.yml`
Especially links.

Fix issues with broken and inaccessible documentation links

---

docs/hugo/content/guide/aso-controller-settings-options.md
docs/hugo/content/guide/authentication/credential-format.md
v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/templates/secret.yaml
v2/charts/azure-service-operator/values.yaml
v2/cmd/asoctl/cmd/import_azure_resource.go
v2/cmd/controller/app/setup.go
v2/config/manager/manager_image_patch.yaml
v2/go.mod
v2/internal/config/vars.go
v2/internal/genericarmclient/generic_client.go
v2/internal/identity/client_certificate_credential.go
v2/internal/identity/credential_provider.go
v2/internal/identity/credential_provider_test.go
v2/internal/identity/token_credential_provider.go
v2/internal/identity/token_credential_provider_test.go
v2/internal/reconcilers/arm/arm_client_cache.go
v2/internal/reconcilers/arm/arm_client_cache_test.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/testcommon/vcr/v1/test_replayer.go
v2/internal/testcommon/vcr/v3/test_recorder.go
v2/pkg/common/cloud/cloud.go
v2/pkg/common/config/config.go
v2/pkg/common/config/parse.go

Support multitenant auth

---

Taskfile.yml

Increase test timeout for -cover target too

---

README.md
docs/v1/README.md

Updates our docs for ASO v1 indicating that it is now officially deprecated.

Document deprecation of ASO v1

---

v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/values.yaml

_Thanks for sending a pull request! Delete this text and tell us why we need this change._

Enable using json logging in helm chart (#4608)

---

docs/hugo/content/contributing/dependencies.md

Fix dependencies docs

---

docs/hugo/content/guide/diagnosing-problems/_index.md
docs/hugo/content/guide/diagnosing-problems/azure-throttling.md
docs/hugo/content/guide/diagnosing-problems/reconciliation-frequency.md

Extends our documentation with more explicit guidance for two common scenarios.
Closes #4625
Closes #4627

Add more guides for troubleshooting

---

v2/api/cdn/v1api20230501/afd_origin_types_gen.go
v2/api/cdn/v1api20230501/arm/afd_origin_spec_types_gen.go
v2/api/cdn/v1api20230501/storage/afd_origin_types_gen.go
v2/api/cdn/v1api20230501/storage/structure.txt
v2/api/cdn/v1api20230501/storage/zz_generated.deepcopy.go
v2/api/cdn/v1api20230501/structure.txt
v2/api/cdn/v1api20230501/zz_generated.deepcopy.go
v2/azure-arm.yaml
v2/internal/controllers/controller_resources_gen.go

Support sourcing AFDOrigin HostName from config

---

v2/api/signalrservice/v1api20240301/replica_types_gen.go
v2/azure-arm.yaml
v2/tools/generator/internal/config/transform_result.go
v2/tools/generator/internal/config/type_transformer.go

Marks the `sku` property of `signalrservice/ReplicaSpec` as mandatory.
Closes #4672

Mark Replica_Spec.Sku as required

---

v2/api/network/customizations/dns_forwarding_ruleset.go

Retry on certain BadRequests for DnsForwardingRuleset

---

.github/workflows/pr-validation-fork.yml

Actually fix ok-to-test

---

docs/hugo/content/guide/frequently-asked-questions.md

We recently had a question about performance & scaling; capturing the details of that answer here for others to see.

Add perf item to FAQ

---

docs/hugo/content/contributing/chatgpt-release-template.md

Update AI prompt for release

---

docs/hugo/.htmltest.yml

Restores `htmltest` suppresssions for StackOverflow that we didn't need 3 months ago, but do need again now.

Restore stack overflow suppressions

---

v2/charts/azure-service-operator/templates/v1_service_azureserviceoperator-controller-manager-metrics-service.yaml

Deploy metrics service in multitenant mode

---

docs/hugo/content/guide/authentication/multitenant-deployment.md

Add more visible warning for multitenant deployment mode

---

docs/hugo/content/guide/diagnosing-problems/reconciliation-failures.md

Adds a new troubleshooting guide (TSG) for users.
Closes #4624
Partially addresses #4626

Add TSG on handling reconciliation failures

---

v2/internal/crdmanagement/manager.go

As reported in #4756, ASO can experience a panic during startup, with the following stack trace:
```go
I0603 13:31:47.502361       1 manager.go:340] "Acquiring leader lock..." logger="controllers"
I0603 13:31:47.502440       1 leaderelection.go:257] attempting to acquire leader lease azureserviceoperator-system/controllers-leader-election-azinfra-generated...
E0603 13:33:11.669879       1 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
goroutine 45 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x7b35c78, 0xb58d700}, {0x657b6c0, 0xb4c94b0})
/go/pkg/mod/k8s.io/apimachinery@v0.32.3/pkg/util/runtime/runtime.go:107 +0xbc …
```

Eliminate nil panic if leaderContext nil

---

v2/api/dbforpostgresql/v1api20240801/arm/flexible_server_spec_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_server_status_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_advanced_threat_protection_settings_spec_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_advanced_threat_protection_settings_status_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_backup_status_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_configuration_spec_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_configuration_status_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_database_spec_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_database_status_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_firewall_rule_spec_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_firewall_rule_status_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_virtual_endpoint_spec_types_gen.go
v2/api/dbforpostgresql/v1api20240801/arm/flexible_servers_virtual_endpoint_status_types_gen.go
v2/api/dbforpostgresql/v1api20240801/flexible_server_types_gen.go
v2/api/dbforpostgresql/v1api20240801/flexible_servers_advanced_threat_protection_settings_types_gen.go
v2/api/dbforpostgresql/v1api20240801/flexible_servers_backup_types_gen.go
v2/api/dbforpostgresql/v1api20240801/flexible_servers_configuration_types_gen.go
v2/api/dbforpostgresql/v1api20240801/flexible_servers_database_types_gen.go
v2/api/dbforpostgresql/v1api20240801/flexible_servers_firewall_rule_types_gen.go
v2/api/dbforpostgresql/v1api20240801/flexible_servers_virtual_endpoint_types_gen.go
v2/api/dbforpostgresql/v1api20240801/storage/flexible_server_types_gen.go

Pulls in the latest submodule as a separate PR.
Only changes of consequence are documentation updates for PostgreSQL.

Update Azure Rest API Specs submodule

---

docs/hugo/content/guide/aso-controller-settings-options.md
docs/hugo/content/guide/authentication/credential-format.md
docs/hugo/content/guide/crd-management.md
docs/hugo/content/guide/frequently-asked-questions.md

Entra resources require an additional environment variable `ENTRA_APP_ID` which needs to be documented.

Add docs for Entra resources

---

v2/internal/controllers/reconcile_policy_test.go

Fix flaky ReconcilePolicy test

---

v2/internal/tests/api_linting_test.go

Add test to check all or none implement default/validate helpers

---

README.md

_Thanks for sending a pull request! Delete this text and tell us why we need this change._

Replaced a link in the documentation that didn't work

---

.github/instructions/copilot-instructions.md
.github/instructions/new-resource-instructions.md

Incremental improvements to our CoPilot instructions.

Improve copilot instructions for working on ASO

---

v2/cmd/asoctl/internal/crd/cleaner.go
v2/internal/crdmanagement/deprecation.go

Refactor deprecation check to shared crdmanagement package

---

docs/hugo/content/guide/annotations.md
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_azureserviceoperator-crd-manager-role.yaml
v2/cmd/controller/app/setup.go
v2/config/rbac/crd_manager_role.yaml
v2/internal/crdmanagement/deprecation.go
v2/internal/reconcilers/generic/generic_reconciler.go
v2/internal/reconcilers/migration/crd/reconciler.go
v2/internal/reconcilers/migration/crd/reconciler_test.go
v2/pkg/common/controllerutils/singleton/singleton.go
v2/pkg/common/labels/labels.go

* Add crd storedVersions deprecation controller
* Add controllutils for singleton controller
Fixes #4376.

Add crd storedVersions deprecation controller

---

v2/internal/controllers/recordings/Test_Owner_IsImmutableOnceSuccessfullyCreated.yaml
v2/internal/controllers/recordings/Test_Owner_IsMutableIfNotSuccessfullyCreated.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Keyvault_v1api20210401preview_CreationAndDeletion.yaml
v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Synapse_v1api_CreationAndDeletion.yaml

We know that the reasons some tests are flaky were addressed in v2 of our HTTP test recording framework, but we haven't rerecorded all the tests yet.
This PR rerecords a few known flakes in the hope that things will be more stable.
Closes #4223 
New issue for tracking test flakes: #4892

Update recordings of flaky tests

---

docs/hugo/content/guide/breaking-changes/_index.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.15.0.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.9.0.md

Documents the (very small) breaking change in v2.15
Also updates the breaking changes docs, fixing formatting and removing obsolete information.

Document breaking changes

---

v2/internal/controllers/crd_sql_server_failover_group_test.go
v2/internal/controllers/crd_sql_server_test.go
v2/internal/controllers/recordings/Test_SQL_Server_CRUD.yaml
v2/internal/controllers/recordings/Test_SQL_Server_FailoverGroup_CRUD.yaml

Update SQL Server tests to v2 recordings
