Azure/azure-service-operator

config/default/manager_webhook_patch.yaml
main.go

Closes #1036 
Add a healthy check in controller manager to ensure the connection to Azure is healthy. 
This is indeed the same pull request as https://github.com/Azure/azure-service-operator/pull/1041. Due to the repo sync issue, has to create a new repo and made the new pull request. Comments could be found from the old link though. 

add health check to controller manager

---

azure-pipelines.yml

Closes #1132 
- We were building the helm chart in the pipeline, but that results in us not being able to validate the Helm chart thats checked in and makes it impossible for us to catch the Helm chart not being updated in the repo. So the pipeline now uses the checked in charts and pushes that to MCR/release. 
- Also cleans up the CRDs and deployment in the cluster at the end of the deploy test
Latest run of the pipeline - https://dev.azure.com/azure/azure-service-operator/_build/results?buildId=10817&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

New pipeline update: Remove Helm chart packaging stage and use checked in Helm chart instead

---

pkg/resourcemanager/mysql/mysqluser/mysqluser.go
pkg/resourcemanager/mysql/mysqluser/mysqluser_manager.go
pkg/resourcemanager/mysql/mysqluser/mysqluser_reconcile.go

This PR is part of  #1147, also fix the username bug found during customer test in engagement3. 
The PR has fixes: 
-- As customer requested,  MySQL Username should be created using the default format: ```<username>@%```, but not ```<username>@<servername>```.The '%' is the hostname and is different than the mysql login name that should be with the ```<username>@<servername> ``` format. 
https://dev.mysql.com/doc/refman/5.7/en/create-user.html
https://dev.mysql.com/doc/refman/5.7/en/account-names.html
If the user was created without specify the '@' part, it will be created using the default format.  
-- By specify the 'interpolateParams' parameter and MySQL CreateUser and DropUser now use the SQL injection to create SQL query command.  
**Special …

Corret the MySQL username format to <username>@%, and use SQL injection for MySQL CreateUser and DropUser

---

docs/howto/contents.md

Azure Service Operator Documentation has a link to the Testing page. But that link is broken and it is giving a 404 error. This PR is fixing that broken link.

Fixing broken link of 'Testing' content

---

main.go

Some users are getting restarts related to the health probe:
```
Warning  Unhealthy  5m33s (x3707 over 3d)  kubelet, aks-nodepool1-29600608-vmss000002  Liveness probe failed: Get http://10.244.2.4:8081/healthz: dial tcp 10.244.2.4:8081: connect: connection refused
```
And since the current probe doesn't do anything too terribly substantial I am removing it until we can investigate and/or come up with a better check.

removing health probe 

---

azure-pipelines.yml

Updates ADO to not build of the change is just a docs change
I have also updated the ADO job to stop overriding the yaml (prior to now, the section of the YAML specifying when to build was ignored because it was overridden in the ADO backend).

Update to azure pipelines file

---

.devcontainer/devcontainer.json

VSC Go extension is hosted by Google now. This PR points to the new extension name.
This should fix #1230

Changed VSC Go extension name

---

charts/azure-service-operator/templates/generated/~g_v1_service_azureoperator-webhook-service.yaml
config/webhook/service.yaml

Update webhook service to listen on 443. This will prevent the need to update the current CRDs that specify 443 in their conversion config.
Closes #1251 
Without this change, creating Custom Resources that have CRD conversion webhook configs will fail.
:)

update port for webhook service to 443

---

api/v1alpha2/mysqlserver_types.go
pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go

Moves secret deletion to best effort.
**Special notes for your reviewer**: It was like this before and was changed as it looked like a bug. Turns out some customers liked the old behavior so we're reverting for now.
I've filed #1280 tracking a feature that should allow us to do both best effort and required deletions.

Move secret deletion to best effort again

---

pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go

A customer reported an issue where we failed to create a managed user but the error was very sparse. This should improve the error messages and also fix a few issues where we don't properly mark the resource as `FailedProvisoning`.

Improve managed user state management

---

docs/services/apimgmt/apimgmt.md
docs/services/appinsights/appinsights.md
docs/services/azuresql/azuresql.md
docs/services/keyvault/keyvault.md
docs/services/mysql/mysql.md
docs/services/postgresql/postgresql.md
docs/services/rediscache/rediscache.md
docs/services/resourcegroup/resourcegroup.md
docs/services/storage/blobcontainer.md
docs/services/storage/storageaccount.md
docs/services/virtualmachine/virtualmachine.md
docs/services/virtualnetwork/loadbalancer.md
docs/services/virtualnetwork/networkinterface.md
docs/services/virtualnetwork/publicipaddress.md
docs/services/virtualnetwork/virtualnetwork.md
docs/services/vmscaleset/vmscaleset.md
docs/virtualmachineextension/virtualmachineextension.md

- some of the documentation was moved around in https://github.com/Azure/azure-service-operator/commit/97bb1a23a314cfe6538559b6b9b4e898fd03c1d6#diff-d922fb40bc498ea697e996ac414f56cb
- not all links to the resourceprovision.md file appear to have been updated
- should hopefully make navigating the docs a little easier

update broken link in docs

---

pkg/resourcemanager/keyvaults/keyvault.go

The range variable is overwritten at each iteration, and &policy is the same. It's end up appending a newEntry containing the same ObjectID multiple times. Simple workaround is to use a local copy of that variable.

KeyVault multiple policies ObjectID fix

---

.github/stale.yml

Fixing stale bot message. We do not close any issues based on staleness.

Update GH stale bot

---

README.md

Minimum Kubernetes version (`cert-manager` requirement) was not noted.
[Link to rendered file.](https://github.com/Azure/azure-service-operator/blob/b3a3681f24d5777bcfc56b5f0e52074c9422c09a/README.md)
There was no minimum version for Kubernetes specified, but `cert-manager` (at least) requires 1.16.

Add pre-reqs to setup steps

---

.gitignore

This hides the dockerfile and bundle directory that the generate-operator-bundle target (#1285) generates so they don't get accidentally added to the repository.

Add operator bundle artifacts to .gitignore

---

controllers/mysql_combined_test.go
pkg/helpers/sqlrole.go
pkg/helpers/sqlrole_test.go
pkg/resourcemanager/mysql/mysqlhelper.go

This is related to but does not resolve #1311
We need to decide if we want to support this functionality at all. It's "easiest" for MySQL and harder for Azure SQL (I haven't even looked into PostgreSQL).

Update MySQL user roles when users are modified

---

api/v1alpha1/mysqlaaduser_types.go
config/samples/azure_v1alpha1_mysqlaaduser.yaml
pkg/resourcemanager/mysql/mysqlaaduser/reconcile.go

Adds support for MySQL AAD Users and Groups.
Difficult to test currently given the existing test infrastructure. As before with the Managed Identity pieces of this work I have confirmed this works manually (and we can rely somewhat on the standard user create tests to test the basic connect/etc pieces of the workflow).

Update to support MySQL AAD users and groups too

---

api/v1alpha1/mysqlserveradministrator_types.go
config/samples/azure_v1alpha1_mysqlserveradministrator.yaml
pkg/resourcemanager/mysql/mysqlhelper.go

The Sid field of a MySQLAdministrator resource referring to a managed identity should be the client ID for the identity, rather than the object ID as suggested by the comments. If the OID is used, MySQLAADUser resources that are created can't be reconciled - the error that comes back is `Azure AD access token is not valid for user 'identityname'`.
Also clarified some logging so we can see which server we're trying to connect to if there's a problem connecting.

Clarify documentation for sample MySQLAdministrator

---

api/v1alpha1/azuresqlvnetrule_types.go
api/v1alpha1/mysqlvnetrule_types.go
api/v1alpha1/postgresqlvnetrule_types.go
charts/azure-service-operator/crds/apiextensions.k8s.io_v1beta1_customresourcedefinition_azuresqlvnetrules.azure.microsoft.com.yaml
charts/azure-service-operator/crds/apiextensions.k8s.io_v1beta1_customresourcedefinition_mysqlvnetrules.azure.microsoft.com.yaml
charts/azure-service-operator/crds/apiextensions.k8s.io_v1beta1_customresourcedefinition_postgresqlvnetrules.azure.microsoft.com.yaml
config/samples/azure_v1alpha1_azuresqlvnetrule.yaml
config/samples/azure_v1alpha1_mysqlvnetrule.yaml
config/samples/azure_v1alpha1_postgresqlvnetrule.yaml
pkg/resourcemanager/azuresql/azuresqlshared/getgoclients.go
pkg/resourcemanager/azuresql/azuresqlvnetrule/azuresqlvnetrule.go
pkg/resourcemanager/azuresql/azuresqlvnetrule/azuresqlvnetrule_reconcile.go
pkg/resourcemanager/mysql/vnetrule/client.go
pkg/resourcemanager/mysql/vnetrule/reconcile.go
pkg/resourcemanager/psql/vnetrule/client.go
pkg/resourcemanager/psql/vnetrule/reconcile.go

VNET Rules may be required for VNETs in other subscriptions. The VNET rules continue to be created in the ASO's subscription. I've tested all three CRD changes.

Add optional VNET Subscription ID to VNET rules.

---

controllers/mysql_combined_test.go
pkg/helpers/sqlrole.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go

We would treat any error from getting the database in Azure as a signal that the database had already been removed.
This can mean that if there's a communication error when checking with Azure then we just remove the k8s database resource without trying to delete the Azure one (which is then orphaned).
Closes #1335

Don't ignore errors checking whether a being-deleted DB exists

---

api/v1alpha1/aso_types.go
api/v1alpha1/keyvault_types.go
api/v1alpha2/aso_types.go
api/v1beta1/aso_types.go
config/samples/azure_v1alpha1_keyvault.yaml
controllers/keyvault_controller_test.go
pkg/resourcemanager/keyvaults/keyvault.go
pkg/resourcemanager/keyvaults/keyvault_manager.go
pkg/resourcemanager/keyvaults/keyvault_test.go
pkg/secrets/keyvault/client.go
pkg/secrets/keyvault/client_test.go

The operator was originally reconciling AccessPolicy's after the rest of the KV
had been created (see: #1158). This isn't actually required because even doing
this there are tons of reasons that this can fail. I've filed #1351 to track
removing ClientID from the CRD in a future API version as there are a ton of
obscure ways that we can fail to translate that ID into an ObjectID.
Closes #1298

Provision AccessPolicy and KeyVault at same time

---

api/v1beta1/azuresqldatabase_types.go
config/samples/azure_v1beta1_azuresqldatabase.yaml
controllers/azuresql_combined_test.go
controllers/keyvault_controller_test.go
pkg/errhelp/errors.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_manager.go
pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go
pkg/resourcemanager/azuresql/azuresqlshared/getgoclients.go
pkg/resourcemanager/azuresql/azuresqlshared/sqlproperties.go
pkg/resourcemanager/azuresql/azuresqluser/azuresqluser_reconcile.go

Closes #1302
Adds support for Azure SQL short term retention alongside existing support for long term retention on the AzureSQLDatabase object.

Add AzureSQL short term retention policies

---

controllers/async_controller.go
controllers/suite_test.go
pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser.go
pkg/resourcemanager/azuresql/azuresqluser/azuresqluser.go

Adds a context with a 5 minute timeout for all reconcile loop passes to ensure that if for whatever reason something gets stuck, it doesn't block all reconciliation forever.
Also ensure that we specify a timeout when connecting to Azure SQL to avoid deadlocks in that codepath (see https://github.com/denisenkom/go-mssqldb/issues/609)

Prevent deadlocks in reconcilation loop

---

config/default/webhookcainjection_patch.yaml
controllers/async_controller.go
pkg/resourcemanager/appinsights/api_keys_reconcile.go
pkg/resourcemanager/appinsights/appinsights.go
pkg/resourcemanager/azuresql/azuresqlaction/azuresqlaction_reconcile.go
pkg/resourcemanager/azuresql/azuresqlserver/azuresqlserver_reconcile.go
pkg/resourcemanager/mysql/server/reconcile.go
pkg/resourcemanager/psql/server/server_reconcile.go
pkg/resourcemanager/storages/storageaccount/storageaccount_reconcile.go
pkg/resourcemanager/vm/reconcile.go
pkg/resourcemanager/vmext/reconcile.go
pkg/resourcemanager/vmss/reconcile.go
pkg/secrets/keyvault/client.go

- Fix issue where we were checking if a KeyVault was accessible very frequently. Instead just rely on error handling in the resource itself if creating a secret fails. This also gives a better error message.
- Fix bug in templates preventing webhook from getting correct certificate injected by `cert-manager`.

Bug fixes for release 1.0.19504

---

Makefile
azure-pipelines.yml
controllers/azurevirtualmachine_controller_test.go
controllers/azurevirtualmachineextension_controller_test.go
controllers/azurevmscaleset_controller_test.go
controllers/secret_naming_version_test.go
pkg/helpers/stringhelper.go
pkg/resourcemanager/appinsights/api_keys_reconcile.go
pkg/resourcemanager/appinsights/appinsights.go
pkg/resourcemanager/appinsights/manager.go
pkg/resourcemanager/azuresql/azuresqlfailovergroup/azuresqlfailovergroup_reconcile.go
pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser.go
pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go
pkg/resourcemanager/azuresql/azuresqlserver/azuresqlserver_reconcile.go
pkg/resourcemanager/azuresql/azuresqluser/azuresqluser_reconcile.go
pkg/resourcemanager/cosmosdbs/cosmosdb_reconcile.go
pkg/resourcemanager/eventhubs/hub.go
pkg/resourcemanager/mysql/server/reconcile.go
pkg/resourcemanager/psql/server/server.go
pkg/resourcemanager/psql/server/server_reconcile.go
pkg/resourcemanager/rediscaches/actions/rediscacheaction_reconcile.go
pkg/resourcemanager/rediscaches/redis/rediscache_reconcile.go
pkg/resourcemanager/rediscaches/shared.go
pkg/secrets/keyvault/client.go

- Fix issue where namespace was mistakenly included in v1 secret
naming key generation. Some resources are not expected to have
namespace prefix in certain KeyVault scenarios.
- Increase CI timeout a bit.
- SecretClient should not be modified by options in Ensure as Managers are singletons and share state between resources.

Fix v1 secret naming

---

.gitignore
api/v1alpha1/conversion_stash.go
api/v1alpha1/mysqlaaduser_conversion.go
api/v1alpha1/mysqlaaduser_types_test.go
api/v1alpha1/mysqluser_conversion.go
api/v1alpha1/mysqluser_types_test.go
controllers/mysql_combined_test.go

Previously if a v1alpha2 `MySQLUser` or `MySQLAADUser` had server-level roles or roles in more or fewer than one database, trying to convert it to a v1alpha1 representation would fail because the older format could only refer to exactly one database. This caused something (likely a cache but I'm not entirely sure ☹️) in the system to go into a loop trying to request the resource as v1alpha1 every second and spamming the log with errors.
Change the *from* conversion to store the affected fields as JSON in an `azure.microsoft.com/convert-stash` annotation, and the *to* conversion to incorporate the annotation values when going back to v1alpha2.
Fixes #1388.

Always allow converting MySQL[AAD]Users back to v1alpha1

---

pkg/resourcemanager/rediscaches/redis/rediscache_reconcile.go

A user reported a case where a RedisCache was provisioned and working but was marked as FailedProvisioning=true. This seems to have happened because it initially failed (possibly a temporary error that we aren't checking for), and then on a subsequent periodic reconciliation the ARM query reported that it was deployed successfully. Use the SetProvisioned helper method (and friends) to prevent this state.
Fixes #1394 

RedisCache - ensure FailedProvisioning=false when Provisioned=true

---

api/v1beta1/azuresqlfailovergroup_types.go
config/samples/azure_v1alpha1_azuresqlfailovergroup.yaml
controllers/azuresqlfailovergroup_controller_test.go
pkg/resourcemanager/azuresql/azuresqlshared/sqlproperties.go

- Validate FailoverGroup policy has valid values
- This fixes #1386.
- Fix AzureSQLFailoverGroup sample

Minor Azure SQL FailoverGroup improvements

---

controllers/mysql_combined_test.go
pkg/resourcemanager/mysql/server/reconcile.go

Previously this was being dropped on the floor unless the create call returned an AsyncOpIncompleteError. This works fine as long as the server eventually is available. One situation where it fails is creating a replica at the same time as the leader server (or very quickly after). In that case the create server call returns no error, but querying the poll URL shows that the creation failed because the SourceServerID didn't match anything. Without capturing the poll URL on the initial creation the reconciliation gets stuck because it thinks that the 404 it gets when checking for the server indicates that it's just not ready yet - provisioning never goes back to false and it doesn't retry the creation. This could happen in other eventual error cases …

mysqlserver: Keep track of the polling URL when creating

---

Dockerfile

We've already changed the webhook listener to start on 9443, so there's no need for the manager to run as root - this reduces the attack surface if the pod is compromised somehow.
Closes #1406 

Switch to use the distroless nonroot base image and user

---

config/default/manager_image_patch.yaml
go.sum

Having the tenant and subscription required causes issues in the community-operators CI for the operator bundle, because it tries to deploy the operator without any configuration. There is precedent here: client ID is already marked as optional.  Additionally tenant and subscription would need to become optional as part of implementing the operator-per-namespace multitenancy model. 
If the fields are left out the error is correctly reported on resources when they are reconciled.

Make tenant and subscription IDs optional in the config

---

Makefile

Closes #1270.
- Update CRDs to use v1 of the CRD API.
- Forces preserveUnknownFields to false.

Update CRDs to v1 apiversion

---

scripts/check-changes.sh

This adds the `hack` directory (where `k8s-infra`-sourced code lives) to the `IGNORE_FILTERS` set in `check-changes.sh`, which means that the ASO pipeline will not need to be re-run when only `k8s-infra` code changes.

Add /hack/ directory to IGNORE_FILTERS

---

hack/generated/controllers/recordings/Test_CosmosDB_CRUD.yaml
hack/generated/controllers/recordings/Test_ResourceGroup_CRUD.yaml
hack/generated/controllers/recordings/Test_ServiceBus_Namespace_CRUD.yaml
hack/generated/controllers/recordings/Test_StorageAccount_CRUD.yaml
hack/generated/pkg/armclient/recordings/Test_NewResourceGroupDeployment.yaml
hack/generated/pkg/armclient/recordings/Test_NewResourceGroupDeployment_Error.yaml
hack/generated/pkg/testcommon/counting_roundtripper.go
hack/generated/pkg/testcommon/error_translating_roundtripper.go
hack/generated/pkg/testcommon/kube_test_context_envtest.go
hack/generated/pkg/testcommon/test_context.go

A few changes here:
This makes sure the request/response pair is for the correct request (by default, `go-vcr` only checks the HTTP method/URL). To achieve this we blank out any dates/timestamps that are found in bodies, since they cause a mismatch when the test is rerun.
We had code to track the request count at a per-URL level so that we handle multiple requests to the same URL properly in recordings (so that a series of polling GETs can get back different responses, for example), but this was not being added properly. Now it is.
At the moment when running record/replay tests and an interaction (request+response) cannot be located, it is hard to figure out what went wrong. This PR adds a wrapper around the `go-vcr` code to add more context about what went wrong.
An example message in …

Improve record/replay tests

---

hack/generated/pkg/genruntime/resource_reference.go
hack/generated/pkg/genruntime/resource_reference_test.go
hack/generated/pkg/reflecthelpers/reflect_helpers_test.go
hack/generator/pkg/astmodel/kubernetes_admissions_validations.go
hack/generator/pkg/astmodel/kubernetes_admissions_validator.go
hack/generator/pkg/astmodel/kubernetes_resource_interface.go
hack/generator/pkg/astmodel/std_references.go
hack/generator/pkg/codegen/testdata/ArmResource/Arm_oneof_resource_conversion_on_arm_type_only_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_dependent_resource_and_ownership_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_empty_objecttype_removed_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_has_embedded_resource_inside_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_multiple_contexts_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_removed_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_subresource_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_subresource_same_properties_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_id_resource_reference_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_required_and_optional_resource_references_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_array_properties_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_complex_properties_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_json_fields_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_map_properties_azure.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_renders_spec_azure.golden
hack/generator/pkg/codegen/testdata/EmbeddedTypes/Embedded_type_simple_resource.golden
hack/generator/pkg/codegen/testdata/EnumNames/Multi_valued_enum_name.golden
hack/generator/pkg/codegen/testdata/EnumNames/Single_valued_enum_name.golden

Validator for ResourceReference which ensures that all references provided to us are formatted property.
Valid ResourceReference formats are: only ARMID, or Group, Kind, Namespace, Name.
An upcoming PR will perform namespace defaulting so that the namespace parameter can be left empty.

Add ResourceReference Validator

---

config/crd/kustomizeconfig.yaml

The path seems to have changed with the upgrade of the CRD to version v1.
refs #1531
Not sure if it fixes all related issues, but worked when generating the CRD yamls locally.

fix path so kustomize adds prefixes to the webhook service

---

hack/generator/pkg/astmodel/object_type.go
hack/generator/pkg/astmodel/resource_type.go
hack/generator/pkg/codegen/pipeline_json_serialization_test_cases.go
hack/generator/pkg/testcases/object_type_serialization_test_case.go

Moves our existing JSON serialization test case into a new package that will contain only test cases.
Test cases aren't really a part of the AST model and they have significant internal complexity; pulling them out into a separate package makes them more discoverable and keeps the complexity contained.
This PR also fixes a problem where test cases were not being emitted for Resource types.

Create new package testcases and move existing test case into place

---

hack/generator/pkg/astmodel/property_container.go
hack/generator/pkg/astmodel/resource_type.go
hack/generator/pkg/astmodel/resource_type_test.go

Currently resources only have `Spec` and `Status` properties, but we have a need (for storage versions) to have additional properties as well. This PR extends support to allow additional properties on resources, but treating `Spec` and `Status` as special cases.
First consumer will be for Storage versions where the original group-version-kind of the API type needs to be preserved.

Allow resources to have additional properties

---

hack/generator/pkg/astmodel/object_type.go
hack/generator/pkg/astmodel/resource_type.go
hack/generator/pkg/astmodel/test_case.go
hack/generator/pkg/astmodel/test_file_definition.go
hack/generator/pkg/codegen/pipeline_json_serialization_test_cases.go
hack/generator/pkg/testcases/object_type_serialization_test_case.go

To reduce clutter in the `astmodel` package, creates a new package `testcases`. Currently we have only a single test case, but that number is going to grow as a part of the implementation for storage variants, so it makes sense to break it out now.
Also fixes a bug where test cases were not being generated for Resources because the interface wasn't being implemented.

Create testcases package

---

hack/generated/controllers/generic_controller.go
hack/generated/pkg/genruntime/errors.go
hack/generated/pkg/genruntime/errors_test.go
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generated/pkg/testcommon/counting_roundtripper.go
hack/generated/pkg/util/kubeclient/kube_client.go
hack/generated/pkg/util/patch/patch_test.go

Removes all uses of the format specifiers `%v` and `%+v` as those dump entire objects into the log, which very likely will include secrets (e.g. credentials etc); we don't want those exposed in the logs.
Closes #1470

Remove dangerous format specifiers

---

Makefile
azure-pipelines.yml
config/default/manager_image_patch.yaml
controllers/suite_test.go
controllers/targetnamespace_test.go
main.go
pkg/resourcemanager/config/config.go
pkg/resourcemanager/config/env.go
pkg/resourcemanager/config/env_test.go

Add a new configuration value AZURE_TARGET_NAMESPACES which restricts the operator to only reconciling Azure resources within the listed namespaces (comma-separated).
This enables running multiple operators that each watch their own set of namespaces and work with different credentials.
Testing is a pain for settings like this - I've used the same approach as the secret-naming version testing for now, but we need to come up with a better way to do this. The next part of the multitenancy work is a setting to put the operator into webhook-only mode, so that will have the same problem. 

Add AZURE_TARGET_NAMESPACES to restrict the namespaces the operator watches

---

hack/generated/controllers/crd_disk_test.go
hack/generated/controllers/recordings/Test_Disk_CRUD.yaml
hack/generator/azure-arm.yaml
hack/generator/pkg/codegen/pipeline_add_cross_resource_references.go

This enables the Disk resource in code generation and adds a test that exercises creating, updating and deleting it.
The test framework is really nice now!

Add Disk (from microsoft.compute/20200930) to generated resources

---

.dockerignore
azure-pipelines.yml

Since the clusters have been upgraded to 1.19.11 the cluster-release task has started failing since helm is complaining about deprecated v1beta1 ClusterRoleBindings in aad-pod-identity. Turn off the check so the pipeline stops failing while we upgrade the aad-pod-identity dependency.
Example of failing job: https://dev.azure.com/azure/azure-service-operator/_build/results?buildId=25000&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bfdc8dd2-1718-51d0-a919-951535614239

Temporarily remove stderr check in pipeline clean up task

---

.github/workflows/build-devcontainer-image.yml

Build a Devcontainer image at least once a week and push it to GitHub Container Registry. We can use this as a base/cache-from image to speed up builds and mitigate [flaky upstream dependencies](https://arstechnica.com/gadgets/2021/06/microsofts-linux-repositories-were-down-for-18-hours/).

Build & push Devcontainer image to GitHub Container Registry

---

.github/workflows/build-devcontainer-image.yml
.github/workflows/pr-validation.yml

Use the shared devcontainer image in the PR validation build.

Use shared devcontainer image in PR builds

---

Taskfile.yml
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generated/pkg/testcommon/error_translating_roundtripper.go
hack/generated/pkg/testcommon/kube_test_context_envtest.go
hack/generated/pkg/testcommon/test_context.go
hack/generated/pkg/testcommon/test_logger.go
scripts/check-changes.sh

Closes #1431
- Only see logs for tests that fail.
- When tests do fail, you get much more verbose logs including HTTP responses, which should help to diagnose issues
- Test logs are no longer interleaved between tests (each tests logs are cleanly separated)

Improve recorded test logging

---

hack/generator/azure-arm.yaml
hack/generator/azure-crossplane.yaml
hack/generator/pkg/codegen/pipeline_apply_export_filters.go
hack/generator/pkg/codegen/pipeline_apply_property_rewrites.go
hack/generator/pkg/codegen/pipeline_load_schema.go
hack/generator/pkg/config/configuration.go
hack/generator/pkg/config/configuration_test.go
hack/generator/pkg/config/type_matcher.go
hack/generator/pkg/config/type_transformer.go

- Ensure that all config transformers and filters
raise an error by default if they don't match anything.
- Removed config options that had no matches.

Config transformers and filters now error if no matches

---

hack/generator/pkg/astmodel/types.go
hack/generator/pkg/astmodel/types_test.go

Pulls a useful method out of a WIP branch so that @matthchr can use it

Extract OverlayWith() method

---

hack/generator/pkg/codegen/code_generator.go
hack/generator/pkg/codegen/golden_files_test.go
hack/generator/pkg/codegen/pipeline_collapse_cross_group_refs.go
hack/generator/pkg/codegen/testdata/ARMCodeGeneratorPipeline.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_oneof_resource_conversion_on_arm_type_only_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_dependent_resource_and_ownership_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_empty_objecttype_removed_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_has_embedded_resource_inside_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_multiple_contexts_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_resource_removed_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_subresource_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_embedded_subresource_same_properties_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_id_resource_reference_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_required_and_optional_resource_references_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_array_properties_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_complex_properties_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_json_fields_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_map_properties_crossplane.golden
hack/generator/pkg/codegen/testdata/ArmResource/Arm_test_simple_resource_renders_spec_crossplane.golden

Fixes #1578
- In the case that group A references group B, we need to pull group B's types into group A.
- Also fixes a bug in the Crossplane golden files tests which combined with this new pipeline stage could cause all types to get pruned.

Add new pipeline stage that merges groups

---

hack/generator/pkg/conversions/property_assignment_function.go

We had the parameter name for the PropertyAssignmentFunction defined in two places, which would allow them to inadvertently move out of sync later on. This PR centralises the naming of the parameter into one place, caching the name on the function to allow easy reuse where required.
Closes #1564

Fix duplication of parameter name assignment

---

hack/generator/pkg/codegen/pipeline/flatten_properties.go
hack/generator/pkg/codegen/pipeline/flatten_properties_test.go

The new VMSS resources do this (a collision on `Type` property). Technically we can handle this case properly but it will require more work.
We can handle the VMSS case because the user can't normally overwrite the top-level `Type` property, so any `Type` property in the CRD must point to the flattened `Type`.

Don't fail on flattening collisions

---

hack/generated/controllers/crd_vmss_test.go
hack/generated/controllers/recordings/Test_VMSS_CRUD.yaml
hack/generated/go.mod
hack/generated/go.sum
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generated/pkg/testcommon/error_translating_roundtripper.go
hack/generated/pkg/testcommon/test_context.go
hack/generator/azure-arm.yaml

- Add support for a code generated version of VMSS
- Add tests for VMSS.

Add support for V2 VMSS

---

docs/issue-triage.md

Makes our goal for issue triage public, and documents the GitHub search that we use.

Document our issue triage process

---

controllers/async_controller.go
controllers/targetnamespace_test.go

We now add an annotation `azure.microsoft.com/operator-namespace=<namespace>` to any resource when we reconcile it. This will help users to find the operator configured to reconcile a resource, and log a warning if it looks like multiple operators are watching the same namespace.

Annotate a resource with the namespace of the operator handling it

---

hack/generated/controllers/crd_vmss_test.go
hack/generated/controllers/deployment_reconciler_negative_test.go
hack/generated/controllers/edge_case_test.go
hack/generated/controllers/recordings/Test_CreateResourceGroupThatAlreadyExists_ReconcilesSuccessfully.yaml
hack/generated/controllers/recordings/Test_CreateStorageAccountThatAlreadyExists_ReconcilesSuccessfully.yaml
hack/generated/controllers/recordings/Test_DeploymentAccepted_LongRunningOperationFails.yaml
hack/generated/controllers/recordings/Test_DeploymentAccepted_LongRunningOperationFails_SucceedsAfterUpdate.yaml
hack/generated/controllers/recordings/Test_DeploymentRejected.yaml
hack/generated/controllers/recordings/Test_DeploymentRejected_SucceedsAfterUpdate.yaml
hack/generated/controllers/recordings/Test_StorageAccount_CreatedBeforeResourceGroup.yaml
hack/generated/controllers/recordings/Test_StorageAccount_CreatedInParallelWithResourceGroup.yaml
hack/generated/controllers/recordings/Test_Subnet_CreatedBeforeVNET.yaml
hack/generated/controllers/recordings/Test_Subnet_CreatedInParallelWithVNET.yaml
hack/generated/pkg/armclient/types.go
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generated/pkg/reconcilers/deployment_error_classifier.go
hack/generated/pkg/reconcilers/deployment_error_classifier_test.go
hack/generated/pkg/reflecthelpers/reflect_helpers.go
hack/generated/pkg/testcommon/be_provisioned_matcher.go
hack/generated/pkg/testcommon/ensure.go
hack/generated/pkg/testcommon/error_translating_roundtripper.go
hack/generated/pkg/testcommon/kube_matcher.go
hack/generated/pkg/testcommon/kube_per_test_context.go

- Fixes a number of issues with the Azure deployment reconciler.
- Adds various edge-case tests to ensure that scenarios such as creating 
a resource before it's owner is created, or updating a failed resource, work
correctly.

Improve Azure deployment reconciler and add tests

---

hack/generated/pkg/genruntime/property_bag_test.go

Our CI builds have been failing because one of our lint tools has identified a problem in one of the tests for `PropertyBag`. This PR fixes the problem.

Ensure test uses float value

---

hack/generator/pkg/astbuilder/builder.go
hack/generator/pkg/astbuilder/calls.go

Pulls in some improvements to the `astbuilder` package.
Harvested from PR #1533

Minor improvements to astbuilder

---

hack/generated/controllers/recordings/Test_ServiceBus_Basic_CRUD.yaml
hack/generated/controllers/recordings/Test_ServiceBus_Standard_CRUD.yaml
hack/generated/controllers/recordings/Test_StorageAccount_CRUD.yaml
hack/generated/pkg/testcommon/kube_per_test_context.go
hack/generated/pkg/testcommon/resource_namer.go
hack/generated/pkg/testcommon/test_context.go

Subtests stared with `ParallelSubtests` were sharing the same `Namer` as parent tests, which is a) wrong and b) could lead to race conditions.
Each subtest now gets its own `Namer`, based on its test name.
Regenerated recordings for affected tests. I also removed 2 more headers from recordings to reduce recording diff size.

Fix subtest name generation

---

controllers/mysql_combined_test.go
pkg/resourcemanager/azuresql/azuresqlaction/azuresqlaction.go
pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go
pkg/resourcemanager/azuresql/azuresqluser/azuresqluser_reconcile.go
pkg/resourcemanager/mysql/mysqlaaduser/reconcile.go
pkg/resourcemanager/mysql/mysqluser/mysqluser_reconcile.go
pkg/resourcemanager/psql/psqluser/psqluser_reconcile.go

Closes #1576 
Before this change, the different resources would leak database connections whenever they were reconciled. Add `defer db.Close()` to all of the places that open database connections so that they are closed at the end of the method.
I started off making a cache to keep the `*sql.DB`s in so that they could be reused between reconciliations, but then the difficulty was ensuring we didn't keep the DBs in the cache indefinitely. One option was to hook up the database controller so it could remove the cached entry when the database was deleted, but that's quite fiddly architecturally. I also wrote [some code](https://github.com/Azure/azure-service-operator/compare/master...babbageclunk:bug/postgres-connect …

Ensure DB connections are closed when we've finished with them

---

hack/generated/controllers/crd_vmss_test.go
hack/generated/pkg/testcommon/kube_per_test_context.go
hack/generator/pkg/codegen/pipeline/add_cross_resource_references.go

Closes #1569
This reduces the probability of us accidentally missing references,
which it turns out we had already done because as soon as this
was turned on, a number of errors were returned due to references
we missed.

Return error if reference-like property is not labelled

---

hack/generator/pkg/conversions/direction.go
hack/generator/pkg/conversions/property_assignment_function.go

Code that needed to make a decision based on the direction of conversion always needed to handle "other" values with a panic; converting the type into an interface allows us to ensure that only valid implementations are provided, simplifying consumption.
This type will be used more frequently in upcoming PRs to implement type conversion.
Harvested from PR #1533
**Prerequisites**
Let us take a moment and lament how `SelectString()` and `SelectType` would be a single method if Go had generics right now.

Convert Direction from enum into a discriminated union

---

api/v1alpha2/mysqlserver_types.go
controllers/mysql_combined_test.go
controllers/mysqlserver_controller_test.go
controllers/suite_test.go
docs/services/mysql/mysql.md
main.go
pkg/resourcemanager/mysql/mysqlaaduser/reconcile.go
pkg/resourcemanager/mysql/mysqluser/mysqluser.go
pkg/resourcemanager/mysql/mysqluser/mysqluser_reconcile.go
pkg/resourcemanager/mysql/server/client.go
pkg/resourcemanager/mysql/server/reconcile.go

Closes #1590
- The specified secret must be a Kubernetes secret.
- The specified secret must contain a "username" and "password" field.
- The specified secret must be in the same namespace as the MySQLServer.
- If the specified secret doesn't exist, reconciliation will be blocked
until the secret does exist. Once the secret is created, reconciliation
will continue as normal.
- The operator does not make the user specified secret owned by
the MySQLServer.
- The operator still creates a secret containing connection string details
and username/password for the server. This secret is named as it was
before. This means that the customer specified username and password
are consumed to create this secret, but other resources such as MySQLUser
still consume the generated secret file.
**If …

Support user specified MySQLServer secrets

---

.golangci.yml
hack/generated/pkg/duration/duration_test.go
hack/generator/pkg/astbuilder/literals_test.go
hack/generator/pkg/astmodel/array_type_test.go
hack/generator/pkg/astmodel/enum_type_test.go
hack/generator/pkg/astmodel/external_package_reference_test.go
hack/generator/pkg/astmodel/flagged_type_test.go
hack/generator/pkg/astmodel/identifier_factory_test.go
hack/generator/pkg/astmodel/local_package_reference_test.go
hack/generator/pkg/astmodel/map_type_test.go
hack/generator/pkg/astmodel/meta_type_test.go
hack/generator/pkg/astmodel/object_type_test.go
hack/generator/pkg/astmodel/package_import_set_test.go
hack/generator/pkg/astmodel/package_import_test.go
hack/generator/pkg/astmodel/package_reference_test.go
hack/generator/pkg/astmodel/primitive_type_test.go
hack/generator/pkg/astmodel/property_definition_test.go
hack/generator/pkg/astmodel/storage_package_reference_test.go
hack/generator/pkg/astmodel/type_flag_test.go
hack/generator/pkg/astmodel/type_name_test.go
hack/generator/pkg/astmodel/type_test.go
hack/generator/pkg/astmodel/type_visitor_test.go
hack/generator/pkg/codegen/pipeline/status_from_swagger_test.go
hack/generator/pkg/config/create_globbing_regex_test.go
hack/generator/pkg/functions/property_assignment_function_test.go

If subtests are going to run in parallel the parent test needs to be marked as well; this linter catches it.

Add tparallel linter and fix

---

hack/generator/pkg/astmodel/armconversion/arm_conversion_function.go
hack/generator/pkg/astmodel/function.go
hack/generator/pkg/astmodel/one_of_json_marshal_function.go
hack/generator/pkg/astmodel/package_definition.go
hack/generator/pkg/astmodel/reference_graph.go
hack/generator/pkg/astmodel/reference_graph_test.go
hack/generator/pkg/codegen/code_generator.go
hack/generator/pkg/codegen/pipeline/create_arm_types.go
hack/generator/pkg/codegen/pipeline/strip_unused_types.go
hack/generator/pkg/codegen/pipeline/strip_unused_types_test.go
hack/generator/pkg/codegen/testdata/ARMCodeGeneratorPipeline.golden
hack/generator/pkg/codegen/testdata/EmbeddedTypes/Embedded_type_simple_resource.golden
hack/generator/pkg/codegen/testdata/EnumNames/Single_valued_enum_name.golden
hack/generator/pkg/codegen/testdata/TestCodeGeneratorPipeline.golden

* Flattening can cause types which were previously being used to no longer be used. 
Run a prune after flattening to ensure that we remove these unneeded types.
* Fix bug in Function References() where many functions were incorrectly referring to 
their receiverType, resulting in types remaining included when they should have been
removed.
* Fix small bug in embedded type handling exposed by this change so that 
the golden tests pass.

Prune unused types after flattening

---

hack/generator/azure-arm.yaml
hack/generator/pkg/astmodel/armconversion/convert_to_arm_function_builder.go
hack/generator/pkg/codegen/pipeline/add_cross_resource_references.go
hack/generator/pkg/config/configuration.go
hack/generator/pkg/config/type_transformer.go

* Improve errors from property type transformers further.
* Add missed reference properties.
* Exclude some readonly properties

Clean up autogenerated properties

---

hack/generator/pkg/astmodel/errored_type.go
hack/generator/pkg/astmodel/type_visitor.go
hack/generator/pkg/codegen/code_generator.go
hack/generator/pkg/codegen/pipeline/apply_export_filters.go
hack/generator/pkg/codegen/pipeline/status_from_swagger.go
hack/generator/pkg/codegen/pipeline/verify_no_errored_types.go
hack/generator/pkg/codegen/testdata/TestNewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewCrossplaneCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewTestCodeGeneratorCreatesRightPipeline.golden

* Adds a new stage requiring that all generated types do not contain an `ErroredType` with errors (warnings are ok). 
* Missing `Status` types now produce an `ErroredType` with errors (before it was warnings). This is required for future work where resource Status's will begin to have more information in addition to just the response from Azure, such as `Conditions` and possibly other things going forward.

Fail pipeline if any type contains ErroredType with errors

---

Taskfile.yml
hack/generated/.gitignore
hack/generated/config/certmanager/certificate.yaml
hack/generated/config/certmanager/kustomization.yaml
hack/generated/config/certmanager/kustomizeconfig.yaml
hack/generated/config/default/kustomization.yaml
hack/generated/config/default/manager_webhook_patch.yaml
hack/generated/config/default/webhookcainjection_patch.yaml
hack/generated/config/webhook/kustomization.yaml
hack/generated/config/webhook/kustomizeconfig.yaml
hack/generated/config/webhook/service.yaml
hack/generated/main.go

Fixes webhook configuration in ASOv2.
When we add conversion webhooks we will need to revisit this as they aren't currently hooked up.

Fix webhooks in ASOv2

---

hack/generated/_apis/microsoft.resources/v1alpha1api20200601/resourcegroup_types.go
hack/generated/config/manager/manager.yaml
hack/generated/controllers/generic_controller.go

controller-gen is only run inside the _apis directory, and we had annotations outside next to generic_controller.go which were not
being honored. We needed those permissions (and also leases which we had missed).

Fix missing controller RBAC permissions

---

.devbots/needs-triage.yml

Using [DevBots - Needs Triage](https://devbots.xyz/documentation/needs-triage/).

Add needs-triage label automatically

---

hack/generator/pkg/astbuilder/assignments.go
hack/generator/pkg/astbuilder/builder.go
hack/generator/pkg/astbuilder/conditions.go
hack/generator/pkg/astbuilder/lists.go
hack/generator/pkg/astbuilder/maps.go
hack/generator/pkg/astmodel/armconversion/convert_from_arm_function_builder.go
hack/generator/pkg/astmodel/conversion_function_builder.go
hack/generator/pkg/astmodel/kubernetes_admissions_defaults.go
hack/generator/pkg/astmodel/kubernetes_admissions_validator.go
hack/generator/pkg/astmodel/kubernetes_resource_interface.go
hack/generator/pkg/codegen/pipeline/resource_registration_file.go
hack/generator/pkg/conversions/property_conversions.go
hack/generator/pkg/conversions/writable_conversion_endpoint.go
hack/generator/pkg/functions/resource_conversion_function.go
hack/generator/pkg/testcases/object_type_serialization_test_case.go

Our `SimpleAssignment()` method has always been brittle because it's so easy to misuse by passing the wrong token value. This also makes it more complex to consume - I've wanted to simplify things for a while.
* `SimpleAssignment()` has been modified so it always does assignment 
* New method `SimpleDeclaration()` uses `:=` to always declare a variable. The first parameter is a string, simplifying all the calling sites.
* New method `SetVariable()` handles the very few remaining cases where the choice between declaration and assignment was dynamic.
The helper `EnsureStatementBlock()` has been subsumed into `StatementBlock()` to simplify usage.
Extends usage of helper functions to simplify code.
Moves some local variable name reservations later, …

Code gardening for code generation

---

docs/issue-triage.md

We're introducing the tag `needs-triage` and a bot to automatically apply it to new issues; this PR updates our docs on what we're looking at when we triage.

Update our triage docs for new tag

---

hack/generated/controllers/generic_controller.go
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generated/pkg/testcommon/kube_test_context_envtest.go

Multiple updates in a single loop means that there are multiple changes with new resourceVersions floating around. This then leads to races where you might end up reconciling on the resource from after update1 when you really want the change from after update2.
Since the two-updates was just an optimization, removed it.

Don't CommitUpdate twice in a single reconcile loop

---

.devbots/needs-triage.yml
.github/workflows/add-needs-triage-label.yml

Bot doesn't seem to be working so let's do this instead. Seems simpler overall as well!

Use Github Action to add needs-triage label

---

Taskfile.yml
hack/generated/pkg/genruntime/conditions/conditions.go
hack/generated/pkg/genruntime/resource_reference.go

Some genruntime types are used by the generated code, while others are used only by the handcrafted controller. Types used
by the generated code need DeepCopy() functionality.

Generate DeepCopy() methods for genruntime types

---

hack/generated/controllers/crd_disk_test.go
hack/generated/controllers/crd_storageaccount_test.go
hack/generator/pkg/astmodel/types.go
hack/generator/pkg/codegen/code_generator.go
hack/generator/pkg/codegen/pipeline/make_status_properties_optional.go
hack/generator/pkg/codegen/testdata/TestNewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewCrossplaneCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewTestCodeGeneratorCreatesRightPipeline.golden

There are times when `Status` doesn't exist, such as when an object is first created. There's a bit of an unwritten rule that:
1. `Status` is not a pointer on the resource.
2. All top level status properties have `omitempty` set.
This way when there isn't a status, there's not a bunch of extra `""`'s returned.
This is especially important for some multi-write cases between spec and status, as `""`'s returned can overwrite in-memory data before it has a chance to be sent via a `client.Status().Update()` call

Force top level status properties to be optional

---

hack/generator/pkg/codegen/pipeline/json_serialization_test_cases.go
hack/generator/pkg/testcases/json_serialization_test_case.go
hack/generator/pkg/testcases/object_type_serialization_test_case.go

We were only generating the JSON serialization test case for objects, but we need it for resources too - particularly since upcoming tests are going to be reliant on the generator infrastructure this test case generates.

Generalize our JSON serialization test case to work with resources too

---

.github/workflows/create-release.yml
Taskfile.yml

`run-kustomize` would fail if run before `build-docker-image` due to output directory not existing.

Fix run-kustomize task and reorder steps

---

azure-pipelines.yml
controllers/azuresql_combined_test.go
controllers/helpers.go
pkg/helpers/retry.go

It seems like there's a problem in the job that's causing it to be killed by the timeout, but the way the job is killed prevents us from seeing the output which would let us fix the underlying problem in whichever test is failing.
[Example of the job timeout](https://dev.azure.com/azure/azure-service-operator/_build/results?buildId=27948&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=cb33ee24-f492-54d2-727a-ae0a7bb84b2c)

Remove envtest job timeout for now

---

.devcontainer/Dockerfile
.devcontainer/install-dependencies.sh

Two fixes:
- Kubebuilder broke their vanity URIs for downloads, switch to Github URIs
- `packages.microsoft.com` is missing Moby packages for Debian Bullseye, switch to use Docker CE (see https://github.com/microsoft/vscode-dev-containers/issues/1008)

Fixes for CI breakage

---

hack/generator/azure-arm.yaml
hack/generator/pkg/astmodel/enum_type.go
hack/generator/pkg/astmodel/types.go
hack/generator/pkg/astmodel/types_test.go
hack/generator/pkg/codegen/code_generator.go
hack/generator/pkg/codegen/pipeline/remove_status_property_validations.go
hack/generator/pkg/codegen/testdata/TestNewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewCrossplaneCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewTestCodeGeneratorCreatesRightPipeline.golden

Removes validation from status types.
This has the unfortunate impact that we won't be able to share types between spec and status... which is pretty unfortunate. See the long explanation in remove_status_property_validations.go for the reason behind this change.
Note: Testing this is difficult because of our testing gap on status types, but it _is_ covered by the upcoming AKS E2E test (not in PR yet) as without this that test fails.

Remove all status validations

---

hack/generated/controllers/generic_controller.go
hack/generated/controllers/suite_test.go
hack/generated/go.mod
hack/generated/main.go
hack/generated/pkg/testcommon/kube_per_test_context.go
hack/generated/pkg/testcommon/kube_test_context_envtest.go

Improve recording test default timeouts
* In the abscence of a timeout specified on the cmdline, use recording mode to determine what the timeout should be. When recording, timeout is longer (15m), and when replaying the timeout is shorter (2m).
Improve controller exponential backoff and timing
* Reduced the maximum wait time (it was >15m). Polling speed is now variable based on test mode. In replay mode, polling is fast. In recording mode, polling is slower. 

Improve recording default timeouts and controller backoff timing

---

.devcontainer/devcontainer.json

The existing method is “deprecated”.

Stop VS Code complaining about devcontainer.json

---

hack/generated/pkg/reconcilers/azure_deployment_reconciler.go
hack/generated/pkg/testcommon/kube_per_test_context.go

Obivously this isn't the ideal way to do things, but I can't think of another "easy" fix. The real solution is to stop modifying status and spec at the same time, but I believe in order to do that we need to move some fields out of Spec and into Status, which will take some effort. This should unblock us for now.

Reduce test polling speed some to reduce flakiness

---

hack/generated/config/manager/manager.yaml
hack/generated/controllers/generic_controller.go
hack/generated/pkg/logging/levels.go
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go

We weren't consistent with what we were logging at what level. Some log level 0 messages were getting emitted every time through the reconcile loop, others were much less verbose. When writing a log statement, it was hard to determine where in the 0 to 10 spectrum to put your log without crawling all of the other log statements around you to rebuild your mental model of what levels we were using.
There is some relatively standard guidance [from Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md), but the problem is remembering it, especially given that they have 6 levels discussed there many of which are just described as "More details" which of course begs the question: "When do I …

Controller logging improvements

---

Makefile
config/operator-bundle/bases/azure-service-operator.clusterserviceversion.yaml
scripts/update-webhook-references-in-operator-bundle.sh

The previously released operator bundle wasn't setting up conversion webhooks properly, so any custom resource with multiple versions would encounter problems reconciling. This updates the bundle generation to use the latest release of operator-sdk, and corrects the webhook config on the multi-version CRDs so that they refer to the webhook service OLM creates, since that's the one that it sets up certificates for.
The azureoperator-webhook-service has been removed. 
Since OLM manages the certificate setup for the webhooks, I've also removed the cert-manager annotations from the CRDs, and removed the cert-manager setup from the installation instructions.
Closes #1718 

Fix conversion webhooks in operator bundle

---

hack/crossplane/apis/microsoft.cache/v1alpha1api20200601/redis_types_gen.go
hack/crossplane/apis/microsoft.sql/v1alpha1api20201101preview/server_types_gen.go
hack/crossplane/apis/microsoft.sql/v1alpha1api20201101preview/servers_database_types_gen.go
hack/generated/apis/microsoft.batch/v1alpha1api20210101/batch_account_types_gen.go
hack/generated/apis/microsoft.batch/v1alpha1api20210101/batch_accounts__spec_arm_types_gen.go
hack/generated/apis/microsoft.compute/v1alpha1api20200930/disks__spec_arm_types_gen.go
hack/generated/apis/microsoft.compute/v1alpha1api20201201/virtual_machine_scale_sets__spec_arm_types_gen.go
hack/generated/apis/microsoft.documentdb/v1alpha1api20210515/database_account_types_gen.go
hack/generated/apis/microsoft.documentdb/v1alpha1api20210515/database_accounts__spec_arm_types_gen.go
hack/generated/apis/microsoft.managedidentity/v1alpha1api20181130/user_assigned_identities__spec_arm_types_gen.go
hack/generated/apis/microsoft.managedidentity/v1alpha1api20181130/user_assigned_identity_types_gen.go
hack/generated/apis/microsoft.network/v1alpha1api20201101/subnet__status__virtual_networks_subnet__sub_resource_embedded_arm_types_gen.go
hack/generated/apis/microsoft.network/v1alpha1api20201101/virtual_networks_subnet_types_gen.go
hack/generated/apis/microsoft.servicebus/v1alpha1api20210101preview/namespace_types_gen.go
hack/generated/apis/microsoft.servicebus/v1alpha1api20210101preview/namespaces__spec_arm_types_gen.go
hack/generated/apis/microsoft.storage/v1alpha1api20210401/storage_account_types_gen.go
hack/generated/apis/microsoft.storage/v1alpha1api20210401/storage_accounts__spec_arm_types_gen.go
hack/generated/apis/microsoft.storage/v1alpha1api20210401/storage_accounts_blob_services__spec_arm_types_gen.go
hack/generated/apis/microsoft.storage/v1alpha1api20210401/storage_accounts_blob_services_containers__spec_arm_types_gen.go
hack/generator/pkg/astmodel/object_type.go
hack/generator/pkg/codegen/pipeline/convert_allof_and_oneof_to_objects.go

When merging properties as a part of a one-of or all-of, the comment included on a merged property was non-deterministic, resulting in different results on different runs.
This PR applies a super simple heuristic, selecting the longer (more detailed) comment each time. This works pretty well, but isn't perfect.
Closes #1757 

Fix non-deterministic property comments 

---

hack/generator/pkg/astmodel/type_name.go
hack/generator/pkg/codegen/pipeline/testdata/TestGolden_CreateStorageTypes/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestGolden_CreateStorageTypes/microsoft.person-v20211231storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestGolden_InjectConvertibleInterface/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestGolden_InjectConvertibleInterface/microsoft.person-v20211231storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectConvertibleSpecInterface/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectConvertibleSpecInterface/microsoft.person-v20211231storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectConvertibleStatusInterface/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectConvertibleStatusInterface/microsoft.person-v20211231storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectJsonSerializationTests/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectJsonSerializationTests/microsoft.person-v20211231storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectPropertyAssignmentFunctions/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectPropertyAssignmentFunctions/microsoft.person-v20211231storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectPropertyAssignmentTests/microsoft.person-v20200101storage.golden
hack/generator/pkg/codegen/pipeline/testdata/TestInjectPropertyAssignmentTests/microsoft.person-v20211231storage.golden

Code generation by `TypeName.AsFunc()` was generating the wrong code if the _current_ package was also present in the list of _imported_ packages - it was triggering an import of the package and incorrectly using a qualified name for the type.
I've inverted the logic - now, if the `TypeName` is within the current package, it emits an unqualified identifier, otherwise it creates a selector.
This impacts on a bunch of golden files - where I really should have noticed earlier the incorrect imports - so I've put this in an isolated PR despite it being a small fix.

Fix TypeName to make code generation more resilient

---

hack/crossplane/apis/microsoft.sql/v1alpha1api20201101preview/server_types_gen.go
hack/generator/azure-arm.yaml
hack/generator/pkg/jsonast/jsonast.go

There was a bug in the JSON schema generator previously where multiple OpenAPI specifications under the same provider (Microsoft.Authorization for example) would overwrite one another. The ARM JSON schema generator team solved this problem by manufacturing multiple documents named based on the OpenAPI specification file/folder name. We must combine all of
these fabricated documents into a single picture of a single API (as that's what it's actually attempting to represent).
The code to do this is a bit fragile/hacky, although the code that existed prior to this was also a bit fragile...

Update JSON schema submodule

---

hack/generated/controllers/generic_controller.go
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go

* Instead of logging ARMID just once, include it on all log messages.
* Don't use string format specifiers (%s) as they aren't used by klog.

Improve generic controller logging

---

hack/generator/cmd/gen_kustomize.go

Trying to run `task ci` locally, I'm getting errors where `generator gen-kustomize` is erroring with an exit code of `1` and no logging. This PR plugs a few gaps in the logging, hoping to make it easier to diagnose future build faults.

Improve error reporting for gen-kustomize command

---

Makefile
scripts/inject-container-reference.sh
scripts/update-webhook-references-in-operator-bundle.sh

When the operator bundle is installed OLM will set up a volume containing the webhook server certificate and mount it into the manager container, so the existing ones (to get the cert-manager certificate we use in non-operator-bundle deployments) are unnecessary. The spurious volume was referring to a secret that cert-manager is no longer creating and this was preventing the pod from starting in OpenShift 4.6 (k8s 1.19). So this PR removes them.
It also removes the `conversion:` fields from the CRDs in the bundle - the `webhook.clientConfig.namespace` value they specified was wrong for OpenShift. That wasn't causing a problem because it's hooked up by OLM when the operator is installed, but it's misleading.

operator bundle: Remove the cert volume and mount from the pod

---

hack/generated/pkg/genruntime/resolver_test.go
hack/generated/pkg/genruntime/resource_hierarchy.go
hack/generated/pkg/genruntime/resource_hierarchy_test.go
hack/generated/pkg/genruntime/sample_resources_test.go
hack/generator/azure-arm.yaml
hack/generator/pkg/codegen/code_generator.go
hack/generator/pkg/codegen/pipeline/remove_resource_scope.go
hack/generator/pkg/codegen/testdata/TestNewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewCrossplaneCodeGeneratorFromConfigCreatesRightPipeline.golden
hack/generator/pkg/codegen/testdata/TestNewTestCodeGeneratorCreatesRightPipeline.golden

- Add Scope() to ResourceHierarchy for Extension resources
- Remove scope in pipeline stage rather than config
- This allows us to skip removing that property on extension resources. It also resolves a small possible bug where we would
have blindly removed a more deeply scoped "Scope" property. Now we're limited to just top level properties on the spec.

Add ability to generate scope from resource kind and name

---

hack/generated/pkg/genruntime/conditions/conditions.go
hack/generated/pkg/genruntime/conditions/conditions_test.go
hack/generated/pkg/genruntime/conditions/positive_condition_builder.go
hack/generated/pkg/genruntime/conditions/positive_condition_builder_test.go
hack/generated/pkg/genruntime/conditions/ready_condition_builder.go
hack/generated/pkg/reconcilers/azure_deployment_reconciler.go

This gives us a way to pick winners when we're updating the same condition multiple times for a single resource "shape". It follows the KEP on conditions, I had originally not included it because I thought we didn't need it but it turns out we probably do.
This solves the problem of a Warning (of the same generation) immediately getting overwritten by the subsequent reconcile, while maintaining that overwrite in the case the resource had a warning _and was updated_ (since now the generation will be larger).

Add ObservedGeneration to our Conditions

---

Taskfile.yml
docs/hugo/content/docs/authentication.md
docs/hugo/content/docs/contributing/index.md
scripts/deploy_testing_secret.sh
v2/README.md
v2/config/manager/manager.yaml
v2/config/manager/manager_image_patch.yaml

Closes #1869 
Closes #1854
Adds Managed Identity support and documents how to use it. Testing is still an outstanding issue which we need to solve.
See #1941. I will be following up with a separate PR for this.

Managed identity support

---

v2/README.md

The VM CRD is too big to be applied with `kubectl apply` because it can't fit into the `last-applied-configuration` annotation. Running with `create` instead works though.

Update v2 README to use `kubectl create`

---

hack/crossplane/apis/resources.md
v2/api/resources.md
v2/tools/generator/internal/astmodel/meta_type.go
v2/tools/generator/internal/codegen/pipeline/implement_convertible_interface.go
v2/tools/generator/internal/codegen/pipeline/mark_latest_storage_variant_as_hub_version.go
v2/tools/generator/internal/codegen/pipeline/recursivetypefixer/simple_recursive_type_fixer.go
v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go
v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_ReportResourceVersions.golden
v2/tools/generator/internal/testcases/resource_conversion_test_case_test.go

The supported resources list was showing only our internal version reference, not the matching ARM resource version, which may have been confusing for those new to ASO. 
I've changed it to show the ARM api version (which can therefore be searched for) as well as the CRD version as a note for those who need it.

Improve the generated versions report to show ARM API versions

---

v2/internal/controllers/suite_test.go

It turns out that this isn’t very useful and it clutters the test output dramatically. I’ve left the code commented-out in case anyone ever needs to debug anything low-level.

Suppress controller-runtime logging in test suite

---

v2/internal/config/vars.go
v2/internal/controllers/crd_authorization_roleassignment_test.go
v2/internal/controllers/recordings/Test_Authorization_RoleAssignment_OnStorageAccount_CRUD.yaml
v2/internal/controllers/recordings/Test_Compute_VM_CRUD.yaml
v2/internal/reconcilers/azure_generic_arm_reconciler.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/testcommon/kube_test_context_envtest_test.go
v2/internal/testcommon/kube_test_context_real.go

The maximum delay of 1 minute was making replayed tests with a lot of retries (for example the Cosmos DB ones) run very slowly. Also increase the minimum backoff for non-replay tests, which should make the test recordings a bit smaller.
Rerecorded the VM test.

Turn off retry backoff for replay tests

---

docs/hugo/content/contributing/create-a-new-release.md
v2/README.md

We can't use client-side apply because the VirtualMachines CRD is too big to fit in the `last-applied-configuration` annotation kubectl uses, but using `kubectl create` is a bit unpleasant (since it won't update existing resources).
Also note to wait for cert-manager to be started before installing ASO - if we don't do this the ASO webhook-service certificate creation fails because it can't talk to the cert-manager webhook, and the ASO pod won't start. (It bit me while I was testing the various options.)

Update docs to use `kubectl apply --server-side=true`

---

v2/internal/controllers/generic_controller.go
v2/internal/reconcilers/azure_generic_arm_reconciler.go
v2/internal/testcommon/direct_client.go
v2/internal/testcommon/kube_test_context_envtest.go

* Use a KubeClient in EnvTest that always hits APIServer to avoid cache latency and inconsistency issues that can cause races and intermittent test failures. See kubernetes-sigs/controller-runtime#1464 and kubernetes-sigs/controller-runtime#343 for details.
* Write Status after Spec. This ensures that tests waiting for a status update cannot possibly see it so fast that they go on   to perform a write that conflicts with the Spec write of the controller.
* Improve log messages to be clearer (aids in test debugging).
* Prior to performing any deletion actions (either monitoring or deletion), verify that the finalizer is still set. If it's not set,
immediately allow the k8s resource to be deleted. Don't take any action on the Azure resource in this instance.
**How does this PR make you …

Improve test reliability

---

v2/tools/generator/internal/astmodel/code_generation_context.go
v2/tools/generator/internal/astmodel/external_package_reference.go
v2/tools/generator/internal/astmodel/external_package_reference_test.go
v2/tools/generator/internal/astmodel/kubernetes_admissions_defaulter.go
v2/tools/generator/internal/astmodel/kubernetes_admissions_validator.go
v2/tools/generator/internal/astmodel/local_package_reference.go
v2/tools/generator/internal/astmodel/local_package_reference_test.go
v2/tools/generator/internal/astmodel/package_reference.go
v2/tools/generator/internal/astmodel/resource_type.go
v2/tools/generator/internal/astmodel/storage_package_reference.go
v2/tools/generator/internal/astmodel/type_definition_test.go
v2/tools/generator/internal/astmodel/type_name.go
v2/tools/generator/internal/astmodel/type_walker.go
v2/tools/generator/internal/codegen/golden_files_test.go
v2/tools/generator/internal/codegen/pipeline/add_arm_conversion_interface.go
v2/tools/generator/internal/codegen/pipeline/check_for_anytype.go
v2/tools/generator/internal/codegen/pipeline/export_generated_code.go
v2/tools/generator/internal/codegen/pipeline/mark_latest_api_version_as_storage_version.go
v2/tools/generator/internal/codegen/storage/conversion_graph.go
v2/tools/generator/internal/codegen/storage/conversion_graph_builder.go
v2/tools/generator/internal/codegen/storage/group_conversion_graph_builder.go
v2/tools/generator/internal/codegen/storage/property_converter.go
v2/tools/generator/internal/config/object_model_configuration.go
v2/tools/generator/internal/config/type_matcher.go
v2/tools/generator/internal/test/asserts.go
v2/tools/generator/internal/test/file_definition.go

We've been handwaving along with the illusion that a `StoragePackageReference` was effectively a `LocalPackageReference` and could be treated as such for all intents and purposes ... this illusion broke down as I was implementing object renaming.
Upon inspection, it became clear that most (if not all) use of `AsLocalPackageReference` was interested in getting the `Group`, `Version` or both values from the reference.
By adding `GroupVersion()` to the interface definition, I was able to replace almost all calls to `AsLocalPackageReference` with cleaner code.
The few remaining references were easily refactored, allowing the removal of both the interface member `AsLocalPackageReference` and the helper method `PackageAsLocalPackage`.
**How does this PR …

Clean up distinction between package reference types

---

v2/internal/controllers/generic_controller.go
v2/internal/reconcilers/azure_generic_arm_reconciler.go

* Renamed "poller-resume-token.azure.com" to "serviceoperator.azure.com/poller-resume-token".
* Renamed "poller-resume-id.azure.com" to "serviceoperator.azure.com/poller-resume-id".
* Renamed "resource-sig.azure.com" to "serviceoperator.azure.com/resource-sig".
* Renamed "azure.microsoft.com/operator-namespace" to "serviceoperator.azure.com/operator-namespace".
This fixes #1970.

BREAKING: Rename annotations to match prefix/name

---

Taskfile.yml
v2/test/managedidentity_test.go
v2/tools/generator/internal/kustomization/conversion_patch_file.go

The `cert-manager.io/inject-ca-from` annotation on a CRD tells the cert-manager webhooks to add the CA bundle to the conversion webhook client config. Without this the conversion webhooks will fail and the only resource that will be able to be created will be resource groups (since they don't have multiple versions). This was missed because our integration test and manual post-release check only tested resource groups 😢. This has now been rectified! 
Envtests were working because they manage the CA bundle themselves when the CRD is being installed.

Add `inject-ca-from` annotation to generated CRD patches

---

scripts/kind-with-registry.sh

Sometimes the live Azure tests can fail because the apiserver
isn't responding to requests yet. This is hard to reproduce locally
due to the power/speed of our dev machines compared to the CI machines.

Wait for kind apiserver to be up in tests

---

v2/cmd/controller/main.go
v2/config/manager/manager_image_patch.yaml
v2/internal/config/vars.go
v2/internal/config/vars_test.go
v2/internal/controllers/generic_controller.go
v2/internal/reconcilers/azure_generic_arm_reconciler.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/util/lockedrand/rand.go
v2/internal/util/randextensions/time.go
v2/internal/util/randextensions/time_test.go

* Stop using SpecHash to prevent issuing a PUT to Azure. 
The use of SpecHash prevented us from detecting changes in Azure 
and resolving them, which is one of the primary deliverables of an
operator.
* Perform a re-sync with Azure every 15m.
* Add Jitter helper method and associated lockedrand module.
This is related to #1491

Stop using specHash optimization - reconcile should always PUT to Azure

---

docs/issue-management.md

Our current link is wrong - it includes the needs-triage label twice, in two different forms.

Fix link for GitHub triage search

---

v2/tools/generator/internal/astmodel/type_merger.go
v2/tools/generator/internal/codegen/pipeline/convert_allof_and_oneof_to_objects.go
v2/tools/generator/internal/codegen/pipeline/status_augment.go

The default merger deals with the common cases so that augmenters can
focus on the specific cases they want to handle.

Create default merger helper method for status merging

---

v2/tools/generator/internal/astmodel/property_definition.go
v2/tools/generator/internal/codegen/pipeline/status_augment.go
v2/tools/generator/internal/jsonast/jsonast.go

Properties with either "x-ms-secret" or "format: password" are
flagged as secrets in the type graph for the generator.

Detect Swagger secrets and track them

---

docs/hugo/content/architecture-decision-records/ADR-2022-01-Reconciler-Extensions.md

We are discovering inconsistencies in the way different Azure Resource Providers behave. 
This ADR proposes a way we can provide extension points allowing resource providers to customize behaviour in a controlled fashion.
@matthchr suggested using the approach of extending resource registration, which is a lot cleaner than the `init` based approach I had in mind originally.

Specification for Reconciler Extension points

---

hack/crossplane/apis/resources.md
v2/api/resources.md
v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go
v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_ReportResourceVersions.golden

Adds a preamble to our supported resources report to make it work better as a page in our documentation.
Also tweaks formatting; previously we were using level 3 & 4 headers, now uses level 2 & 3.
The result looks like this:

Add preamble to report

---

v2/api/resources/v1alpha1api20200601/resourcegroup_types.go
v2/go.mod
v2/go.sum
v2/internal/controllers/controller_resources.go
v2/internal/controllers/controller_resources_gen.go
v2/internal/controllers/generic_controller.go
v2/internal/reflecthelpers/reflect_helpers.go
v2/internal/reflecthelpers/reflect_helpers_test.go
v2/pkg/genruntime/registration/registration.go
v2/test/mysql_secret_update_test.go
v2/tools/generator/internal/astmodel/package_definition.go
v2/tools/generator/internal/astmodel/property_definition.go
v2/tools/generator/internal/astmodel/std_references.go
v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go
v2/tools/generator/internal/codegen/pipeline/resource_registration_file.go
v2/tools/generator/internal/functions/index_registration_function.go
v2/tools/generator/internal/functions/pure_function.go

* Add index in client-go for resources that support secrets, indexed on
the property containing the secret.
* Trigger reconcile for resources that have a secret reference by watching
secret modifications and using the resource specific indexes to
see if that secret is in use by a resource.
* Add tests to ensure that this whole dance works. The test cannot run
in the recording tests because they do not use a cached client and
the custom indexing is all client-side.

Support secret rollover

---

docs/hugo/content/design/secrets.md

Secrets design proposal

---

v2/internal/controllers/crd_compute_vm_test.go
v2/internal/controllers/recordings/Test_MissingCrossResourceReference_ReturnsError.yaml
v2/internal/controllers/recordings/Test_MissingSecretKey_ReturnsError.yaml
v2/internal/controllers/recordings/Test_MissingUserSecret_ReturnsError.yaml
v2/internal/controllers/references_test.go
v2/internal/controllers/to_azure_secrets_test.go
v2/internal/reconcilers/azure_generic_arm_reconciler.go
v2/pkg/genruntime/conditions/errors.go
v2/pkg/genruntime/conditions/ready_condition_builder.go
v2/pkg/genruntime/secret_resolver.go

- Sets a Ready Condition with severity=Warning if a secret reference
or cross-resource reference could not be found.
- Adds tests to ensure that the error is set and delete of the resource
can still go through.

Fix bug where Condition is not set in some error cases

---

v2/api/cache/customizations/redis_extension_types.go
v2/api/cache/customizations/redis_firewall_rule_extension_types.go.go
v2/api/cache/customizations/redis_linked_server_extension_types.go
v2/api/cache/customizations/redis_patch_schedule_extension_types.go
v2/internal/duration/duration_test.go
v2/internal/genericarmclient/cloud_error.go
v2/internal/genericarmclient/cloud_error_test.go
v2/internal/genericarmclient/generic_client_test.go
v2/internal/reconcilers/error_classifier.go
v2/internal/reconcilers/error_classifier_test.go
v2/pkg/genruntime/core/error_constants.go
v2/pkg/genruntime/extensions/error_classifier.go

We have to support two different formats for the error as some services do things differently.
The [ARM spec](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/common-api-details.md#error-response-content) says that error details should be nested inside an `error` element.
However, some services put the code & message at the top level instead.
This is common enough that the [Azure Python SDK](https://github.com/Azure/azure-sdk-for-python/blob/9791fb5bc4cb6001768e6e1fb986b8d8f8326c43/sdk/core/azure-core/azure/core/exceptions.py#L153) has specific handling to promote a nested error to the top level.

Flexible error formats

---

v2/tools/generator/internal/armconversion/shared.go
v2/tools/generator/internal/astmodel/code_generation_context.go
v2/tools/generator/internal/astmodel/types.go
v2/tools/generator/internal/codegen/embeddedresources/remover.go
v2/tools/generator/internal/codegen/pipeline/status_augment.go
v2/tools/generator/internal/codegen/storage/conversion_graph.go

This is useful for an upcoming PR where I wanted to have a single method that could operator on a `Types` and a `CodeGenerationContext`.
Once early in the process to pick out what types to add a function to, and then in the actual implementation of that function in order to examine some of the types in more detail.

CodeGenerationContext implements ReadonlyTypes too

---

v2/api/documentdb/customizations/mongodb_database_extension.go
v2/api/documentdb/customizations/sql_database_extension_types.go
v2/internal/reconcilers/error_classifier.go
v2/internal/reconcilers/error_classifier_test.go
v2/pkg/genruntime/extensions/error_classifier.go

Moves CosmosDB and MongoDB specific error handling into specific extensions.
Closes #2106 
Update 24 Feb: Now that PR #2112 has been merged, I was able to make our CI fail by disabling the extensions, which gives me much more confidence that this works.

Custom error classification for CosmosDB

---

docs/hugo/content/introduction/installing-from-yaml.md
v2/README.md

Added alternative docs path for installing straight from the release
YAML.

Update v2 README to prefer installation from Helm

---

v2/internal/controllers/controller_resources.go
v2/internal/controllers/controller_resources_gen.go
v2/internal/controllers/generic_controller.go
v2/pkg/genruntime/registration/registration.go
v2/tools/generator/internal/codegen/pipeline/resource_registration_file.go

This enables it to be more easily changed by the handcrafted code, for
example to add extra indices that may be needed for extensions.

Use pointer for registration.StorageType

---

v2/tools/generator/go.mod
v2/tools/generator/go.sum
v2/tools/generator/internal/astmodel/string_set.go
v2/tools/generator/internal/config/group_configuration.go
v2/tools/generator/internal/config/object_model_configuration.go
v2/tools/generator/internal/config/type_configuration.go
v2/tools/generator/internal/config/typo_advisor.go
v2/tools/generator/internal/config/typo_advisor_test.go
v2/tools/generator/internal/config/version_configuration.go

The most common cause for configuration not matching an existing resource is a minor difference between the name used in configuration and the name of the actual resource. This can be caused by singular/plural differences, or by a simple typo, for example. 
We augment the error messages with a hint about a closely named item in the same scope, to aid users in correcting the configuration.
Sample for a misnamed group:
> E0315 13:10:11.348939   12688 gen_kustomize.go:111] Error during code generation:
> failed during pipeline stage 20/60: 
> Apply export filters to reduce the number of generated types: group signalservice not seen **(did you mean signalrservice?)**: 
> group signalservice: version 2021-10-01: type SignalR: $export: true not consumed
Sample for a misnamed version:
> E0315 …

Improve diagnostics for configuration issues

---

v2/tools/generator/internal/config/group_configuration.go
v2/tools/generator/internal/config/type_configuration.go
v2/tools/generator/internal/config/version_configuration.go

Spotted a minor bug where the typo advisor would only ever suggest something already configured as a potential fix for the item that's wrong. 
The set of possible suggestions should include all terms that exist, not just the subset we've already set up.

Always add known terms to the typo advisor

---

v2/README.md

Link we had previously for `install-from-YAML` was not valid anymore. Have replaced it with the right one.

Fix install-from-yaml docks site link for README.md

---

v2/tools/generator/internal/astmodel/local_package_reference.go
v2/tools/generator/internal/astmodel/local_package_reference_test.go
v2/tools/generator/internal/astmodel/storage_package_reference_test.go
v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/golden_files_test.go
v2/tools/generator/internal/codegen/pipeline/status_from_swagger.go
v2/tools/generator/internal/config/configuration.go
v2/tools/generator/internal/config/group_configuration.go
v2/tools/generator/internal/config/group_configuration_test.go

Discovered during work to move our generator prefix to `v1beta`, our configuration wasn't being picked up by some packages, resulting in needed modifications not being made to the object model.
This PR changes the way we look up version-configuration within the object-model-configuration hierarchy so that it's independent of the generator version.
We also enable configuration based on the generator version as well (which is needed by some tests), ensuring some forward compatibility.

Fix bug where Version configuration wasn't used for some packages

---

v2/tools/generator/internal/codegen/storage/conversion_graph.go
v2/tools/generator/internal/codegen/storage/conversion_graph_test.go

Creation of the conversion graph was incorrectly identifying multiple versions of the same resource as Hub types because it was failing to skip versions where the resource does not exist. See #2185 for more details.
Closes #2185 

Fix bug where the conversion graph wouldn't bridge for resources that skip versions

---

v2/internal/testcommon/kube_test_context_envtest.go

Includes the underlying error in the panic when waiting for the webhook server times out.
Also increases the timeout to 15s - given this is failing on a PR that doubles the number of resource versions we have, it's a reasonable hypothesis that it's failing due to workload.

Include error in panic

---

.github/workflows/create-release.yml
Taskfile.yml
scripts/deploy_multitenant_testing_secret.sh
scripts/make-multitenant-cluster.sh
scripts/make-multitenant-tenant.sh
scripts/wait-for-ca-bundles.sh
v2/test/multitenant/multitenant_test.go
v2/test/multitenant/suite_test.go

The multitenant deployment files can be generated by running the `controller:make-multitenant-files` task. They'll be generated and attached to new releases.
Also adds an integration test to validate that we can create resources in a multitenant-deployed cluster that is run in the PR validation CI.

Generate multitenant deployment yaml files automatically

---

.devcontainer/install-dependencies.sh

Base image we are using for our devcontainer now includes `golangci-lint` 1.45.2 which (somewhat) supports go 1.18. Update the `install-dependencies.sh` version to match.
This now allows us to use generics.

Update golangci-lint install-depedencies.sh to match base image

---

v2/internal/genericarmclient/generic_client.go

We'll currently experience a panic if an HTTP request returns an error as the response will be **nil**. 
Fixed by moving the metrics line after the `err` check, at which point we expect to have a response.

Avoid metrics panic if HTTP request returns an error

---

v2/go.mod
v2/go.sum

The bug in question is https://github.com/json-iterator/go/issues/608

Update dependency to work around envtest 1.18 bug

---

README.md
docs/hugo/content/introduction/installing-from-yaml.md
docs/hugo/content/introduction/multitenant-deployment.md
v2/README.md
v2/config/samples/cache/v1beta20201201_redis.yaml
v2/config/samples/documentdb/v1beta20210515_databaseaccount.yaml
v2/config/samples/storage/v1beta20210401_storageaccount.yaml

- Remove section about "not production ready" for ASOv2.
- Clarify ASOv2 is in beta now in README table.
- Add secrets to examples for resources that support them.
- Change installation instructions to point to beta.0 Helm chart and
YAML.

Update documentation for beta

---

.github/workflows/visualize-repo.yml

The structure diagram for ASO v2 included all the details of our code-generator, which is covered by another diagram.
There was already an exclusion for this folder, but it wasn't working.

Exclude tools directory from structure diagram

---

docs/hugo/content/contributing/_index.md
docs/hugo/content/design/_index.md
docs/hugo/content/reference/_index.md
scripts/gen-api-docs.sh

API Generation was deleting the `_index.md` file required for the content to apper on the site
Show _Contributing_ before _Design_
Change reference docs title to _Supported Resources_

Quick fixes to docs site

---

v2/api/cache/customizations/redis_extensions.go
v2/api/documentdb/customizations/database_account_extensions.go
v2/api/network/customizations/virtual_network_extensions.go
v2/api/storage/customizations/storage_account_extensions.go
v2/cmd/controller/main.go
v2/internal/controllers/generic_controller.go
v2/internal/reconcilers/arm/arm_client_factory.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/reconcilers/arm/client_helpers.go
v2/internal/resolver/resolver.go
v2/internal/resolver/resolver_test.go
v2/internal/resolver/resource_hierarchy.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/util/kubeclient/kube_client.go
v2/pkg/genruntime/admissions.go
v2/pkg/genruntime/arm_id.go
v2/pkg/genruntime/base_types.go
v2/pkg/genruntime/convertible_spec.go
v2/pkg/genruntime/convertible_status.go
v2/pkg/genruntime/extensions/arm_resource_modifier.go
v2/pkg/genruntime/extensions/secrets_retriever.go
v2/pkg/genruntime/group_version_kind_aware.go
v2/pkg/genruntime/kubernetes_resource.go

Change type hierarchy so that MetaObject doesn't assume a resource exists in ARM.
In the future, the GenericController must function on types that aren't ARM resources, such as MySQL Users.

Make base types appropriate for non-ARM resources

---

v2/tools/generator/internal/astmodel/external_package_reference.go
v2/tools/generator/internal/astmodel/local_package_reference.go
v2/tools/generator/internal/astmodel/package_import_set.go
v2/tools/generator/internal/astmodel/package_reference.go
v2/tools/generator/internal/astmodel/property_reference.go
v2/tools/generator/internal/astmodel/resource_type.go
v2/tools/generator/internal/astmodel/storage_package_reference.go
v2/tools/generator/internal/astmodel/type_definition_test.go
v2/tools/generator/internal/codegen/golden_files_test.go
v2/tools/generator/internal/codegen/pipeline/add_arm_conversion_interface.go
v2/tools/generator/internal/codegen/pipeline/check_for_anytype.go
v2/tools/generator/internal/codegen/pipeline/create_resource_extension_types.go
v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go
v2/tools/generator/internal/codegen/pipeline/export_generated_code.go
v2/tools/generator/internal/codegen/pipeline/mark_latest_api_version_as_storage_version.go
v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go
v2/tools/generator/internal/codegen/storage/conversion_graph.go
v2/tools/generator/internal/codegen/storage/conversion_graph_builder.go
v2/tools/generator/internal/config/object_model_configuration.go
v2/tools/generator/internal/config/type_matcher.go
v2/tools/generator/internal/functions/kubernetes_admissions_defaulter.go
v2/tools/generator/internal/functions/kubernetes_admissions_validator.go
v2/tools/generator/internal/functions/resource_conversion_function.go
v2/tools/generator/internal/test/asserts.go
v2/tools/generator/internal/test/file_definition.go

Most of the time when accessing the `Group` and `Version` from a `PackageReference` we either know that we won't have an `ExternalPackageReference` or want to panic if we do have one. We had boilerplate doing this over and over, so I've added a helper to simplify consumption.
We now have
* `TryGroupVersion()` as it may not succeed (returning a **false**)
* `GroupVersion()` which either succeeds or panics

Simply access to Group and Version

---

v2/tools/mangle-test-json/main.go

When generating the Markdown summary we should also include package-level logs.
These can represent failures (e.g. if something happens during teardown).

Output package-level logs as well

---

.golangci.yml
v2/internal/controllers/crd_aks_managedcluster_test.go
v2/internal/controllers/crd_cache_redis_test.go
v2/internal/controllers/crd_cdn_test.go
v2/internal/controllers/crd_cosmosdb_mongodb_test.go
v2/internal/controllers/crd_dbformysql_flexibleserver_test.go
v2/internal/controllers/crd_dbforpostgresql_flexibleserver_test.go
v2/internal/controllers/crd_eventgrid_domain_test.go
v2/internal/controllers/crd_eventgrid_topic_test.go
v2/internal/controllers/crd_eventhub_namespace_test.go
v2/internal/controllers/crd_networking_nsg_test.go
v2/internal/controllers/crd_networking_routetable_test.go
v2/internal/controllers/crd_networking_virtualnetwork_test.go
v2/internal/controllers/crd_servicebus_namespace_basic_test.go
v2/internal/controllers/crd_servicebus_namespace_standard_test.go
v2/internal/controllers/crd_storage_storageaccount_test.go
v2/internal/controllers/recordings/Test_Cache_Redis_CRUD.yaml
v2/internal/controllers/recordings/Test_DBForMySQL_FlexibleServer_CRUD.yaml
v2/internal/controllers/recordings/Test_EventGrid_Topic.yaml
v2/internal/controllers/recordings/Test_ServiceBus_Namespace_Standard_CRUD.yaml
v2/internal/controllers/recordings/Test_Storage_StorageAccount_CRUD.yaml
v2/internal/controllers/recordings/Test_Subnet_CreatedBeforeVNET.yaml
v2/internal/genericarmclient/generic_client.go
v2/internal/reconcilers/common.go
v2/internal/testcommon/kube_per_test_context.go

Intermittently failing tests are annoying. This fixes a few causes of them.

Ensure parallel tests don't race for names

---

.devcontainer/install-dependencies.sh
.golangci.yml

Change our Go version check in `install-dependencies.sh` to allow minor versions to match.

Use prefix match for Go version

---

.devcontainer/Dockerfile

Updates to the Hugo tooling we use for generating our website require a newer version of NodeJS:
```
[build-docs-site] npm WARN EBADENGINE Unsupported engine {
[build-docs-site] npm WARN EBADENGINE   package: 'postcss-cli@10.0.0',
[build-docs-site] npm WARN EBADENGINE   required: { node: '>=14' },
[build-docs-site] npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '[7](https://github.com/Azure/azure-service-operator/runs/7124675759?check_suite_focus=true#step:6:8).5.2' }
[build-docs-site] npm WARN EBADENGINE }
[build-docs-site] npm WARN EBADENGINE Unsupported engine {
[build-docs-site] npm WARN EBADENGINE   package: 'postcss-load-config@4.0.1',
[build-docs-site] npm WARN EBADENGINE   required: { node: '>= 14' },
[build-docs-site] npm WARN …
```

Install updated versions of NodeJS and NPM

---

v2/api/dbformysql/v1beta1/doc.go

Adds in the missing `doc.go` the lack of which was causing `controller-gen` to crash.

Fix generation of CRD documentation

---

v2/api/cache/v1alpha1api20201201storage/redis_types_gen.go
v2/api/cache/v1alpha1api20210301storage/redis_enterprise_types_gen.go
v2/api/cache/v1beta20201201storage/redis_types_gen.go
v2/pkg/genruntime/property_bag.go
v2/tools/generator/internal/astbuilder/builder.go
v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_InjectJsonSerializationTests/person-v20200101storage.golden
v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_InjectPropertyAssignmentFunctions/person-v20200101storage.golden
v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_InjectPropertyAssignmentTests/person-v20200101storage.golden
v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_InjectResourceConversionTestCases/person-v20200101storage.golden
v2/tools/generator/internal/conversions/property_conversions.go
v2/tools/generator/internal/functions/testdata/TestGolden_PropertyAssignmentFunction_AsFunc/CopyMapToPropertyBag.golden
v2/tools/generator/internal/functions/testdata/TestGolden_PropertyAssignmentFunction_AsFunc/CopyOptionalIntToPropertyBag.golden
v2/tools/generator/internal/functions/testdata/TestGolden_PropertyAssignmentFunction_AsFunc/CopyOptionalObjectToPropertyBag.golden
v2/tools/generator/internal/functions/testdata/TestGolden_PropertyAssignmentFunction_AsFunc/CopyOptionalStringToPropertyBag.golden
v2/tools/generator/internal/functions/testdata/TestGolden_PropertyAssignmentFunction_AsFunc/CopySliceToPropertyBag.golden

We already had checks to ensure we don't store explicit **nil** values in a `PropertyBag` when converting versions of a resource (we represent missing values by omitting them from the bag).
This PR extends this practice to empty maps and slices.
Also fixes a bug where an existing value would be left in the bag if our value was nil; now we explicitly remove it.
Closes #2388
**Special notes for your reviewer**
The updates to the golden tests show all the new cases.

Fix property bag use for maps and slices

---

.github/workflows/api-docs-repo.yaml

We were having failures generating CRD documentation because the same branch name was being reused.
This wasn't a problem after successful runs of the workflow, as the follow-up PR merge would delete the branch. But when the workflow fails, the old branch was left around to cause mayhem for the next run.
Fix is to use the `run_number` to make the branch name unique each time.

Use a unique branch name each time we generate CRD docs

---

v2/tools/generator/internal/astmodel/type_name.go
v2/tools/generator/internal/astmodel/type_name_test.go
v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/pipeline/improve_resource_pluralization.go

It doesn't return strings in the same case you passed them in. This can
result in types being named with all lowercase names, which causes build
errors since those types aren't exported.

Fix issue with Flect pluralization

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/pkg/genruntime/kubernetes_resource.go

The API version associated with a resource is the one that should always be used when making ARM REST API calls. This wasn't the case, as documented in #2416
Fixes #2416
Thanks to @matthchr for helping to track down the issue.

Add helper method GetAPIVersion to genruntime

---

azure-pipelines.yml

ARM apperantly now can return Type either in the correct case or
lowercase. This feels like a bug but it's not something they're fixing
anytime soon, so for now we need to work around it.

Fix ADO job cluster query

---

v2/go.mod
v2/go.sum
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/testcommon/kube_test_context_envtest_test.go
v2/internal/testcommon/test_context.go

* Stop envtest (kube-apiserver, etcd) when they are no longer needed.
* Prevent more than `numCores` extra envtests from being run at once. Total running should be 1 + `numCores`.

Improve EnvTest performance by not launching so many

---

v2/internal/config/vars.go
v2/internal/config/vars_test.go
v2/internal/testcommon/creds.go
v2/internal/testcommon/test_context.go

Also add support for billing invoice ID test variable

Record tests for national cloud better

---

v2/tools/generator/internal/codegen/pipeline/json_serialization_test_cases.go
v2/tools/generator/internal/codegen/pipeline/property_assignment_test_cases.go
v2/tools/generator/internal/codegen/pipeline/resource_conversion_test_cases.go

Property tests using [gopter](https://github.com/leanovate/gopter) have a limitation where they panic if a struct his more than 50 fields. This is due to [a limitation of the GO runtime](https://github.com/golang/go/issues/54669). 
This PR specifically excludes these large objects from our testing, giving us a workaround for the problem.
A log line is generated for each. Exclusion so that we know that it's happening.

Skip generating tests using gopter for large structs

---

v2/tools/generator/internal/codegen/pipeline/json_serialization_test_cases.go
v2/tools/generator/internal/codegen/pipeline/property_assignment_test_cases.go
v2/tools/generator/internal/codegen/pipeline/resource_conversion_test_cases.go
v2/tools/generator/internal/testcases/json_serialization_test_case.go

Addresses the issue of gopter tests for large objects by skipping primitive properties (strings ints, etc).
Tested by merge into @super-harsh's branch `feature/azure-functions`.

Alternate fix for gopter tests of large objects

---

v2/internal/controllers/generic_controller.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go

These logs basically happen in sequence and end up reporting the error
multiple times, which causes log bloat and makes things harder to
debug.

Remove unnecessary error logs

---

.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml

Limits the concurrency of CI builds because the build machines are small and we suspect we are overloading them.
I'm hoping the CI build for this PR will run with the workflow modification included. If it doesn't, we'll need to merge this, and then run some tests.

Limit concurrency of CI builds

---

.devcontainer/install-dependencies.sh
v2/internal/reconcilers/common.go
v2/internal/set/set_test.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/tools/generator/internal/codegen/debug_reporter.go
v2/tools/generator/internal/readonly/readonly_map.go

It appears the version of `golangci` in our base image has been updated.
The linter `structcheck` is giving us two new lint messages - one is valid (and fixed in this PR), the other is not (and is suppressed).

Address lint issues

---

.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml

We're seeing odd outcomes of our builds, where they stall at the end of one task and never start the next. Lifting concurrency to 2 to see if this is a viable workaround.

Lift concurrency to 2 simultaneous tasks

---

scripts/make-multitenant-cluster.sh
scripts/make-multitenant-tenant.sh

Multi-tenant deployment was failing due to `serviceAccountName` and non default `ServiceAccount` added in #2464. This PR includes fix to include the new service account added in the multi-tenant files creation. 
Integration tests should pass now. Mainly figured this out when `controller:kind-create-multitenant-cluster` target failed on the other PR after merging main.

Fix: Add non-default serviceAccount to multi-tenant file creation

---

v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/pipeline/name_types_for_crd.go

Discovered by @super-harsh while adding support for Azure Functions in PR #2465, floating the suffix to the end of each TypeName introduced duplicates, aborting the generator mid flow.
The specific problem occurs because of the way some resources in the `web` group embed other resources:
Without suffix floating, the behaviour was this. We start with the resource `Sites_Config`:
```
├── Sites_Config: Resource
│   ├── Spec: Sites_Config_Spec
│   └── Status: Error[<missing>]Ignore the Error, it's a red herring.
```
where `Sites_Config_Spec` is an object type with just one property:
```
├── Sites_Config_Spec: Object[Flag:oneof]
│   └── ResourceBase: *Sites_Config_Spec_ResourceBase
```
In turn, the `ResourceBase` property is itself a resource:
```
├── …
```

Fix CRD naming to maintain uniqueness

---

v2/README.md

Reduced scope or capability credentials are supported.

Clarify that you don't have to use subscription scope credential

---

Taskfile.yml
v2/api/appconfiguration/customizations/configuration_store_extensions.go
v2/api/cache/customizations/redis_extensions.go
v2/api/containerservice/customizations/managed_cluster_extensions.go
v2/api/dbformariadb/customizations/server_extensions.go
v2/api/dbformysql/customizations/flexible_server_extensions.go
v2/api/dbforpostgresql/customizations/flexible_server_extensions.go
v2/api/documentdb/customizations/database_account_extensions.go
v2/api/machinelearningservices/customizations/workspace_extension.go
v2/api/servicebus/customizations/namespace_extensions.go
v2/api/storage/customizations/storage_account_extensions.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/pkg/genruntime/extensions/kubernetes_exporter.go
v2/pkg/genruntime/kubernetes_exporter.go
v2/pkg/genruntime/owner.go
v2/pkg/genruntime/owner_test.go
v2/pkg/genruntime/secrets/secrets.go
v2/pkg/genruntime/suite_test.go
v2/pkg/genruntime/test/owner_test.go
v2/pkg/genruntime/test/suite_test.go

KubernetesExporter is more generic so scales better to ConfigMaps and possibly other Kubernetes resource types in the future

Use KubernetesExporter interface rather than AzureSecrets extension

---

v2/internal/reflecthelpers/reflect_helpers.go
v2/internal/reflecthelpers/reflect_helpers_test.go
v2/internal/reflecthelpers/reflect_visitor.go
v2/internal/reflecthelpers/reflect_visitor_test.go
v2/pkg/genruntime/resource_reference.go

- This more easily allows ReflectVisitor to be used to modify structures.
- Added a test that showcases how this can be used (and serves as a regression test to ensure that it continues to work going forward).

Update ReflectVisitor to use reflect.Value parameter

---

v2/test/mysql_test.go

Looked like capacity issues to me, however the error was `Subscription 'sub' is not allowed to provision in West US`

Change MySQL livetest location to Eastus

---

v2/tools/generator/internal/astmodel/type_name_set.go
v2/tools/generator/internal/reporting/testdata/Test_TypeCateaLogReport_GivenDirectlyRecursiveType_WhenInlined_ShowsExpectedDetails.golden
v2/tools/generator/internal/reporting/type_catalog_report.go
v2/tools/generator/internal/reporting/type_catalog_report_test.go

Discovered while merging `main` into the Swagger WIP branch, the resource structure report crashes with a stack overflow if any of the inlined types are self-referential. 
We have no types like this in `main`, and controller-gen doesn't support them - but we have them in the Swagger branch at the moment and don't want things to crash.

Prevent self-referencing types from crashing the structure report

---

v2/test/mysql_test.go

RP keeps restricting the US zones for the org subs, so changing it to Australia East.

Change mysql live tests location to Australia East

---

.devcontainer/install-dependencies.sh

Our CI builds are failing because our workflows (correctly!) check out the repo outside the dev container, but we run the build within, as a different user.
From the [release notes for Git 2.36](https://github.blog/2022-04-18-highlights-from-git-2-36/):
> Beginning in Git 2.35.2, Git changed its default behavior to prevent you from executing git commands in a repository owned by a different user than the current one. This is designed to prevent git invocations from unintentionally executing commands which the repository owner configured.
Since our CI runs in a controlled environment, disabling the check should be safe.

Fix Git configuration in CI

---

v2/cmd/controller/main.go
v2/internal/controllers/generic_controller.go
v2/internal/controllers/to_azure_configmaps_test.go
v2/internal/controllers/to_azure_secrets_test.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/util/interval/interval_calculator.go
v2/internal/util/interval/interval_calculator_test.go
v2/internal/util/kubeclient/utilities.go
v2/pkg/genruntime/conditions/conditions.go
v2/pkg/genruntime/conditions/conditions_test.go
v2/pkg/genruntime/conditions/errors.go
v2/pkg/genruntime/conditions/ready_condition_builder.go

Retry less aggressively for most Azure returned errors. Retry more aggressively for Kube-local errors such as WaitingForOwner.
Closes #2575.
Closes #2556

More customizable retry

---

.github/workflows/codeql-analysis.yml

Upgrades CodeQL action references to the latest versions as per the [deprecation blog](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/).
Closes #2471.
Can't trigger this manually, so I think we just need to merge and try it.

Upgrade referenced versions of actions

---

docs/hugo/content/introduction/frequently-asked-questions.md
v2/internal/util/interval/interval_calculator.go

* Change sync jitter to .25. This protects better against retry storms after pod restart

Update FAQ to mention throttling

---

v2/internal/controllers/generic_controller.go

Our configuration of rate limiting permitted requests at a much higher rate than ARM accommodates; configuring the rate limiter so we play nicely with ARM should improve things overall.
This isn't perfect, as noted by @matthchr, because not every request respects this limiter; but this should still help.

Configure rate limiter to accomodate ARM throttling

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/testcommon/kube_per_test_context.go

Closes #2650 
When checking for a code-generated implementation of `genruntime.KubernetesExporter`, we need to make sure we're looking at the correct version of the resource. 
Unlike extensions, where a single extension handles all versions of a resource, our code generated implementation can (and does!) differ between resource versions.

Ensure the correct resource version is used for KubernetesExporter checks

---

dev.sh

Without this fix, the env variable set has single quotes which means it doesn't actually work.

Fix KUBEBUILDER_ASSETS set from dev.sh

---

v2/internal/controllers/samples_test.go
v2/internal/reflecthelpers/reflect_helpers.go
v2/internal/set/set.go

Some secrets are already provided by refs and those must be accounted for when autogenerating secrets.

Samples tests should only auto-fill secrets it must

---

v2/tools/generator/internal/codegen/pipeline/load_types.go

This could happen if there was a name collision as the ARM URL was lost.

Fix bug where some resources could be missing an owner

---

v2/internal/controllers/generic_controller.go
v2/internal/genericarmclient/generic_client.go
v2/internal/reconcilers/annotations.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/pkg/genruntime/conditions/ready_condition_builder.go
v2/pkg/genruntime/extensions/error_classifier.go
v2/pkg/genruntime/extensions/prereconciliation_checker.go

Creates an extension point allowing resources to customize ASO to avoid sending PUT requests that can't possibly succeed.
Implements #2649
Closes #2644
Follow-up PRs will implement this extension point for selected resources.

Create PreReconciliation Extension Point

---

v2/api/scheme.go

This PR includes `v2/api/scheme.go` to expose `internal/controllers.CreateScheme()` method externally

Add helper method to export controllers.CreateScheme

---

v2/internal/reconcilers/annotations.go
v2/internal/reconcilers/arm/arm_client_cache.go
v2/internal/reconcilers/arm/arm_client_cache_test.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/reconcilers/generic/generic_reconciler.go
v2/internal/reconcilers/generic/register.go
v2/internal/util/interval/interval_calculator.go
v2/internal/util/interval/interval_calculator_test.go
v2/internal/util/kubeclient/utilities.go
v2/pkg/genruntime/conditions/errors.go
v2/test/single_operator_multitenant_test.go

* Fix a bug where a PUT or PATCH to the resource being reconciled which changed only fields which we were not watching (ignored annotations for example) could cause reconciliation to fail to requeue quickly like it should.
The root cause of this issue is that we were treating Conflict as an ignorable error, expecting that we could avoid requeing on it because we would get an updated event shortly. This only holds true when the update changes a property of the object we actually care about. If it changes a property we aren't watching we didn't requeue but also didn't get an updated event and so were "stuck" (at least until the periodic reconciliation interval was hit).
* Fix bug were we weren't triggering reconciliation when the credential-from annotation changed.

Fix bug where an update to the resource being reconciled could cause reconciliation to fail to requeue quickly like it should.

---

Taskfile.yml

Did try some fixes in the previous PR, however, seemed like more of an issue where `v2/api` is not completely present due to multiple workers running in CI

Fix asoctl lint

---

Taskfile.yml

There are steps in controller build which delete some generated files and regenerate them, and if asoctl build runs while that is happening asoctl build will fail.
Even though our generated files are mostly checked in, their dependencies must run after them in build order

asoctl build must happen after controller

---

Dockerfile

Noticed the Docker file in our root (which I believe is used by Azure DevOps) was still set to use Go 1.18.

Update AzureDevops Docker file to Go 1.20

---

.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml

**Task** can experience deadlocks while waiting on executing tasks to complete. 
We were using `--concurrency 2` but this only worked because we were only ever waiting on an outstanding task once. With the recent introduction of the build steps for `asoctl` we can now end up with two concurrent waits on an outstanding tasks at the same time. 
Lifting the concurrent limit should avoid the deadlock until the fix has been merged.
Fix for **Task** is here in [PR#1025](https://github.com/go-task/task/pull/1025).

Lift concurrency to 3

---

docs/hugo/content/contributing/_index.md
docs/hugo/content/design/_index.md
docs/hugo/content/introduction/_index.md
docs/hugo/content/reference/_index.md
hack/crossplane/apis/resources.md
v2/README.md
v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go
v2/tools/generator/internal/codegen/pipeline/testdata/TestGolden_ReportResourceVersions.golden

I noticed on the Kubernetes Slack that the preview of ASO links was a little odd:
ASO is pretty cool, but I don't think it qualifies as "The most popular HTML, CSS, and JS library in the world" 😁 
Turns out this is happening because we're not setting `description` in the front-matter of our pages, resulting in a default value showing up.
I also added a quick summary line for each group of resources, listing the number of supported resources.

Improve Supported Resources Report

---

v2/api/servicebus/customizations/namespaces_topic_subscription_extension.go

Closes #2736 
With this extension, we handle `MessagingGatewayBadRequest` as retriable and non-fatal. So that we can wait for the `forwardTo` resource to exist.

Add NamespacesTopicsSubscription extension to handle cloudError

---

docs/hugo/content/contributing/_index.md

When using VS Code devcontainer plugin to setup ASOv2 dev environment, I am running into following error when `task defult`: `task: Command "./scripts/build-version.py v2" failed: exit status 1`
This is because the repository was cloned with a depth setting, which create a shallow copy.
The fix is to convert the shallow clone to regular one by: `git fetch --unshallow`
- this PR contains documentation

Update initialization instruction

---

docs/hugo/content/design/ADR-2022-11-Resource-Import.md

Noticed by @matthchr, the image reference is broken for one of our ADRs.
Tweaking the image URL makes it work:

Fix broken image reference

---

v2/tools/generator/internal/jsonast/swagger_type_extractor.go
v2/tools/generator/internal/jsonast/swagger_type_extractor_test.go

Fix issue where infer name would include parameters which were the resource "name" such as "current", when really we only want to include parameters which define resource type.

Improve resource path canonicalization

---

docs/hugo/content/contributing/generator-overview.md
docs/hugo/content/design/ADR-2022-08-Evil-Discriminator.md
docs/hugo/content/design/ADR-2022-11-Resource-Import.md
docs/hugo/link-checker.json

Our markdown link checker gets images wrong, because our markdown is rendered by Hugo.
The link-checker assumes that each `markdown.md` file gets rendered as `http://www.example.com/markdown.html`, for which an image in the same folder would be referenced as `image.png`.
However, with Hugo, each `markdown.md` file gets rendered as a directory containing an `index.html` file. The URL looks like `http://www.example.com/markdown/` so an image referenced as `image.png` would be loaded from `http://www.example.com/markdown/image.png` which doesn't work.
Our image links therefore need to be of the form `../image.pn` at the start so the fully resolved URL actually references the image file as `http://www.example.com/image.png`.
**Special notes for your …

Fix broken image links

---

scripts/kustomize-build.sh

`--attributes-only` and `--preserve` flags for `cp` does not work on mac. Have replaced them with `-p` as a fix. 
We don't need `--attributes-only` so dropping it totally.

Replace `--attributes-only` and `--preserve` with `-p` in kustomize-build.sh

---

.github/workflows/create-release.yml
Taskfile.yml

Fixes #2825.
Builds binaries for Linux ARM and AMD64, Darwin (mac) ARM and AMD64, and Windows AMD64.

Include asoctl binaries in release

---

docs/hugo/content/introduction/secrets.md

Docs site publishing has been failing due to a dead link which is replaced in this PR

Fix dead link in docs

---

v2/config/manager/manager.yaml

The operator pod was running into timeouts on my arm64 mac machine due to readiness probe timeout. This PR bumps the `initialDelaySeconds` for readiness and liveness probes so that operator gets more time to load and apply CRDs.

bump initialDelaySeconds for readiness and liveness probe

---

Taskfile.yml
v2/pkg/genruntime/group_version_kind_aware.go
v2/tools/asoctl/cmd/crd_clean.go
v2/tools/asoctl/internal/crd/cleaner.go

- Use non-storage API version in CRD Cleaner.
- Update Taskfile Helm target to use same Helm installation name as public docs.
- Avoid v1alpha1api versions in Controller.
- Delete kind cluster after upgrade test.

Fix bugs found by bug bash

---

v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/golden_files_test.go
v2/tools/generator/internal/codegen/pipeline/add_cross_resource_references.go
v2/tools/generator/internal/codegen/pipeline/apply_cross_resource_references_from_config.go
v2/tools/generator/internal/codegen/pipeline/create_arm_types_test.go
v2/tools/generator/internal/codegen/testdata/TestGolden_NewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewTestCodeGeneratorCreatesRightPipeline.golden

The original cross resource reference config override handler classified properties as references (or not). This works OK for properties of type *string or string but doesn't work for collections like []string or map[string]Something, because in those cases it's not the property that is the reference it's the type (or a part of the type).
The Swagger "format": "arm-id" importer already used the astmodel.ARMID type. Now the config based overrides also use the same type and work for collections.

Refactor cross resource reference config overrides

---

docs/hugo/content/design/ADR-2023-02-Adoption-Policy.md

A design for how the operator will "adopt" resources that existed in Azure before they were created in Kubernetes.

Adoption design

---

.github/workflows/ok-to-test.yml
.github/workflows/pr-validation-fork.yml

Updates the `ok-to-test` workflow and the PR workflow it triggers for updates to the `peter-evans/slash-command-dispatch` action. In the [**v2.0.0**](https://github.com/peter-evans/slash-command-dispatch/releases/tag/v2.0.0) release, the payload was altered to prevent named arguments overwriting other values.
Can't test this without merging, unfortunately. 
Please check the linked docs on the breaking change and review my changes in that context.

Fix `ok to test` workflow.

---

azure-pipelines.yml

ubuntu-latest now has Kustomize v5 by default which is what we were using before (even though we purposefully selected Kustomize v4 in our installation scripts we weren't actually using it).
This ensures that we use the pinned version of Kustomize.

Force usage of Kustomize v4 for ASOv1 build

---

scripts/v2/gen-api-docs.sh

Currently our CRD Documentation pass will abort if we try to generate documentation for a folder that contains no Go code. This can happen when we have orphan `structure.txt` files left in the project. 
I've added a check into the script to skip these folders.

Modify CRD Documentation to skip non-code folders

---

Taskfile.yml
scripts/v2/generate-helm-manifest.sh
v2/charts/azure-service-operator/values.yaml
v2/cmd/controller/app/flags.go
v2/cmd/controller/app/setup.go
v2/cmd/controller/main.go
v2/config/manager/manager.yaml
v2/internal/crdmanagement/crd_installation_instruction.go
v2/internal/crdmanagement/helpers.go
v2/internal/crdmanagement/manager.go
v2/internal/crdmanagement/manager_test.go
v2/internal/util/flags/string_slice_flags.go

Fixes #1433.
Fixes #2920.
* By default, no CRDs are installed.
* If no CRDs are installed, the operator pod will exit with an error stating that there are no CRDs.
* Operator pod --crd-pattern command-line argument will now accept more than '*'.
* --crd-pattern means NEW CRDs to install. Existing CRDs in the cluster will always be upgraded. This means that upgrading an existing ASO installation without specifying any new CRDs will upgrade all of the existing CRDs and install no new CRDs.
Documentation updates will come in a separate PR.

Allow users to configure a subset of CRDs to install

---

docs/hugo/content/guide/breaking-changes/_index.md
docs/hugo/content/guide/breaking-changes/breaking-changes-v2.1.0.md
scripts/v2/check-changes.sh
v2/README.md

Also fixes a relative link to make it absolute so it works in both the README and hugo site context.

Document v2.1.0 breaking changes

---

.github/workflows/build-devcontainer-image.yml
docs/hugo/.htmltest.yml

Previous attempt to upgrade from deprecated versions of the docker actions failed, so trying again.
It appears the _required_ use of `docker/setup-buildx-action@v2` ... isn't.
Manually tested by pushing the branch and triggering the workflow.

Fix DevContainer Builds

---

.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml
Taskfile.yml
scripts/v2/cipool/deploy.bicep
scripts/v2/cipool/deploy.sh
v2/internal/testcommon/kube_test_context_envtest.go

Use 1ES Pool for long-running CI jobs

---

v2/samples/cache/v1api/refs/v1api20201201_redis.yaml
v2/samples/cache/v1api/v1api20201201_redislinkedserver.yaml
v2/samples/cache/v1beta/v1beta20201201_redislinkedserver.yaml

Found out while scenario testing, `RedisLinkedServer` has `location` property on it which should not be there.

Fix redis samples

---

v2/internal/crdmanagement/manager.go
v2/internal/crdmanagement/manager_test.go

We were fixing up the cert-manager label when really it's an annotation that should have been fixed.
- Adds a unit test.
- Fixes #3057.

Fix bug preventing operator from installing CRDs into a different namespace

---

v2/config/manager/manager.yaml
v2/config/manager/manager_auth_proxy_patch.yaml

Specify readOnlyRootFilesystem: true and allowPrivilegeEscalation: false for extra security goodness.
Resolves #3056.

Improve pod securityContext parameters

---

Taskfile.yml
docs/operator-bundle/testing-and-releasing.md
v2/README.md

We were using 1.8.x version for cert-manager in our CI. Updating it to 1.12.1 in this PR

Update cert manager version to use latest(1.12.1)

---

v2/api/machinelearningservices/customizations/workspace_extension.go
v2/internal/controllers/crd_keyvault_test.go
v2/internal/controllers/crd_machinelearningservices_test.go
v2/internal/controllers/recordings/Test_MachineLearning_Workspaces_CRUD.yaml

If a required storage account is not yet provisioned when a `MachineLearningServices.Workspace` is deployed, that deployment will fail. We need to retry when that happens to allow `StorageAccount` provisioning to complete.
Fixes #3086 
We didn't catch this with our tests because they provisioned the `StorageAccount` first and only then attempted to provision the `Workspace` after that was complete.

Retry Workspace if storage account not ready

---

v2/tools/generator/internal/codegen/pipeline/apply_defaulter_and_validator_interfaces.go
v2/tools/generator/internal/interfaces/defaulter_interface.go

Pass default functions as an argument rather than hardcoding them. This is similar to what we're already doing for validations.

Refactor AddDefaulterInterface

---

v2/cmd/asoctl/internal/importing/importable_arm_resource.go
v2/cmd/asoctl/internal/importing/resource_importer_report.go

If a resource being imported has a fixed name, it doesn't have an AzureName property and `asoctl` was encountering a panic.
Fixes #3098 

Fix asoctl when importing resources with fixed names

---

.devcontainer/install-dependencies.sh

Currently `postcss` will always install when `dev.sh` is run, regardless of whether it's already installed or not.
Turns out it installs into different locations inside/outside the devcontainer; switching to using `which` means it should work in both cases.

Fix postcss always reinstalling

---

.devcontainer/Dockerfile
Taskfile.yml

Compresses `asoctl` for release
Closes #3102
Other minor changes
* Changes ci to run in sequence (avoiding `controller:` and `crossplane:` logs interleaving)
* Relocates some documentation related tasks (but leaves the originals for use by workflows, for now)
* Removes use of `[ foo, bar, baz ]` syntax for dependencies

Improvements to Taskfile

---

docs/hugo/content/tools/asoctl.md

With the change in v2.2.0 of using compressed archives for asoctl instead of bare executables, we need to update the installation docs.
Resolves #3108 

Update installation docs for asoctl

---

v2/api/managedidentity/v1api20220131preview/federated_identity_credential_types_gen.go
v2/api/managedidentity/v1api20220131preview/structure.txt
v2/api/managedidentity/v1api20220131preview/user_assigned_identities_federated_identity_credential_spec_arm_types_gen.go
v2/api/managedidentity/v1api20220131preview/zz_generated.deepcopy.go
v2/api/managedidentity/v1api20220131previewstorage/federated_identity_credential_types_gen.go
v2/api/managedidentity/v1api20220131previewstorage/structure.txt
v2/api/managedidentity/v1api20220131previewstorage/zz_generated.deepcopy.go
v2/api/managedidentity/v1beta20220131preview/federated_identity_credential_types_gen.go
v2/api/managedidentity/v1beta20220131preview/structure.txt
v2/api/managedidentity/v1beta20220131preview/user_assigned_identities_federated_identity_credential_spec_arm_types_gen.go
v2/api/managedidentity/v1beta20220131preview/zz_generated.deepcopy.go
v2/api/managedidentity/v1beta20220131previewstorage/federated_identity_credential_types_gen.go
v2/api/managedidentity/v1beta20220131previewstorage/structure.txt
v2/api/managedidentity/v1beta20220131previewstorage/zz_generated.deepcopy.go
v2/azure-arm.yaml
v2/internal/controllers/controller_resources_gen.go

Allows the `issuer` and `subject` properties of FederatedIdentityCredential to be set from configMaps.
Closes #3030 

Configuration of FederatedIdentityCredential 

---

v2/cmd/controller/app/setup.go

As reported in #3127, ASO upgrade fails when there are non-ASO CRDs present that use the `azure.com` suffix. We filter out for GVKs that we don't recognize.
Closes #3127

Filter against upgrading non-ASO resources

---

Taskfile.yml

The Taskfile target `controller:run-kustomize` deletes and regenerates all the `zz_generated.deepcopy.go` files, resulting in build errors for `asoctl` unless we ensure the regeneration runs first.
This PR enforces that ordering so the builds work.

Fix sequencing of asoctl builds for release

---

v2/tools/generator/internal/armconversion/convert_from_arm_function_builder.go
v2/tools/generator/internal/armconversion/convert_to_arm_function_builder.go
v2/tools/generator/internal/armconversion/shared.go

Something has been nagging at the back of my brain about this prior fix and when I stumbled across the code today, I realized what it was. It's subtle, but worth fixing.
When the `noarmconversion` tag is found on the property, we want to return an empty set of statements (`[]dst.Stmt`), because no conversion is required.
What we've actually been doing is returning _whatever set of statements the first conversion in the list happened to return_.
In practice, this has been an empty set of statements, so the code has worked, but nothing has required this to be the case. 
Put another way, the contract for `propertyConversionHandler` is:
> If I return **false**, don't use the slice of statements.
But we were.
**How …

Fix potential use of wrong statements

---

v2/cmd/asoctl/cmd/import_azure_resource.go
v2/cmd/asoctl/internal/importing/resource_import_result.go

When importing an Azure resource, we have been getting an empty status section in the output, which isn't necessary.
``` 
...
powerState:
code: Running
type: Microsoft.ContainerService/managedClusters/agentPools
vmSize: Standard_D8ds_v5
status: {}
---
Import Azure Resources  [==============================] 100 %
```
This PR redacts that wart to make things cleaner:
```
powerState:
code: Running
type: Microsoft.ContainerService/managedClusters/agentPools
vmSize: Standard_D8ds_v5
---
Import Azure Resources  [==============================] 100 %
```
Also fixes a minor bug where the output was being sent to the wrong stream, giving weird results on screen.

Redact empty status properties 

---

v2/cmd/asoctl/internal/importing/importable_arm_resource.go
v2/cmd/asoctl/internal/importing/importable_resource.go
v2/cmd/asoctl/internal/importing/resource_importer.go

During import of an Azure Resource, **asoctl** was using the name of the resource as a unique key to identity the resource. 
While these names are often unique (due to the use of GUIDs or to specific naming conventions), they aren't always unique.
In particular, some resources have hard coded names - and when those names collided, **asoctl** was incorrectly assuming the importers were identical. 
One case where this occured was during import of a Storage Account - all of the container resources within a Storage Account (for Blobs, Queues, Tables and Files) are named `default`.
This PR changes to using the full ARM ID as the unique identifier for each importer.
Fixes #3195 

Use fully qualified ARM ID to identity importers

---

scripts/v2/generate-helm-manifest.sh

Closes #3189 
This PR removes `v` from chart versions to make ASOv2 helm chart version SemVer 2 compatible.
The change is made in the `generate-helm-manifest.sh` so that the next time we release the helm chart, we'll have the helm chart version in a new format.
Tested it out and upgrades work fine :

Make helm chart version SemVer 2 compatible

---

.github/workflows/merge-queue-cla.yaml

Uses the context of the workflow run to target the 'success' indication to the SHA of the merge group.
In theory. 😁

Update to target SHA of merge group

---

v2/api/containerservice/customizations/managed_cluster_extensions.go

Treat the error `CustomKubeletIdentityMissingPermissionError` as a retryable error, to avoid a race condition where slow creation of a `UserAssignedIdentity` might cause creation of a `ManagedCluster` to fail with a permanent error.
Closes #3267 

Treat CustomKubeletIdentityMissingPermissionError as retryable

---

.github/workflows/pr-validation.yml

For security reasons, we don't want dependabot to automatically run integration builds, so I'm working on having them work with our usual `/ok-to-test` workflow that we use for PRs from outside the repo.

Disable automatic runs for dependabot

---

.github/dependabot.yml

As mentioned by @theunrepentantgeek, all Dependabot PRs automatically rebase on making changes to a Dependabot PR. Which results in loading up our CI and result in slower feedback. This PR adds in rebase-strategy to disable automatic rebase and we can manually rebase the PRs using `dependabot rebase` comment.

Disable dependabot automatic rebase

---

docs/hugo/content/guide/authentication/credential-format.md
docs/hugo/content/guide/diagnosing-problems.md
docs/hugo/content/guide/frequently-asked-questions.md

Docs improvements

---

.github/workflows/pr-validation.yml

Often the `go get` step in our CI builds will fail.
This is due to delays in the default proxy used by the `go` CLI, [specifically](https://proxy.golang.org/):
> In order to improve our services' caching and serving latencies, new versions may not show up right away. If you want new code to be immediately available in the mirror, then first make sure there is a semantically versioned tag for this revision in the underlying source repository. Then explicitly request that version via go get module@version. The new version should be available within one minute. 
Bypassing the proxy would invalidate the scenario we want to test, so I've juiced up the retries.

Update Go-Get, take II

---

v2/tools/generator/internal/astmodel/type_definition_set.go
v2/tools/generator/internal/codegen/embeddedresources/misbehaving_embedded_resources.go
v2/tools/generator/internal/codegen/embeddedresources/remover.go
v2/tools/generator/internal/codegen/embeddedresources/renamer.go
v2/tools/generator/internal/config/object_model_configuration.go

Approximately halves the length of time taken for the _Remove properties that point to embedded resources_ stage to run.
On my laptop, was 64s, now 27s.

Improve generator performance

---

v2/cmd/asoctl/go.mod
v2/cmd/asoctl/go.sum
v2/cmd/asoctl/internal/crd/cleaner.go
v2/cmd/asoctl/internal/crd/cleaner_test.go

This command will no longer work on alpha relases because we changed how the CRD listing is done (now uses label, which alpha doesn't have), but as per our metrics alpha has no more usage, and older asoctl versions will still work to clean alpha.

Update asoctl clean command to clean beta CRDs

---

.github/workflows/pr-validation.yml

I suspect the previous condition was excluding merge-queue builds for dependabot PRs, so I'm changing it.

Change triggering condition for merge queues

---

v2/cmd/controller/app/flags.go
v2/cmd/controller/app/setup.go

Allows users to customize the port and certificate directory. Aligns with Cluster API flags.

Allow to customize webhook server port and cert dir

---

.github/workflows/pr-validation.yml
azure-pipelines.yml

Setting the status of the `integration-test-fork` check requires knowing the SHA of the code we're checking.
Previously we obtained that from the pull request we're testing, which doesn't work for merge queues.
This changes the script to instead obtain the SHA from the metadata of the check we're _currently running_; this should allow us to update `integration-test-fork` regardless of the context within which we're running the checks.

Using existing check-run to obtain SHA

---

azure-pipelines.yml

Fixing the ADO triggers so that the pipeline is triggered automaticaly for GitHub merge queue checks.
I suspect the `exclude: '*'` was taking precedence over the include.

Update branch triggers for ADO

---

.devcontainer/install-dependencies.sh

This is so that even if somebody launches the container and runs it using their user identity (matching the UID/GID of the files they've mounted into the container locally) docker will still be able to find the buildx extension.

Install buildx for all container users

---

.devcontainer/install-dependencies.sh

Installing buildx under `$HOME/.docker/cli-plugins` doesn't work in the devcontainer because the installation scripts run as **root** but users usually don't run within the container as root.
But installing to `/usr/lib/docker/cli-plugins` doesn't work when running outside the container.
This PR makes the script smart enough to choose the location that works for the context.

Make installation location for buildx dynamic

---

v2/cmd/controller/app/flags.go
v2/cmd/controller/app/setup.go

Currently, there is no way to decide if the ASO manager should control all CRDs, or just use the ones already installed in the cluster without any modifications.
This PR adds a flag called `enable-crd-management`, enabled by default (to retain backward compatibility).
More information was captured in the upstream slack thread: https://kubernetes.slack.com/archives/C046DEVLAQM/p1697665840941649.

Add a flag to control CRD management

---

.devcontainer/devcontainer.json
v2/api/apimanagement/customizations/product_extensions.go
v2/internal/controllers/crd_apimanagement_20220801_test.go
v2/internal/controllers/recordings/Test_ApiManagement_20220801_CRUD.yaml

This pull request fixes two APIM issues
My previous work on APIM left a setting of `Recover: true` when creating the apim instance. This will cause an error if you were to delete the recording and not have an apim instance in a deleted state.
It would be better not to have this setting defined and allow it to error if there was a deleted APIM in your resource group - which is a smaller probability!
This would eventually be handled by having a goal seeking APIM creation #3433.
When we create an APIM Product, it creates a Subscription for that Product. This causes problems when you delete the Product; however there is a flag to pass deleteSubscriptions to true which will fix this. Override the default delete behaviour and use the go sdk to carry out the deletion. This will close #3408
**How …

APIM: Delete subscriptions when deleting products

---

docs/hugo/content/guide/uninstalling.md

Fixes incorrect documentation. 
Closes #3416

Update documentation around CRD removal

---

.github/dependabot.yml

As discussed - We're not actively releasing ASOv1 anymore, so makes sense to turn off dependabot for ASOv1 and manually update the dependencies whenever required.

Exclude ASOv1 from dependabot config

---

v2/azure-arm.yaml
v2/tools/generator/internal/codegen/pipeline/apply_export_filters.go
v2/tools/generator/internal/config/object_model_configuration.go
v2/tools/generator/internal/config/type_configuration.go

We've had the ability to rename _resources_ for some time, using `$exportAs` but that doesn't support renaming other types. This PR adds configuration and functionality to do that.
Given that `$exportAs` implies `$export: true`, I didn't want to reuse it for non-resource types; the new configuration option is `$renameTo`.
Closes #3402 
This came out of my first attempt at closing #3403 but wasn't actually used for that.

Add configuration to rename types

---

v2/cmd/asoctl/internal/crd/cleaner.go
v2/cmd/asoctl/internal/crd/cleaner_test.go
v2/pkg/genruntime/group_version_kind_aware.go

* asoctl was not removing "v1beta" usage, which was a version used for handcrafted resources such mysql user.
* The operator needs to translate beta versions into GA versions when doing ARM version conversion.

Fix bugs related to beta resource removal

---

.devcontainer/install-dependencies.sh
Taskfile.yml
docs/hugo/content/contributing/dependencies.md
docs/v2/dependencies-footer.md
docs/v2/dependencies-header.md

Adds documentation of the developer dependencies required to work on ASO if you don't want to use our devcontainer or run `install-dependencies.sh`.
Closes #3047 
Documentation is generated by scanning `install-dependencies.sh` to help ensure that it remains up to date.

Document Dependencies

---

.github/workflows/pr-validation.yml

The step `Get Job ID from GH API` is currently being skipped if any prior step fails; this causes issues with the following step because no job id is available.
This PR changes the step to always execute.

Fix for skipping job-id step in workflow

---

v2/tools/mangle-test-json/main.go
v2/tools/mangle-test-json/test_run.go

The `mangle-test-json` tool that we use to generate summaries of test results has a bug - it only lists the outcome for tests that have an explicit outcome listed in the test output.
Other tests were omitted, including:
* Tests that panic
* Tests that were paused at the time of test suite termination
* Tests that were still running at the time of test suite termination
Of these, the first (omission of tests that panic) was crucial because we had test failures where the identity of the failing test was suppressed.
Instead of tracking information about test execution and only creating a `TestRun` summary once we know the outcome of the test, we instead need to start tracking each test up front, pruning those that aren't _interesting_ once we're …

Improve test summary tool

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/pkg/genruntime/base_types.go
v2/pkg/genruntime/kubernetes_resource.go

This fixes #3398.
Note that there are no tests for this (yet), but they will come when we add the APIM resources which don't have a body (which will come in a future PR). I've already confirmed that these tests pass.

Controller should use HEAD if GET is not available

---

v2/tools/generator/internal/astmodel/allof_type.go
v2/tools/generator/internal/astmodel/allof_type_test.go
v2/tools/generator/internal/astmodel/array_type.go
v2/tools/generator/internal/astmodel/enum_type.go
v2/tools/generator/internal/astmodel/errored_type.go
v2/tools/generator/internal/astmodel/external_type_name.go
v2/tools/generator/internal/astmodel/file_definition.go
v2/tools/generator/internal/astmodel/flagged_type.go
v2/tools/generator/internal/astmodel/interface_type.go
v2/tools/generator/internal/astmodel/internal_type_name.go
v2/tools/generator/internal/astmodel/map_type.go
v2/tools/generator/internal/astmodel/object_type.go
v2/tools/generator/internal/astmodel/oneof_type.go
v2/tools/generator/internal/astmodel/oneof_type_test.go
v2/tools/generator/internal/astmodel/optional_type.go
v2/tools/generator/internal/astmodel/primitive_type.go
v2/tools/generator/internal/astmodel/resource_type.go
v2/tools/generator/internal/astmodel/type.go
v2/tools/generator/internal/astmodel/type_definition.go
v2/tools/generator/internal/astmodel/type_definition_test.go
v2/tools/generator/internal/astmodel/validated_type.go
v2/tools/generator/internal/conversions/property_bag_member_type.go

Changes `Type.AsDeclarations()` to allow for an error return, and removes use of **panic** for when things go predictably awry.
Part of a sequence of changes designed to remove the use of **panic** for errors that are expected because they can be triggered by external factors.
Closes #2969 

Allow AsDeclarations to return an error

---

v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/embeddedresources/remove_empty_objects.go
v2/tools/generator/internal/jsonast/swagger_type_extractor.go

They have a HEAD rather than a GET and no body parameters

Support resource types that aren't quite "really" resources

---

v2/tools/generator/internal/armconversion/arm_spec_interface.go
v2/tools/generator/internal/astmodel/std_references.go
v2/tools/generator/internal/codegen/pipeline/apply_defaulter_and_validator_interfaces.go
v2/tools/generator/internal/codegen/pipeline/inject_property_assignment_functions.go
v2/tools/generator/internal/functions/common.go
v2/tools/generator/internal/functions/conditions_functions.go
v2/tools/generator/internal/functions/empty_status_function.go
v2/tools/generator/internal/functions/get_resource_type_function.go
v2/tools/generator/internal/functions/get_spec_function.go
v2/tools/generator/internal/functions/get_status_function.go
v2/tools/generator/internal/functions/hub_function.go
v2/tools/generator/internal/functions/initialize_spec_function.go
v2/tools/generator/internal/functions/kubernetes_admissions_defaulter.go
v2/tools/generator/internal/functions/kubernetes_admissions_defaults.go
v2/tools/generator/internal/functions/kubernetes_admissions_validations.go
v2/tools/generator/internal/functions/kubernetes_admissions_validator.go
v2/tools/generator/internal/functions/kubernetes_exporter_function.go
v2/tools/generator/internal/functions/locatable_resource_function.go
v2/tools/generator/internal/functions/new_empty_arm_value_function.go
v2/tools/generator/internal/functions/object_function.go
v2/tools/generator/internal/functions/resource_function.go
v2/tools/generator/internal/interfaces/kubernetes_resource_interface.go

Currently the definitions of `ResourceFunctionHandler` and `ObjectFunctionHandler` have to resort to **panic** if something goes wrong; this results in the ASO generator aborting instead of returning context for the problem. 
This PR changes the signatures to allow for errors to be returned, modifying some **panic** calls into errors.
Closes #2968

Allow Function Handlers to return errors

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/resolver/resolver_test.go
v2/internal/resolver/resource_hierarchy.go
v2/internal/resolver/resource_hierarchy_test.go
v2/internal/testcommon/resource_groups.go
v2/internal/tests/azure_generic_arm_reconciler_test.go
v2/pkg/genruntime/arm_id.go
v2/test/single_operator_multitenant_test.go

Closes #3244 
Adding check to match resource credential subscription with owner's subscription.

Add guards against using distinct subscriptions between owner and child resources

---

v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/debug_reporter.go
v2/tools/generator/internal/codegen/pipeline/create_conversion_graph.go
v2/tools/generator/internal/codegen/pipeline/debug_settings.go
v2/tools/generator/internal/codegen/pipeline/pipeline_diagram.go
v2/tools/generator/internal/codegen/pipeline/stage.go
v2/tools/generator/internal/codegen/storage/conversion_graph.go
v2/tools/generator/internal/codegen/storage/conversion_graph_test.go
v2/tools/generator/internal/codegen/storage/group_conversion_graph.go
v2/tools/generator/internal/codegen/storage/property_converter.go
v2/tools/generator/internal/codegen/storage/resource_conversion_graph.go
v2/tools/generator/internal/codegen/storage/testdata/TestGolden_ConversionGraph_WhenCompatPackagePresent_HasExpectedTransitions.golden

Extends the debug mode of the code generator (triggered by using the `--debug` command line option) so that our conversion graphs are also exported for review.
The graphs are exported in GraphViz `dot` format, suitable for dropping into [GraphViz Online](https://dreampuf.github.io/GraphvizOnline) or for local use.
Sample output:
``` dot
graph G {
rankdir=LR;
subgraph apiversions {
rank=same;
node [shape=ellipse, style=dashed, penwidth=1, rankType=min, group=storage];
"v20210501";
"v20230201";
"v20230202p";
}
subgraph storageversions {
rank=same;
node [shape=ellipse, style=dashed, penwidth=1, rankType=min, group=storage];
"v20210501s";
"v20230201s";
"v20230202ps";
}
edge [arrowhead=vee, arrowtail=vee, dir=forward];
v20210501 -- v20210501s
v20210501s …
```

Extend generator debug mode to export our conversion graphs

---

v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/pkg/common/annotations/annotations.go
v2/pkg/common/labels/labels.go
v2/pkg/genruntime/base_types.go

Closes #3190 
This PR enables controller to add `serviceoperator.azure.com/owner-name: <OwnerName>` label at the time of adding the initial resource state

Add owner-name label on resources

---

v2/internal/resolver/resolver.go
v2/internal/resolver/resolver_test.go

Closes #3019 
This PR adds validation to `ResolveReference` method to catch if the name provided is an armID and output an error message with suggestion. 

Improve validation to catch use of armID as name

---

v2/tools/generator/internal/astmodel/kubebuilder_validations.go
v2/tools/generator/internal/astmodel/validated_type.go
v2/tools/generator/internal/codegen/testdata/Validations/Validate_property_type.golden
v2/tools/generator/internal/codegen/testdata/Validations/Validate_property_type.json
v2/tools/generator/internal/jsonast/jsonast.go

We've had this implemented for a long time, and have never used it before.
During import of a new version of ManagedCluster (see #3629), I got this error during testing:
```
Forbidden: uniqueItems cannot be set to true since the runtime complexity becomes quadratic
```
Turns out this potential validation is now [forbidden by Kubernetes](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/):
> The field uniqueItems cannot be set to true.
Since we can't use it, I'm removing it from the generator.

Remove generation of UniqueItems validation

---

v2/internal/controllers/README.md

Currently almost every CRD test file under `controllers` has the prefix `crd_` which is just noise. File naming is inconsistent, making it harder to find tests.
This PR documents a desired convention, towards which we can move once agreed.
I (@theunrepentantgeek) had a go at this a while ago, but my ideas weren't fully baked, so we didn't progress at that time.

Document naming convention for CRD tests

---

docs/hugo/content/design/ADR-2022-09-Reading-Status-Properties-Of-Resources.md

Minor fix for docs link reference for `Taskfile` project

Fix docs link

---

scripts/v2/build_version.py

Point to most specific content to resolve shallow clones of repos, for example a GitHub Codespace.
Happy to replace the existing link.

docs: Link to repo health when shallow clone is used

---

.devcontainer/install-dependencies.sh

This should be safe given Go's compatibility guarantees and it makes using ASO easier with dev.sh and other Go projects which may have moved to a newer Go version before we did easier.

Allow newer versions of Go than we require in dev.sh

---

.devcontainer/Dockerfile
.devcontainer/install-dependencies.sh
.devcontainer/library-scripts/docker-debian.sh
Taskfile.yml
docs/hugo/content/contributing/dependencies.md
docs/hugo/content/contributing/developer-setup.md
hack/crossplane/.gitignore
hack/crossplane/config/default/kustomization.yaml

- This PR fixes issues with packages for ARM64 architecture
- Updates `azwi` as macOS arm64 support has been introduced starting version 1.1.0
- Formats documentation

Contributing: arm64 support

---

v2/api/kubernetesconfiguration/v1api20230501/extension_spec_arm_types_gen.go
v2/api/kubernetesconfiguration/v1api20230501/extension_spec_arm_types_gen_test.go
v2/api/kubernetesconfiguration/v1api20230501/extension_status_arm_types_gen.go
v2/api/kubernetesconfiguration/v1api20230501/extension_status_arm_types_gen_test.go
v2/api/kubernetesconfiguration/v1api20230501/extension_types_gen.go
v2/api/kubernetesconfiguration/v1api20230501/extension_types_gen_test.go
v2/api/kubernetesconfiguration/v1api20230501/storage/extension_types_gen.go
v2/api/kubernetesconfiguration/v1api20230501/storage/extension_types_gen_test.go
v2/api/kubernetesconfiguration/v1api20230501/storage/structure.txt
v2/api/kubernetesconfiguration/v1api20230501/storage/zz_generated.deepcopy.go
v2/api/kubernetesconfiguration/v1api20230501/structure.txt
v2/api/kubernetesconfiguration/v1api20230501/zz_generated.deepcopy.go
v2/azure-arm.yaml
v2/internal/controllers/controller_resources_gen.go
v2/internal/controllers/crd_kubernetesconfiguration_extension_test.go
v2/internal/controllers/recordings/Test_KubernetesConfiguration_Extension_ProtectedSettings.yaml

Add ConfigurationProtectedSettings to extensions resource

---

v2/internal/controllers/samples_test.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/samples_tester.go

* This has the advantage of the sample being clearer to users, although it does involve having secrets committed in the repo. I think this is OK for two reasons:
* The resources in question aren't durably created and exist for sample purposes only.
* For SecretMapReference, it will not be possible for the test infrastructure to generate the secret, as it doesn't understand the expected payload of the map (what keys should be set).
As part of this change, slightly harden the test helper functions to do the right thing if passed a non-ASO resource (so they don't try to monitor it's Ready condition)
Note: This just enables the capability in the framework, we can still choose to ask PRs to mostly use the secret-autogeneration function if we want to.
**If …

Allow samples with a hardcoded secret rather than an autogenerated one

---

scripts/v2/generate-helm-manifest.sh
v2/charts/azure-service-operator/values.yaml

Closes #3646 
This PR adds changes to the helm chart generation script to add `Affinity` and `Tolerations` to ASOv2 helm chart. Also updates `values.yaml` to specify the above.

Add affinity and tolerations to ASOv2 helm chart

---

v2/tools/generator/internal/astmodel/local_package_reference.go
v2/tools/generator/internal/astmodel/local_package_reference_test.go

Fix local package aliases with "." in them

---

v2/tools/generator/internal/astmodel/object_type.go
v2/tools/generator/internal/conversions/property_conversions.go

If a property conversion strategy needs a specific package referenced, that package needs to be added into the provided `propertyConversionContext`.
Our hand-crafted conversions weren't doing this - which was fine as long as those conversions only used packages already referenced, but as soon as one of them needed a new package, we started getting errors during the code generation phase of our generator.
Fix is to ensure all of the packages required by the conversion are explicitly included - the references are set based, so there's no downside to adding the same one multiple times.

Hand-crafted conversions need to add package references

---

v2/tools/generator/internal/codegen/pipeline/load_types.go

As the number of OpenAPI spec files to load grows, performance of the generator is gradually slowing.
Currently, on `main` we're loading 10305 distinct files.
In this PR, we avoid loading _some_ files we know we don't need, loading just 6556 files (a 36% reduction).
We're conservative about what we skip, there's probably scope to be more aggressive.

Reduce the number of types loaded by the generator

---

v2/pkg/genruntime/conditions/conditions.go
v2/pkg/genruntime/conditions/conditions_test.go

This fixes #3788.
AzureResourceNotFound only comes up when ReconcilePolicy is skip. This conditions priority being less than Reconciling allows skip -> reconcile to immediately update the condition to Reconciling rather than continuing to report AzureResourceNotFound until the resource is created.

Ensure reconciling condition overwrites AzureResourceNotFound

---

docs/hugo/content/design/ADR-2022-11-Resource-Import.md

ASO v1 uses the annotation `skipreconcile` to skip reconciliation, and the use of `skip-reconcile` in this ADR was interpreted as documentation of the way ASO v2 worked with a similar annotation, when this is not the case. ASO v2 uses the annotation `serviceoperator.azure.com/reconcile-policy` instead.
I've rephrased the wording to avoid this confusion
According to `git grep` there are no other ocurrences of `skip-reconcile` in the repo.

Avoid phrasing that looks like an annotation

---

v2/cmd/asoctl/internal/importing/find_group_kind.go
v2/cmd/asoctl/internal/importing/importable_arm_resource.go
v2/cmd/asoctl/internal/importing/importable_arm_resource_test.go

Caused by case-mismatch in Azure reported resource type.

Fix panic in asoctl

---

Taskfile.yml
scripts/v2/wait-for-operator-ready.sh

Closes #3715 
The above issue was for ASO beta.5 version and does is not true for current version. As a part of this PR, have modified a multitenant test to confirm ASO works fine in other namespaces as well.

Modify multitenant test to install operator in custom namespace

---

v2/api/operationalinsights/v1api20210601/structure.txt
v2/api/operationalinsights/v1api20210601/workspace_spec_arm_types_gen_test.go
v2/api/operationalinsights/v1api20210601/workspace_status_arm_types_gen_test.go
v2/api/operationalinsights/v1api20210601/workspace_types_gen.go
v2/api/operationalinsights/v1api20210601/workspace_types_gen_test.go
v2/tools/generator/internal/astmodel/enum_type.go

Ordering tweak for declarations of enumerations with an integer base, listing them in order of magnitude instead of alphabetically.

Order numeric enums by magnitude

---

v2/tools/generator/internal/astbuilder/builder.go
v2/tools/generator/internal/astbuilder/declarations.go
v2/tools/generator/internal/astbuilder/statements.go
v2/tools/generator/internal/astmodel/interface_implementer.go
v2/tools/generator/internal/astmodel/object_type.go
v2/tools/generator/internal/astmodel/resource_type.go

The method `InterfaceImplementer.AsDeclarations()` had a panic stemming from the fact that we previously couldn't return the error; thanks to other tech-debt cleanup, we now can.
**CoPilot Summary**
This pull request includes changes to the `v2/tools/generator/internal/astmodel` package to enhance error handling and code readability. The most important changes include the addition of a new `Declarations` function, modification of the `import` statement, changes to the `AsDeclarations` function in multiple files to include error returns and use the new `Declarations` function, and improvements in error messages.
Addition of new function:
* [`v2/tools/generator/internal/astbuilder/declarations.go`](diffhunk://#diff-d …

Eliminate panic in InterfaceImplementer AsDeclarations()

---

v2/cmd/asoctl/cmd/import_azure_resource.go
v2/cmd/asoctl/internal/importing/resource_import_result.go
v2/internal/annotations/parse.go
v2/internal/annotations/parse_test.go
v2/internal/labels/parse.go
v2/internal/labels/parse_test.go

Add namespace, label, and annotation support to asoctl

---

.devcontainer/Dockerfile
.devcontainer/install-dependencies.sh
.github/workflows/pr-validation.yml
Dockerfile
Taskfile.yml
azure-pipelines.yml
docs/hugo/content/contributing/dependencies.md
v2/Dockerfile
v2/cmd/asoctl/go.mod
v2/go.mod
v2/tools/generator/go.mod
v2/tools/generator/internal/astbuilder/statements.go

This was required as setup-envtest@latest no longer works with Go versions less than 1.22.
controller-tools was also updated as it panics if 0.13.0 is used with Go 1.22. 0.14.0 must be used instead.
Go version also moved to 1.21 to comply with new mod shape.

Update Go version

---

v2/api/containerservice/v1api20230315preview/fleets_update_run_spec_arm_types_gen.go
v2/api/containerservice/v1api20230315preview/fleets_update_run_status_arm_types_gen.go
v2/api/containerservice/v1api20230315preview/fleets_update_run_types_gen.go
v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/pipeline/collapse_cross_group_refs.go

Fix a bug where Fleet + AKS had a type name with a different shape that collided.

Update Swagger submodule to latest

---

v2/tools/generator/internal/astmodel/test_case.go
v2/tools/generator/internal/astmodel/test_case_test.go
v2/tools/generator/internal/astmodel/test_file_definition.go
v2/tools/generator/internal/testcases/json_serialization_test_case.go
v2/tools/generator/internal/testcases/property_assignment_test_case.go
v2/tools/generator/internal/testcases/resource_conversion_test_case.go

While working on #2970 I discovered a need to change the signature of `TestCase.AsFuncs` - and this change can be nicely isolated.
Future changes will result in errors being returned; at the moment, they're all **nil** returns.

Improve signature of TestCase.AsFuncs

---

v2/internal/testcommon/creds/creds.go
v2/internal/testcommon/kube_per_test_context.go
v2/internal/testcommon/vcr/redact.go
v2/internal/testcommon/vcr/v1/error_translating_roundtripper.go
v2/internal/testcommon/vcr/v1/test_replayer.go
v2/internal/testcommon/vcr/v3/error_translating_roundtripper.go
v2/internal/testcommon/vcr/v3/replay_roundtripper.go
v2/internal/testcommon/vcr/v3/replay_roundtripper_test.go
v2/internal/testcommon/vcr/v3/test_recorder.go
v2/internal/testcommon/vcr/v3/tracking_roundtripper.go

Fix bug where interaction.Request.RequestURI was used when interaction.Request.URL should have been used. RequestURI seems to always be empty.
Fix bug where body hashes were computed before subscriptionID and other Azure IDs were redacted, resulting in a hash that doesn't match the body that was eventually recorded (that body had these values redacted).
This issue only showed up for requests that contained ARM IDs in the body which is why we didn't notice it before.
The issue here was that there are two contexts that use the vcr/redact.go helpers, one during replay and one
during recording. For replay, there's no need to redact subID because we set it to 0000's, but during recording (such as when we compute the body hash header) we need to redact the subids first.

Fix v3 recording infrastructure

---

Taskfile.yml
docs/hugo/content/_index.md
docs/hugo/content/guide/asov1-asov2-migration/_index.md
docs/hugo/content/guide/asov1-asov2-migration/azuresql.md
docs/hugo/content/guide/asov1-asov2-migration/databaseusers.md
docs/hugo/content/guide/asov1-asov2-migration/eventhub.md
docs/hugo/content/guide/asov1-asov2-migration/mysql.md
docs/hugo/content/guide/asov1-asov2-migration/postgresql.md
docs/hugo/content/guide/asov1-asov2-migration/redis.md
docs/hugo/content/guide/asov1-asov2-migration/storage.md
docs/hugo/content/guide/asov1-asov2-migration/storagecontainer.md
docs/hugo/content/guide/uninstalling.md
docs/hugo/content/tools/asoctl.md
docs/operator-bundle/testing-and-releasing.md
v2/README.md

Add ASOv1 to ASOv2 migration guide

---

docs/hugo/content/contributing/_index.md
docs/hugo/content/contributing/add-a-new-code-generated-resource.md
docs/hugo/content/contributing/running-a-development-version.md
docs/hugo/content/contributing/testing.md
docs/hugo/content/guide/diagnosing-problems.md

* Add new entry to diagnosing problems page about ASO pod restarts due to crdPattern.
* Add entry on how to run ASO on an AKS cluster using the task command we have for that.

Improve docs

---

v2/internal/testcommon/vcr/v3/test_recorder.go
v2/internal/testcommon/vcr/v3/tracking_roundtripper.go

Use of the replaying-roundtripper was consuming attempt numbers, causing mismatches where an interaction in the recording file wouldn't be picked up because it didn't have the expected attempt header (e.g. the recording had an unused _attempt 2_ header, when the matcher was looking for an _attempt 3_ header.)
This seems to only impact on PUT request recordings.

Fix replay bug with go-vcr v3

---

v2/internal/controllers/edge_case_test.go
v2/internal/controllers/recordings/Test_CreateCosmosAccountWithSkipReconcile_SecretsAreWritten.yaml
v2/pkg/genruntime/configmaps/collector.go
v2/pkg/genruntime/configmaps/collector_test.go
v2/pkg/genruntime/secrets/collector.go
v2/pkg/genruntime/secrets/collector_test.go
v2/samples/machinelearningservices/v1api/v1api20210701_workspace.yaml

If the user requests a particular secret or configmap value be written, we should error if we are unable to write it and retry.

Fix bug where we could fail to emit user requested secrets or configmaps

---

docs/hugo/content/_index.md
docs/hugo/content/guide/_index.md
docs/hugo/content/guide/asov1-asov2-migration/_index.md
docs/hugo/content/guide/asov1-asov2-migration/storage.md
docs/hugo/content/guide/authentication/_index.md
docs/hugo/content/guide/authentication/credential-scope.md
docs/hugo/content/guide/best-practices/_index.md
docs/hugo/content/guide/best-practices/security.md
docs/hugo/content/guide/frequently-asked-questions.md

* Added general and security best practices sections.
* Updated FAQ to discuss CVE patching.
* Moved to use more visible warnings/notes in ASOv1 -> ASOv2 migration
guide.
This fixes https://github.com/Azure/azure-service-operator/issues/3261.

Add best practices documentation and update other docs

---

.devcontainer/Dockerfile

We previously were manually making node v18 available because only v12 was available from standard sources; we now have v18 directly available, so the prior workaround is not required.
I suspect this may have been the underlying cause of the problems I was experiencing with reloads of the devcontainer.

Use NPM from standard source

---

v2/internal/controllers/edge_case_test.go
v2/internal/controllers/operatormode_test.go
v2/internal/controllers/targetnamespace_test.go
v2/internal/controllers/to_azure_configmaps_test.go
v2/internal/controllers/to_azure_secrets_test.go
v2/internal/testcommon/kube_per_test_context.go

- Remove unneeded CreateResourceGroup test helpers in favor of the existing CreateResource helpers (which are identical).
- Fix test to actually use the namespace it created.

Fix a few small test issues

---

v2/config/manager/manager_image_patch.yaml

The `AZURE_USER_AGENT_SUFFIX` field in the aso-controller-settings Secret added in #3650 was not being read because the controller Pod wasn't setting the environment variable for it in its definition.

fix AZURE_USER_AGENT_SUFFIX not getting set

---

README.md
azure-pipelines.yml

Disable ASOv1 CI and clarify documentation surrounding it

---

docs/hugo/content/tools/asoctl.md
v2/cmd/asoctl/cmd/import_azure_resource.go

This fixes #4032.
Also improve the asoctl documentation

Support multiple clouds in asoctl

---

docs/hugo/content/guide/aso-controller-settings-options.md
v2/charts/azure-service-operator/values.yaml
v2/internal/config/vars.go
v2/internal/config/vars_internal_test.go
v2/pkg/common/config/config.go

This fixes #3965.
This is technically breaking but seems unlikely to break many folks.

Use "never" rather than "" to mean "don't sync" for AZURE_SYNC_PERIOD.

---

docs/hugo/content/design/ADR-2024-05-OperatorSpec-Custom-Properties/_index.md
docs/hugo/content/design/_index.md

Outlines potential approaches for adding additional properties to the `operatorSpec` for a resource, allowing additional fine control by ASO.
Inspired by conversations about #3935 

ADR to add custom operatorspec properties

---

Taskfile.yml
scripts/v2/create-kind-wi-storage.sh

This PR fixes the TaskFile's `controller:test-upgrade-apply-prerelease-chart` target to replace the old target `controller:gen-helm-manifest` to `controller:package-helm-manifest`
Also, fixes `create-kind-wi-storage.sh` to set --allow-blob-public-access==false for StorageAccount creation.

Fix pre-release-test task target

---

v2/api/keyvault/customizations/vault_extensions.go
v2/internal/controllers/keyvault_goalseekingcreation_test.go
v2/internal/controllers/recordings/Test_KeyVault_CreateOrRecover_FailsWhenRecoveringKeyVaultInDifferentResourceGroup.yaml
v2/internal/controllers/recordings/Test_KeyVault_OwnerIsARMID_RecoversSuccessfully.yaml

Fixes #4117.
Also fix an issue where we gave a confusing and non-fatal error when attempting to recover a KeyVault in a different ResourceGroup than it was originally in. Changed the error to be clearer and also immediately fatal so that no retries happen.

Fix bug where KeyVault with ARMID owner can't be recovered

---

.github/dependabot.yml

This should avoid the issues we've had in the past with dependencies between /v2 and /v2/cmd/asoctl requiring merges in a certain order.

Group updates from all 3 packages into a single dependabot PR

---

Taskfile.yml
docs/hugo/content/contributing/create-a-new-release.md

Fix documentation for creating a new release

---

Dockerfile
Taskfile.yml
v2/Dockerfile

Also fix unrelated warning from Dockerfiles for using FROM and as with different cases.

Fix issue with aks-create Taskfile target failing due to no specified DOCKER_REGISTRY

---

v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/pipeline/add_kubernetes_exporter.go
v2/tools/generator/internal/codegen/pipeline/add_operator_spec.go
v2/tools/generator/internal/codegen/pipeline/catalog_known_resources.go
v2/tools/generator/internal/codegen/pipeline/create_conversion_graph.go
v2/tools/generator/internal/codegen/pipeline/create_conversion_graph_test.go
v2/tools/generator/internal/codegen/pipeline/implement_convertible_interface.go
v2/tools/generator/internal/codegen/pipeline/implement_importable_resource_interface.go
v2/tools/generator/internal/codegen/pipeline/inject_property_assignment_functions.go
v2/tools/generator/internal/codegen/pipeline/inject_spec_initialization_functions.go
v2/tools/generator/internal/codegen/pipeline/mark_latest_storage_variant_as_hub_version.go
v2/tools/generator/internal/codegen/pipeline/repair_skipping_properties.go
v2/tools/generator/internal/codegen/pipeline/state.go
v2/tools/generator/internal/codegen/pipeline/state_test.go
v2/tools/generator/internal/codegen/testdata/TestGolden_NewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewCrossplaneCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewTestCodeGeneratorCreatesRightPipeline.golden

To produce a report listing supported resources that need upgrading, we first need to have a catalog of all known resources.
In this PR we add that catalog to our pipeline state, unblocking the future report.
As this is the _third_ piece of specialized (non-global) data that we need to store in the state, I've switched up the storage to a more generic approach where we don't need to make extensive customizations to `State` as new data needs are identified.

Catalog all known resources, regardless of whether ASO exports them

---

docs/hugo/content/design/ADR-(YEAR)-(MONTH)-(TITLE).md
docs/hugo/content/design/_index.md

Not sure if this is super useful or not, but I thought it might be so here it is.

Add an ADR template

---

v2/cmd/controller/app/setup.go
v2/internal/controllers/controller_resources.go
v2/internal/crdmanagement/helpers.go
v2/internal/crdmanagement/helpers_test.go
v2/internal/crdmanagement/manager.go
v2/internal/crdmanagement/manager_test.go

This happened because in 'none' mode goalCRDs was the set of installed CRDs, but we built an exclusion list from that set and used it to filter the set of known storage types from the scheme. When count(existing) = 5 and count(scheme)=200, the most you can possibly filter from the scheme with an exclusion list is 5 which leaves 195 CRDs being mistakenly installed.
Fixes #4146.

Fix bug where 'none' crd-management mode blocked pod start

---

docs/hugo/content/design/ADR-2024-07-Dynamic-Export-To-Secret-Or-ConfigMap.md

Add Design for Dynamic export of ConfigMap/Secret values

---

docs/hugo/content/design/ADR-2024-04-RoleAssignment-UUID-Generation.md

This PR adds ADR for RoleAssignment UUID clashes. ADR discusses about the issue with UUID clashes for RoleAssignment mentioned in #3637. 

Add RoleAssignment UUID Generation ADR

---

v2/tools/generator/internal/astmodel/interface_implementer.go

Fix InterfaceImplementer ordering if interfaces have same name

---

v2/api/authorization/v1api20200801preview/role_assignment_spec_arm_types_gen.go
v2/api/authorization/v1api20200801preview/role_assignment_types_gen.go
v2/api/authorization/v1api20200801preview/role_assignment_types_gen_test.go
v2/api/authorization/v1api20200801preview/storage/role_assignment_types_gen.go
v2/api/authorization/v1api20200801preview/storage/role_assignment_types_gen_test.go
v2/api/authorization/v1api20200801preview/storage/structure.txt
v2/api/authorization/v1api20200801preview/storage/zz_generated.deepcopy.go
v2/api/authorization/v1api20200801preview/structure.txt
v2/api/authorization/v1api20200801preview/zz_generated.deepcopy.go
v2/api/authorization/v1api20220401/role_assignment_spec_arm_types_gen.go
v2/api/authorization/v1api20220401/role_assignment_types_gen.go
v2/api/authorization/v1api20220401/role_assignment_types_gen_test.go
v2/api/authorization/v1api20220401/storage/role_assignment_types_gen.go
v2/api/authorization/v1api20220401/storage/role_assignment_types_gen_test.go
v2/api/authorization/v1api20220401/storage/structure.txt
v2/api/authorization/v1api20220401/storage/zz_generated.deepcopy.go
v2/api/authorization/v1api20220401/structure.txt
v2/api/authorization/v1api20220401/zz_generated.deepcopy.go
v2/azure-arm.yaml

The type of `RoleAssignmentProperties.DelegatedManagedIdentityResourceId` is wrong; this PR fixes it.
Closes #3831
This is a breaking change - any existing uses of `RoleAssignment` that use `DelegatedManagedIdentityResourceId` will need to be deleted and recreated. Existing uses of `RoleAssignment` that don't use that property are unaffected. 
The property `DelegatedManagedIdentityResourceId` is fairly esoteric, but we haven't found a way to confirm whether it is used or not.

Fix the type of DelegatedManagedIdentityResourceId 

---

v2/test/owner_arm_id_test.go
v2/test/private_endpoint_test.go
v2/test/single_operator_multitenant_test.go
v2/test/storage_write_secret_test.go

Storage Account public access has been disallowed and is default set to `AllowPublicAccess==true` in older api versions. Hence, replacing the old API version with new one `v1api20230101`.

Use latest version of Storage api in kind tests

---

v2/internal/controllers/crd_redhatopenshift_openshiftcluster_20230401_test.go
v2/internal/testcommon/resource_namer.go

Updating rune values for secret generation to remove `&` as it gets recorded in the response body as unicode `\u0026` which results in mis match while redacting the secrets. 
This was found in CI run [here](https://github.com/Azure/azure-service-operator/actions/runs/10480765442/job/29028989632?pr=4203)
Added a few more rune values `-`, `_` and `.` which are allowed in passwords/secrets.

Update secret generation rune values

---

Taskfile.yml

Adding a DIR override to some tarets so we can point them at the AKS directory rather than the default KIND directory, in case we want to run the tests against an AKS cluster.

Make testing on an AKS cluster a bit easier

---

.github/workflows/api-docs-repo.yaml
.github/workflows/deploy-site.yml
.github/workflows/helm-chart-repo.yaml
.github/workflows/ok-to-test.yml
.github/workflows/visualize-repo.yml
docs/hugo/content/contributing/testing.md

Switches from use of GH_PAT for authentication in our workflows to use of our new GitHub App, `azure-service-operator-automation`.
Workflows tested manually: 
* Generate CRD docs ✅ [Passed](https://github.com/Azure/azure-service-operator/actions/runs/10569804539/job/29283244390)
* Render Source Visualizations ✅ [Passed](https://github.com/Azure/azure-service-operator/actions/runs/10478268721)
Other workflows will need to be checked post merge.
Closes #3907 

Create app-token and use instead of GH_PAT

---

v2/charts/azure-service-operator/templates/_helpers.tpl
v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_azureserviceoperator-crd-manager-rolebinding.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_azureserviceoperator-crd-reader-rolebinding.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_azureserviceoperator-manager-rolebinding.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_rolebinding_azureserviceoperator-leader-election-rolebinding.yaml
v2/charts/azure-service-operator/templates/v1_serviceaccount_azureserviceoperator-default.yaml
v2/charts/azure-service-operator/values.yaml

Allows to use existing service account and/or control the name of the created service account so that prerequisites (like federated identity setup) could be successfully passed during deployment without hardcoding service account name used in the chart.

feat(helm): allow to use existing service account

---

.github/workflows/add-needs-triage-label.yml
.github/workflows/api-docs-repo.yaml
.github/workflows/build-devcontainer-image.yml
.github/workflows/codeql.yml
.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml
.github/workflows/deploy-site.yml
.github/workflows/helm-chart-repo.yaml
.github/workflows/live-validation.yml
.github/workflows/pr-validation-docs.yml
.github/workflows/pr-validation-fork.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml
.github/workflows/scan-controller-image.yaml
.github/workflows/visualize-repo.yml

GitHub has deprecated use of Node 16 and has started [forcing actions to run on Node 20](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/) instead.
Warnings are generated for workflows using old versions of actions:
```
The following actions use a deprecated Node.js version and will be forced to run on node20: 
actions/checkout@v3, docker/login-action@v2, actions/github-script@v6. 
For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
This PR updates versions of actions to the latest versions, pinned via commit-id as recommended.

Update Action step versions

---

v2/cmd/controller/app/flags.go
v2/cmd/controller/app/setup.go
v2/cmd/controller/logging/logging.go
v2/cmd/controller/main.go
v2/go.mod
v2/go.sum
v2/internal/controllers/suite_test.go
v2/internal/genericarmclient/suite_test.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/pkg/genruntime/test/suite_test.go
v2/test/multitenant/suite_test.go
v2/test/pre-release/suite_test.go
v2/test/suite_test.go

Refactors the startup of our controller to separate log initialization from app initialization. 
Removes use of the deprecated `klogr` library in favour of `textlogger`.
Introduces the new commandline flag `--json-logging` which switches the output in the obvious way.
The package `k8s.io/klog/v2/klogr` is deprecated in favour of `k8s.io/klog/v2/textlogger` so we need to switch to that.
Closes #4191 
Adding JSON logging as an option (by specifying `--json-logging` on the command line) enables better integration with structured logging tools.
Closes #1620 
By using `zap` for JSON formatted logging, we get stack traces included in the logs by default.
Closes #3529 
Tested manually on the command line.

Upgrade controller logging

---

docs/hugo/content/guide/authentication/credential-format.md

This PR documents how to use ASO with a Managed Identity without using AAD Pod Identity. I've found that this case already works without any changes to ASO, and we (CAPZ) would like to have this case be documented.
These docs are essentially copy-paste from the current Managed Identity section with the AAD Pod Identity steps removed and with the added pre-req that ASO is running on Azure infra.
I haven't tried rendering this locally yet to make sure I didn't make any obvious mistakes in the formatting, but that's what I'm doing next.
cc @dtzar

add docs for non-podidentity managed identity

---

.github/dependabot.yml

It seems to cause the job to time out, probably scanning the embedded submodule or all of our generated code directories for more go.mod's. Instead just list the 3 we have explicitly.

Don't use globbing for dependabot

---

v2/internal/reconcilers/common.go

Fixes some pancis I noticed in logs. The panics were captured so no crashes of the operator occurred but it's still not ideal.

Fix panic in log

---

docs/hugo/content/tools/asoctl.md
v2/cmd/asoctl/cmd/export_template.go

When using `asoctl export template` the values passed for `--crd-pattern` aren't currently checked at all, so they might not do what the user wants.
Closes #3969 
Validation is done against the CRDs known to that version of `asoctl`, which might be different to the `--version` specified on the command-line. Not sure how to handle this - we should discuss.

Add some validation of crd-pattern to asoctl export template

---

v2/cmd/asoctl/internal/importing/importable_arm_resource.go
v2/cmd/asoctl/internal/importing/importable_arm_resource_test.go

Modifies resources names pulled from Azure to make them valid names for Kubernetes Resources.
Closes #4156 
Closes #4153 

Ensure resource names are always K8s compliant

---

v2/api/authorization/customizations/role_assignment_extensions.go
v2/api/authorization/customizations/role_definition_extensions.go
v2/api/dbforpostgresql/customizations/flexible_servers_configuration_extensions.go
v2/api/dbforpostgresql/customizations/flexible_servers_database_extensions.go

They can't be created by ASO because they'd conflict - they're built in, so already present.
`asoctl` shouldn't include built in role definitions in the output.

Built-in role definitions should be skiped by asoctl

---

docs/hugo/content/tools/asoctl.md
v2/cmd/asoctl/cmd/import_azure_resource.go
v2/cmd/asoctl/pkg/importresources/resource_importer.go

Does what it says on the box: makes the number of concurrent workers configurable. 
More workers can make the import process complete more quickly - but not in all cases. 
The default of 4 seems to be a good compromise, ensuring a single slow resource doesn't stall the entire process too much. Making this configurable gives consumers more control when required.
Closes #4251

Allow number of simultaneous workers to be configured

---

v2/cmd/asoctl/pkg/importresources/find_child_resources.go
v2/cmd/asoctl/pkg/importresources/find_child_resources_test.go
v2/cmd/asoctl/pkg/importresources/importable_arm_resource.go
v2/cmd/asoctl/pkg/importresources/importable_arm_resource_test.go

When scanning for child/extension resources in the `cdn` group, `asoctl` runs into a `NoRegisteredProviderFound` error which is incorrectly treated as a fatal error. 
Changing this to a known case, where we simply skip the check for that particular kind of child resource, results in the import working correctly.
Closes #4260 

Allow importing of FrontDoor resources

---

docs/hugo/content/guide/metrics.md
v2/internal/metrics/arm_client_metrics.go

Add some additional documentation about metrics

---

v2/cmd/asoctl/cmd/import_azure_resource.go
v2/cmd/asoctl/cmd/log.go
v2/cmd/asoctl/pkg/importreporter/bar.go

Fixes a deadlock bug that occurs if an error is returned before the first progressbar is created.
Fixes a UX bug where completed progress bars are left on screen as debris.

Fix deadlock and ux bugs in asoctl

---

v2/api/dbforpostgresql/customizations/flexible_servers_configuration_extensions.go

When importing a PostgreSQL Flexible Server, `asoctl` was including more than 400 configuration options, many of which couldn't be changed by the user.
With this PR, we now
* Skip configurations that haven't been changed from their default
* Skip configurations marked readonly that the user cannot modify
Closes #4278

Reduce noise when importing PostgreSQL Flexible Server Configurations

---

pkg/resourcemanager/autorest/authorization_helpers.go

The Azure Storage Emulator was used by ASOv1 for testing; it requires a fixed account name and key (as [documented](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-emulator#authorize-with-shared-key-credentials))  for use. 
Adding documentation of this so that any future reviewers are aware that any apparent security breach is not actually the case.

Document origin of key for the Azure Storage Emulator

---

v2/api/dbformysql/customizations/flexible_servers_configuration_extensions.go
v2/api/dbforpostgresql/customizations/flexible_servers_configuration_extensions.go
v2/api/dbforpostgresql/customizations/flexible_servers_database_extensions.go

When importing a MySQL Flexible Server, `asoctl` was including 450 configuration options, including both default values that hadn't been changed by the user, and readonly values that cannot be changed by the user.
Similar to #4279 

Reduce noise when importing MySQL Flexible Server Configurations

---

v2/charts/azure-service-operator/templates/networkpolicies.yaml
v2/charts/azure-service-operator/values.yaml

Closes #4225 
Expose port `1433` in ASO's Network policies for SQL server user creation.

Update ASO's NetworkPolicy to allow egress to SqlServer's default port

---

docs/hugo/content/guide/asov1-asov2-migration/redis.md

https://azure.github.io/azure-service-operator/reference/cache/v1api20230401/#cache.azure.com/v1api20230401.Redis It should definitely be 'secondaryKey' not key1

Update redis migration docs with correct redis key

---

v2/tools/generator/internal/astmodel/object_type_test.go
v2/tools/generator/internal/astmodel/property_remover.go
v2/tools/generator/internal/astmodel/property_remover_test.go
v2/tools/generator/internal/astmodel/readonly_object_type.go
v2/tools/generator/internal/astmodel/type_definition_set.go
v2/tools/generator/internal/codegen/pipeline/apply_kubernetes_resource_interface.go
v2/tools/generator/internal/codegen/pipeline/create_arm_types.go
v2/tools/generator/internal/codegen/pipeline/determine_resource_ownership.go
v2/tools/generator/internal/interfaces/kubernetes_resource_interface.go
v2/tools/generator/internal/interfaces/validator_interface.go

While convenience functions like `AsObjectType()` and `AsResourceType()` are, well, convenient, they can cause issues if the results are then used to create new types - because they will strip out and discard type structure information that should be retained.
While troubleshooting issues related to import of the `kusto` group of resources, we discovered a couple places where this was happening, resulting in issues. This PR addresses those issues.
Once merged, @super-harsh should be able to merge the changes into their working branch.

Improve Type manipulation

---

v2/api/dbforpostgresql/v1api20221201/flexible_server_spec_arm_types_gen.go
v2/api/dbforpostgresql/v1api20221201/flexible_server_types_gen.go
v2/api/dbforpostgresql/v1api20221201/storage/flexible_server_types_gen.go
v2/api/dbforpostgresql/v1api20221201/storage/structure.txt
v2/api/dbforpostgresql/v1api20221201/storage/zz_generated.deepcopy.go
v2/api/dbforpostgresql/v1api20221201/structure.txt
v2/api/dbforpostgresql/v1api20221201/zz_generated.deepcopy.go
v2/api/dbforpostgresql/v1api20230601preview/flexible_server_spec_arm_types_gen.go
v2/api/dbforpostgresql/v1api20230601preview/flexible_server_types_gen.go
v2/api/dbforpostgresql/v1api20230601preview/storage/flexible_server_types_gen.go
v2/api/dbforpostgresql/v1api20230601preview/storage/structure.txt
v2/api/dbforpostgresql/v1api20230601preview/storage/zz_generated.deepcopy.go
v2/api/dbforpostgresql/v1api20230601preview/structure.txt
v2/api/dbforpostgresql/v1api20230601preview/zz_generated.deepcopy.go
v2/azure-arm.yaml
v2/internal/controllers/controller_resources_gen.go

Allows the values for `geoBackupKeyURI` and `primaryKeyURI` to be pulled from a configmap instead of requiring them to be hard coded in the resource.
Partially addresses #4298 

Allow the data encryption keys for PostgreSQL Flexible server to be configured

---

v2/api/insights/customizations/scheduled_query_rule_extensions.go

When reconciling an Insights `ScheduledQueryRule`, we can get a `BadRequest` response if the associated `Log Analytics Workspace` doesn't yet exist; we need to reclassify that as a retryable error.
Closes #4293

Retry if/when ScheduledQueryRules encounter BadRequest

---

v2/cmd/asoctl/pkg/importresources/importable_arm_resource.go
v2/tools/generator/internal/astmodel/flagged_type.go
v2/tools/generator/internal/functions/one_of_json_marshal_function.go
v2/tools/generator/internal/reporting/type_catalog_report.go

Our type catalog report was omitting flags, which caused problems solving a problem with OneOf types recently. 
This PR adds flags into the report for visibility.
Includes a few minor pieces of code gardening.

Include flags in the type catalog report

---

.github/workflows/api-docs-repo.yaml
.github/workflows/deploy-site.yml
.github/workflows/helm-chart-repo.yaml
.github/workflows/visualize-repo.yml

I forked the ASO repo to hack on some stuff in my own time and have been getting spammed by our scheduled workflows failing in the fork.
Introducing a condition on the workflow so they only proceed when running on the main repo seems a simple way to neuter the spam and make things quieter - and benefits anyone else who forks the repo too.

Disable jobs unless running on the main repo

---

v2/tools/generator/internal/astmodel/oneof_type.go
v2/tools/generator/internal/astmodel/type_set.go
v2/tools/generator/internal/codegen/pipeline/assemble_oneof.go
v2/tools/generator/internal/codegen/pipeline/convert_allof_and_oneof_to_objects.go
v2/tools/generator/internal/codegen/pipeline/convert_allof_and_oneof_to_objects_test.go
v2/tools/generator/internal/codegen/pipeline/testdata/TestConversionOfAllOf_WhenContainingOneOf_ReturnsExpectedResult/structure.txt.golden
v2/tools/generator/internal/test/asserts.go

Construction of objects representing `OneOf` types has an ordering bug, where it can generate the wrong results if the input types are presented in a different order. This process should give the same results regardless of the order of inputs.
Consider the base case (which works) where we have a OneOf called `Address` we're about to merge common properties from `AddressBase`.
``` mermaid
classDiagram
class AddressBase {
Location string
}
class Address {
<<oneOf>>
}
class PostalAddress
class ResidentialAddress 
Address --> PostalAddress : Postal
Address --> ResidentialAddress : Residential
```
The common properties from `AddressBase` are pushed down to the leaves of `Address`, and properties created representing the available cases.
``` mermaid …
```

Fix ordering bug for OneOf processing

---

v2/api/storage/v1api20210401/storage_account_spec_arm_types_gen.go
v2/api/storage/v1api20210401/storage_account_spec_arm_types_gen_test.go
v2/api/storage/v1api20210401/storage_account_types_gen.go
v2/api/storage/v1api20210401/storage_account_types_gen_test.go
v2/api/storage/v1api20210401/structure.txt
v2/api/storage/v1api20210401/zz_generated.deepcopy.go
v2/api/storage/v1api20220901/storage_account_spec_arm_types_gen.go
v2/api/storage/v1api20220901/storage_account_spec_arm_types_gen_test.go
v2/api/storage/v1api20220901/storage_account_types_gen.go
v2/api/storage/v1api20220901/storage_account_types_gen_test.go
v2/api/storage/v1api20220901/structure.txt
v2/api/storage/v1api20220901/zz_generated.deepcopy.go
v2/api/storage/v1api20230101/storage_account_spec_arm_types_gen.go
v2/api/storage/v1api20230101/storage_account_spec_arm_types_gen_test.go
v2/api/storage/v1api20230101/storage_account_types_gen.go
v2/api/storage/v1api20230101/storage_account_types_gen_test.go
v2/api/storage/v1api20230101/structure.txt
v2/api/storage/v1api20230101/zz_generated.deepcopy.go
v2/api/storage/versions_matrix.md
v2/azure-arm.yaml

Fixes #4247.
Storage supports passing multiple values to the Bypass parameter separated by a comma, but that's not how Swagger enums work so the fact they've specified this field as an enum is technically incorrect. We just treat it as a string to allow the user to pass multiple values

Relax enum restrictions on Storage bypass parameter

---

v2/internal/controllers/controller_resources.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/testcommon/scheme.go
v2/internal/tests/azure_generic_arm_reconciler_test.go
v2/pkg/genruntime/convertible.go
v2/pkg/genruntime/convertible_spec.go
v2/pkg/tests/convertible_test.go

The ASO controller uses reflection to look through the resource and find the ConfigMapReference and SecretReference fields. This reflection could miss SecretReference and ConfigMapReference fields that had been serialized into the "PropertyBag" property on the storage type. This was most common when working with preview APIs that had added new ConfigMapReference or SecretReference fields that don't exist in the GA api version.
The fix is to use the converted version for reflection-based discovery.
Fixes #4298.
Fixes #4316.

Fix bug where some ConfigMap and Secret references could be missed

---

.devcontainer/Dockerfile
.devcontainer/install-dependencies.sh

Updates version of Go to 1.23 to avoid this error:
```
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20241014151821-aa78068bdf55 requires go >= 1.23.0 (running go 1.22.7; GOTOOLCHAIN=local)
```
Tested by rebuilding the container and running `task ci` locally.

Update version of Go

---

hack/crossplane/apis/sql/v1api20201101preview/servers_database_types_gen.go
v2/azure-arm.yaml
v2/tools/generator/internal/codegen/pipeline/load_types.go
v2/tools/generator/internal/config/configuration.go
v2/tools/generator/internal/config/type_loader_rename.go
v2/tools/generator/internal/jsonast/swagger_type_extractor.go
v2/tools/generator/internal/jsonast/swagger_type_extractor_test.go

When loading resources from `Microsoft.Insights` we are encountering a panic caused by a naming collision between two near identical resources, `DiagnosticsSettings`. 
To resolve this, we need to target specific renaming to the two types so they end up with different names. Our existing configuration doesn't operate this early in the pipeline, so we need to special case things.
Closes #4337 
I've left the configuration required for `insights` in our configuration file so things are ready to go for our contributer.

Add configuration to allow resolving name collisions when loading resources

---

docs/hugo/.htmltest.yml
docs/hugo/content/contributing/developer-setup.md
docs/hugo/go.mod
docs/hugo/go.sum

Upgrading `hugo` seems to have broken our docs site; upgrading to a matching version of `docsy` appears to fix it.
Also adds a suppression for links that can't be verified by `htmltest`.

Upgrade version of docsy and address broken links

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/improvement-template.md
.github/ISSUE_TEMPLATE/new-feature-template.md
.github/pull_request_template.md

Updates our issue templates to use markdown headings and to clarify the language.
Our existing templates have been irritating me, so trying to make them better.

Update issue templates

---

.github/workflows/pr-validation.yml
Taskfile.yml
reports/README
scripts/v2/linux-docker-use-ssd.sh

Force coverage files to /mnt (tempdir) during CI

Force coverage files to /mnt (tempdir) during CI

---

v2/api/containerservice/v1api20240402preview/arm/managed_clusters_agent_pool_spec_types_gen.go
v2/api/containerservice/v1api20240402preview/arm/managed_clusters_agent_pool_status_types_gen.go
v2/api/containerservice/v1api20240402preview/managed_clusters_agent_pool_types_gen.go
v2/api/insights/v1api20220615/scheduled_query_rule_types_gen.go
v2/api/insights/v1api20220615/structure.txt
v2/api/machinelearningservices/v1api20240401/storage/workspace_types_gen.go
v2/api/machinelearningservices/v1api20240401/storage/workspaces_connection_types_gen.go
v2/api/machinelearningservices/v1api20240401/workspace_types_gen.go
v2/api/machinelearningservices/v1api20240401/workspaces_connection_types_gen.go
v2/api/network/v1api20201101/arm/route_tables_route_spec_types_gen.go
v2/api/network/v1api20201101/arm/route_tables_route_spec_types_gen_test.go
v2/api/network/v1api20201101/arm/structure.txt
v2/api/network/v1api20201101/route_tables_route_types_gen.go
v2/api/network/v1api20201101/route_tables_route_types_gen_test.go
v2/api/network/v1api20201101/storage/route_tables_route_types_gen.go
v2/api/network/v1api20201101/storage/route_tables_route_types_gen_test.go
v2/api/network/v1api20201101/storage/structure.txt
v2/api/network/v1api20201101/storage/zz_generated.deepcopy.go
v2/api/network/v1api20201101/structure.txt
v2/api/network/v1api20201101/zz_generated.deepcopy.go
v2/internal/controllers/recordings/Test_Networking_Route_CreatedThenRouteTableUpdated_RouteStillExists.yaml

Updates the commit referenced by the `v2/specs/azure-rest-api-specs` submodule to the latest main and regenerates code.
**Breaking**: The property `RouteTablesRoute.HasBgpOverride` has been marked as readonly by the upstream product group (see commit [61fdc46](https://github.com/Azure/azure-rest-api-specs/commit/61fdc4621a644bb2b2b5606344139c93765e5518)from [PR#29993](https://github.com/Azure/azure-rest-api-specs/pull/29993)) and has been removed from our Spec definitions.

Update our azure-rest-api-specs submodule

---

.github/workflows/pr-validation.yml
Taskfile.yml
scripts/v2/linux-docker-use-ssd.sh

There was a bug in the GitHub runner infrastructure we use that caused the build to happen on the wrong drive. Now that this bug is fixed we don't need this workaround anymore.

Undo force covecov to /mnt

---

v2/cmd/controller/app/setup.go
v2/internal/reconcilers/generic/generic_reconciler.go
v2/internal/reconcilers/generic/register.go
v2/internal/testcommon/kube_test_context_envtest.go

We disable controller-runtime logging for our envtest instances because we create multiple of them and it can be a lot of extra logs we don't need, but we rely on controller-runtime logs for panic-detection.
We want panic logging with controller-runtime logging disabled for envtest, but we don't want duplicate panic logs in production, so we introduce a PanicHandler that is set only in envtest contexts.

Add envtest panic handler

---

v2/internal/testcommon/resource_namer.go

We use a resource namer that generates a "random" suffix for resources to ensure concurrent tests don't clash during execution.
This namer has two modes - one is predictable (based on the test name) and generates the same results every time, and one is purely random.
We're getting clashes between concurrent tests using _random_ names and we think this is due to a lack of randomness caused by seeding the generator with the current time.
In this PR we switch to _also_ using the test name, increasing the number of bits of entropy.

Increase randomness of naming

---

v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go
v2/tools/generator/internal/codegen/pipeline/report_resource_versions_test.go

Prior to this point, every resource group imported by ASO has been consistent, with its resource URLs all defined with identical letter case. This results in all the resources within the group having an identical _provider_ name as the prefix of their ARM type.
For example, all the resources in the `storage` group have an ARMType() with the prefix `Microsoft.Storage`, including
* Microsoft.Storage/storageAccounts
* Microsoft.Storage/storageAccounts/blobServices
* Microsoft.Storage/storageAccounts/blobServices/containers
* Microsoft.Storage/storageAccounts/fileServices
and so on.
However, the `alertsmanagement` group is not consistent with its letter casing, resulting in differences between resources.
* microsoft.alertsManagement/smartDetectorAlertRules
* …

Fix report case sensitivity

---

docs/hugo/config.toml
docs/hugo/content/design/ADR-2024-10-OneOf-Resources/_index.md

Two of our existing ASO design decisions are colliding and we need to decide how to resolve the conflict.
**TL;DR:** Our one-of handling requires common properties to be pushed down to the leaves; ARM spec generation requires `Name` to be on the root object of the spec.

ADR for changing handling of spec-one-of types

---

.github/workflows/api-docs-repo.yaml
.github/workflows/build-devcontainer-image.yml
.github/workflows/create-release-experimental.yml
.github/workflows/create-release-official.yml
.github/workflows/helm-chart-repo.yaml
.github/workflows/live-validation.yml
.github/workflows/pr-validation.yml
.github/workflows/pre-release-tests.yaml
.github/workflows/visualize-repo.yml

Earlier versions of the `actions/upload-artifacts` action are being deprecated shortly and will stop working, so they need to be updated.
We also have a few versions triggering warnings because they target old versions of Node.js:
```
The following actions use a deprecated Node.js version and will be forced to run on node20:
```
Plus, our CRD documentation workflow has been failing for a while, so that needs a fix.

Update action versions and fix broken workflows

---

v2/tools/generator/internal/armconversion/convert_to_arm_function_builder.go
v2/tools/generator/internal/astmodel/identifier_factory.go
v2/tools/generator/internal/astmodel/identifier_factory_test.go
v2/tools/generator/internal/astmodel/internal_type_name.go
v2/tools/generator/internal/astmodel/type_name.go
v2/tools/generator/internal/codegen/pipeline/name_types_for_crd.go
v2/tools/generator/internal/codegen/pipeline/name_types_for_crd_test.go

Removes the now unused infrastructure that allowed gradual migration of ARM types to the new subpackage location.
Also removes `ARMSuffix`, tidying up related tests and usage.

Tidyup ARM type naming

---

v2/api/authorization/customizations/role_assignment_extensions.go

When importing a `RoleAssignment` we have a check to detect whether it has been inherited from a wider scope. This check is currently triggering a **panic** if we try to directly import a role assignment without an owner.
Closes #4444

Skip checking for inherited roleassignment if owner is unavailable

---

v2/api/network/v1api20201101/virtual_networks_subnet_types_gen.go
v2/api/network/v1api20240301/virtual_networks_subnet_types_gen.go
v2/azure-arm.yaml
v2/cmd/asoctl/go.mod
v2/tools/generator/internal/codegen/code_generator.go
v2/tools/generator/internal/codegen/pipeline/override_descriptions.go
v2/tools/generator/internal/codegen/testdata/TestGolden_NewARMCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewCrossplaneCodeGeneratorFromConfigCreatesRightPipeline.golden
v2/tools/generator/internal/codegen/testdata/TestGolden_NewTestCodeGeneratorCreatesRightPipeline.golden
v2/tools/generator/internal/config/object_model_configuration.go
v2/tools/generator/internal/config/property_configuration.go

Use this option to override the Subnet IPConfigurations field to explain that it is removed if it crosses 2000 entries.

Add description override codegenerator option

---

Taskfile.yml
docs/hugo/content/contributing/hints-and-tips/_index.md

Now that we're enforcing import order using [**gci**](https://github.com/daixiang0/gci), the exacting rule means getting a pull request across the line might be challenging.
Fortunately, there's an automated fix that we can apply by running `golangci-lint` with the `--fix` parameter. Adding this to the `format-code` task in the `Taskfile.yml` makes this easy to access.

Include golangci-lint fixes when formatting code

---

v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_azureserviceoperator-crd-manager-role.yaml
v2/charts/azure-service-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_azureserviceoperator-crd-manager-rolebinding.yaml
v2/cmd/controller/app/setup.go
v2/config/manager/manager.yaml
v2/internal/crdmanagement/helpers_test.go
v2/internal/crdmanagement/manager.go
v2/internal/crdmanagement/manager_test.go

- Use Deployment mode Recreate, which ensures that all webhook pods serving CRD conversion requests during upgrade are running the latest version of ASO.
- Take lease during CRD management, to ensure that ASO doesn't fight with itself during CRD installation.
Related to #4445

Support multiple replicas of ASO pod

---

v2/api/network/customizations/public_ip_address_extension.go
v2/internal/controllers/networking_ipaddress_notBlockedByPrefix_20240401_test.go
v2/internal/controllers/recordings/Test_Network_PublicIPAddress_creationNotBlockedByPublicIPPrefix_20240301.yaml

When creating a PublicIPAddress resource in Azure, you can get an `ReferencedResourceNotProvisioned` error if the address references a `PublicIPPrefix` that isn't ready for use. 
By default this is classified as an **error**, not a **warning**, resulting in the resource being permanently blocked. 
This PR implements the `ErrorClassifier` extension, turning this condition into a warning so that ASO will retry resource creation; it will succeed once the `PublicIPPrefix` is ready.
Closes #4054

Ensure PublicIPAddress resources aren't permanently blocked 

---

v2/cmd/asoctl/pkg/importreporter/log.go

If using the simple logger for asoctl (rather than the progress bars), nested loggers were not shutting down properly when the resource was completed.

Fix: Ensure asoctl simple logger shuts down properly

---

Taskfile.yml
scripts/v2/create-kind-wi-storage.sh
scripts/v2/wait-for-operator-ready.sh

Split the `format-code` task into separate targets, avoiding the problem where `golangci-lint` sometimes fails when applying fixes within a submodule. 
Improved logging in `create-kind-wi-storage.sh` for better traceability and debugging. 
Improved logging and increased timeouts `wait-for-operator-ready.sh` to provide more context.

Minor testing improvements

---

v2/cmd/asoctl/go.mod
v2/cmd/asoctl/go.sum
v2/cmd/asoctl/pkg/importresources/resource_importer.go
v2/cmd/asoctl/pkg/importresources/watchdog.go

Fixes an ASO deadlock introduced in #4452.
The immediate cause of the deadlock was an omitted call to `Completed(1)` when collating import errors, leaving the progress bar incomplete.
However, this coupling between the progress bar and the importer isn't ideal, and leaves the door open for addition problems in the future. To avoid this, I've made two additional changes.
* Introduced a `watchdog` to keep track of inflight resources, to monitor the import, and to shut things down when everything is done
* Refactored construction of the data flow graph into separate sections that can be more easily reasoned about independently.

Fix: asoctl deadlock

---

v2/tools/generator/internal/jsonast/swagger_type_extractor.go
v2/tools/generator/internal/jsonast/swagger_type_extractor_test.go

Some services hardcode names into their URLs, such as `default` here:
```
blobService/default/containers/{containerName}
```
When we construct the **resource type** identifier for those resources, we don't want to include those - for this example, we want `blobService/containers` _not_ `blobService/default/containers`.
While importing `Microsoft.Web/sites/sourcecontrols` Nishant Shekhar encountered this error:
```
could not create fully qualified ARM ID, had 2 azureNames and 3 resourceTypes. 
azureNames: ["aso-sample-function" "web"] 
resourceTypes: ["sites" "sourcecontrols" "web"]
```
which I traced down to the presence of the hard coded name `web` in this URL:
```
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/slots/{slot}/sourceco …
```

Allow 'web' as a hard coded resource name

---

.github/workflows/build-devcontainer-image.yml
.github/workflows/scan-controller-image.yaml

The two workflows _Build Devcontainer image_ and _Scan controller image_ won't work in forks of ASO due to permissions or hard coded values. 
Here we disable them outside of the main repo so that contributors aren't spammed with failure emails.

Disable workflows in forks

---

scripts/v2/create-kind-wi-storage.sh
scripts/v2/make-mi-fic.py

This PR fixes `make-mi-fic.py` script bug where once if identity is created and the process fails, re-running of script doesn't generate the artifacts. 
With this change, even if the identity already exists, the script re-run the rest of the steps and will ensure that the files `miclientid.txt` and `fix.txt` exist with the correct content.
Closes #4478

Add fixes for make-mi-fic.py consistency

---

v2/api/eventhub/customizations/namespaces_eventhubs_authorization_rule_extension.go
v2/api/servicebus/customizations/namespaces_authorization_rule_extensions.go

obj.Name was mistakenly used when it should have been obj.AzureName (or id.Name, which is derived from the ARM ID which comes from obj.AzureName).
Fixes #4515.

Fix bug where obj.AzureName was not used to create Azure URLs

---

v2/internal/genericarmclient/generic_client_test.go
v2/internal/genericarmclient/policy_register_rp.go

This can happen if the Azure RP being called returns a JSON error response payload that doesn't match the Azure contract. Instead of overwriting the underlying error, just return it as-is to aid in debugging.

Fix "missing error information" error on 409s

---

Taskfile.yml

Including lint fixes in `format-code` has caused problems, as the linter requires the code to fully compile before a fix can be applied. 
We can easily end up in a situation where running `task` doesn't fix things because a linter failure blocks code generation.
This PR removes the linters from `format-code` and instead puts the `--fix` flag into the lint tasks.

Fix linting in Taskfile

---

docs/hugo/content/reference/_index.md
docs/hugo/content/reference/containerregistry/_index.md
v2/tools/generator/internal/astmodel/oneof_type.go
v2/tools/generator/internal/astmodel/oneof_type_test.go
v2/tools/generator/internal/codegen/pipeline/convert_allof_and_oneof_to_objects.go

Fixes a few small errors that I uncovered while troubleshooting issues with Kusto resources.
Previously we've always merged object properties into the root of a one-of, then pushed them down to the leaves. Due to the way Kusto resources are structured, we now also need to support merging object properties directly into leaves. (Instead of embedding a OneOf directly into an AllOff, the Kusto resources instead refer to a separate type definition, triggering the change in behaviour.)
In two locations, the synthesizer was looking up an unmodified type definition when that type had already been modified, resulting in the previous updates being lost. All type lookup now goes through a helper method (`lookupType`) that avoids this propblem.
We hadn't updated equality of one-of types, causing …

Fix bugs in OneOf to Object conversion

---

docs/hugo/content/guide/aso-controller-settings-options.md
v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/config/manager/manager_image_patch.yaml
v2/internal/config/vars.go
v2/internal/config/vars_test.go
v2/internal/reconcilers/generic/generic_reconciler.go
v2/internal/reconcilers/predicates.go
v2/internal/reconcilers/reconcile_policy.go
v2/internal/reconcilers/reconcile_policy_test.go
v2/pkg/common/config/config.go

Extends ASO configuration to customize default reconcile policy for CRs when annotation `serviceoperator.azure.com/reconcile-policy` it not explicitly specified.
It keeps the same default behavior of today assuming that all CRs are in `manage` status, however this value can be overridden by setting DEFAULT_RECONCILE_POLICY environment variable.
closes #4562 
closes #4053 
I would appreciate to have your honest feedback on this code change; I'll add relevant unit tests and documentation if code looks correct on your side.

Make reconcile-policy customizable for ASO operator (#4053)

---

v2/tools/generator/internal/armconversion/convert_from_arm_function_builder.go
v2/tools/generator/internal/armconversion/convert_to_arm_function_builder.go
v2/tools/generator/internal/astmodel/conversion_function_builder.go
v2/tools/generator/internal/astmodel/file_definition.go
v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go
v2/tools/generator/internal/codegen/pipeline/resource_registration_file.go
v2/tools/generator/internal/conversions/property_conversions.go
v2/tools/generator/internal/conversions/writable_conversion_endpoint.go
v2/tools/generator/internal/functions/conditions_functions.go
v2/tools/generator/internal/functions/kubernetes_admissions_validator.go
v2/tools/generator/internal/functions/one_of_json_marshal_function.go
v2/tools/generator/internal/functions/one_of_json_unmarshal_function.go
v2/tools/generator/internal/interfaces/kubernetes_resource_interface.go
v2/tools/generator/internal/testcases/json_serialization_test_case.go

Generally, we prefer to use our factory methods in `astbuilder` over declaring literals from `dst` directly, partly for consistency and partly to avoid common errors such as using the same node multiple times.
I'd built up a small list of violations over time - this PR addresses those.

Tidy up dst library use

---

v2/api/network/customizations/dns_zones_a_record_extension.go
v2/api/network/customizations/dns_zones_aaaa_record_extension.go
v2/api/network/customizations/dns_zones_cname_record_extension.go
v2/api/network/customizations/dns_zones_cname_record_extension_test.go

This error is likely transient and can be retried on.
Closes #4645

Retry on DNS Zone targetResource lookup not found

---

v2/internal/util/postgresql/postgresql.go
v2/internal/util/postgresql/role_option.go
v2/internal/util/postgresql/roles.go
v2/test/postgresql_test.go

This is due to PostgreSQL lowercasing role names when they are not double-quoted. This behavior is mentioned here:
https://stackoverflow.com/questions/31694518/how-can-i-create-a-capitalized-postgres-role-name
Closes #4334.

Fix bug where PostgreSQL create user couldn't add roles with caps

---

v2/internal/reconcilers/arm/error_classifier.go
v2/internal/reconcilers/arm/error_classifier_test.go

Fixes an inconsistency where an HTTP conflict (409) was treated as retryable, but the explicit error code `Conflict` was treated as fatal.
Now both kinds of conflict will be treated as retryable.
Partial solution for #4668

Retry for explict Conflict, as we do already for 409

---

v2/cmd/controller/app/setup.go
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/internal/reconcilers/arm/error_classifier.go
v2/internal/reconcilers/arm/error_classifier_test.go
v2/internal/testcommon/kube_test_context_envtest.go
v2/internal/util/interval/interval_calculator.go
v2/internal/util/interval/interval_calculator_test.go
v2/pkg/genruntime/conditions/errors.go
v2/pkg/genruntime/conditions/ready_condition_builder.go
v2/pkg/genruntime/core/cloud_error_details.go
v2/pkg/genruntime/extensions/error_classifier.go
v2/pkg/genruntime/retry/retry_classification.go

* Adds the ability to retry at a slower rate for certain errors.
Fixes #4666.

Retry ScopeLocked errors at a slower rate

---

v2/api/containerservice/customizations/managed_cluster_extensions.go
v2/api/containerservice/customizations/managed_clusters_agent_pool_extensions.go
v2/api/dbforpostgresql/customizations/flexible_server_extensions.go
v2/api/dbforpostgresql/customizations/flexible_servers_database_extensions.go
v2/api/dbforpostgresql/customizations/flexible_servers_firewall_rule_extensions.go
v2/api/kusto/customizations/cluster_extensions.go
v2/api/kusto/customizations/database_extensions.go

Fixes the PreReconcileCheck extension for kusto.Database resources to allow their owner to be referenced by armID.
Note: We can only do the prerequisite check for Kusto Clusters that are managed by ASO, so users will end up with _conflict_ messages in their logs.
Closes #4712 
Also fixes up other implementations of `extensions.PreReconciliationChecker` to properly call the `next()` function, bringing them into alignment with the design of the extension.

Fix the Kusto Database extension to allow owners referenced by armID

---

v2/internal/controllers/labels_test.go
v2/internal/controllers/recordings/Test_ExpectedLabels_AreAdded.yaml
v2/internal/reconcilers/arm/azure_generic_arm_reconciler_instance.go
v2/pkg/common/labels/labels.go
v2/pkg/common/labels/labels_test.go

* Truncate owner name label and group-kind label if they are too long.
* Add a new owner-uid label that will not be truncated (because a UID is never too long). This is useful if users know their names may have been too long, they can use the a filter w/ UID label to ensure they don't miss any child-resources (and that there aren't collisions if there are other owners that have the same first 63 characters).
Fixes #4734

Fix bug when owner label could be too long

---

charts/README.md

We saw [on Slack](https://kubernetes.slack.com/archives/C046DEVLAQM/p1744610768869099?thread_ts=1744383458.097009&cid=C046DEVLAQM) someone who thought ASO was unmaintained because they were looking at the v1 charts.
Adding a README to that folder to redirect people to the v2 charts.

Add readme for v1 charts

---

v2/internal/testcommon/vcr/redact.go

Discovered while testing Entra support, we're _redacting_ URLs by forcibly changing the host to `https://management.azure.com/` - but this breaks URL lookup when doing playback of tests.
This redaction doesn't do anything to prior URLs because they already had the hostname `https://management.azure.com/` specified. 
This PR removes the redaction so that _other_ endpoints can be included in tests - like `graph.microsoft.com` for Entra.

Remove URL host redaction

---

v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/charts/azure-service-operator/values.yaml

_Thanks for sending a pull request! Delete this text and tell us why we need this change._

Support for injecting custom environment in the Helm Chart

---

v2/internal/reconcilers/azuresql/connector.go

Improve type extraction from resource hierarchy for ownerDetails
Replaced fixed index-based type assertions with a dynamic type check loop over the hierarchy slice. This enhances robustness by allowing flexible ordering and avoiding panics on unexpected slice lengths.
Updated error messages to clearly indicate missing types instead of reporting incorrect type assertions.
We have a case where the resource group is created within terraform so aso doesn't know it exists with objects. The armId exists and works but this breaks check which check's the amount of objects found. Change so it will check for the needed objects instead of checking a number.

Improve type extraction from resource hierarchy for ownerDetails

---

docs/hugo/content/design/ADR-2025-05-Version-Priority/_index.md
docs/hugo/content/design/_index.md

Captures offline discussion about how to address #4147 so that users don't get nasty surprises.

Add ADR on how to address version priority

---

v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml
v2/config/manager/manager.yaml

I spend quite a bit of time spinning up CAPZ management clusters which include ASO, and I noticed that the `initialDelaySeconds` on the readiness probe is bottlenecking that process where I usually see ASO finish starting up after about 10s, then idle for an extra ~45s waiting for the first readiness probe.
I see the `initialDelaySeconds` was increased in #2844, but a startup probe should be able to account for longer startup times without holding things up if things are actually ready more quickly.

Add startup probe to controller manager

---

Taskfile.yml
scripts/v2/check-crd-size.sh

Adds a size check on our generated CRD files, failing the build if any exceed the Kubernetes limit of 1.5MiB (in JSON format).
Also generates a warning for any CRDs that exceed 1MiB in file so that we don't get surprised. 
Sample output:
```
[controller:check-crd-size] Checking CRD sizes...
[controller:check-crd-size] Checking CRDs against size limit of 1.5MiB (1572864 bytes)...
[controller:check-crd-size] [WRN] Large CRD (>1MiB): containerservice.azure.com_managedclusters.yaml - 1.29MiB
[controller:check-crd-size] 
[controller:check-crd-size] [INF] CRD Size Summary:
[controller:check-crd-size]       Total CRDs: 243
[controller:check-crd-size]       Large CRDs (>1MiB): 1
[controller:check-crd-size]       Oversized CRDs (>1.5MiB): 0
[controller:check-crd-size] 
[controller:check-crd-size] …
```

Add build check on CRD sizes

---

.github/workflows/copilot-setup-steps.yml

Adds a GitHub action to [configure the workspace](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment) for the GitHub CoPilot Coding Agent so that it has all the correct tools available.
Reuses the `install-dependencies.sh` script we already use.
It doesn't appear that the agent can reuse the existing `.devcontainer`.

Add Copilot Coding Agent setup 

---

v2/charts/azure-service-operator/templates/apps_v1_deployment_azureserviceoperator-controller-manager.yaml

Allows to unset GOMEMLIMIT environment variable if helm value is set to null. 
This is especially needed if you use a VPA to avoid conflict between the POD memory that will change thanks to the VPA and this go memory limit fixed value.
Alternative would be to rely on dynamic configuration as provided by https://github.com/KimMachineGun/automemlimit

Allow GOMEMLIMIT to be unset

---

v2/cmd/controller/app/setup.go
v2/internal/reconcilers/generic/register.go
v2/internal/testcommon/kube_test_context_envtest.go

Controller Runtime already does this by default.

Remove unnecessary LogConstructor overrides

---

v2/cmd/asoctl/pkg/importresources/importable_arm_resource.go

Unlike other resource providers, who use the error code `ResourceTypeNotSupported` when an extension resource is used with the wrong parent resource, `Microsoft.Insights` use `UnsupportedResourceType`.
We need to add `UnsupportedResourceType` to the list of error code we expect for extension resources as asoctl probes to find resources.
Closes #4919

Add "UnsupportedResourceType" to asoctl exclusions for extension resources

---

.gitignore
v2/api/documentdb/v1api20210515/storage/database_account_types_gen.go
v2/api/documentdb/v1api20231115/arm/database_account_spec_types_gen.go
v2/api/documentdb/v1api20231115/arm/database_account_spec_types_gen_test.go
v2/api/documentdb/v1api20231115/arm/structure.txt
v2/api/documentdb/v1api20231115/database_account_types_gen.go
v2/api/documentdb/v1api20231115/database_account_types_gen_test.go
v2/api/documentdb/v1api20231115/storage/database_account_types_gen.go
v2/api/documentdb/v1api20231115/storage/database_account_types_gen_test.go
v2/api/documentdb/v1api20231115/storage/structure.txt
v2/api/documentdb/v1api20231115/storage/zz_generated.deepcopy.go
v2/api/documentdb/v1api20231115/structure.txt
v2/api/documentdb/v1api20231115/zz_generated.deepcopy.go
v2/api/documentdb/v1api20240815/arm/database_account_spec_types_gen.go
v2/api/documentdb/v1api20240815/arm/database_account_spec_types_gen_test.go
v2/api/documentdb/v1api20240815/arm/structure.txt
v2/api/documentdb/v1api20240815/database_account_types_gen.go
v2/api/documentdb/v1api20240815/database_account_types_gen_test.go
v2/api/documentdb/v1api20240815/storage/database_account_types_gen.go
v2/api/documentdb/v1api20240815/storage/database_account_types_gen_test.go
v2/api/documentdb/v1api20240815/storage/structure.txt
v2/api/documentdb/v1api20240815/storage/zz_generated.deepcopy.go
v2/api/documentdb/v1api20240815/structure.txt
v2/api/documentdb/v1api20240815/zz_generated.deepcopy.go
v2/azure-arm.yaml
v2/tools/generator/internal/config/configuration.go
v2/tools/generator/internal/config/field_matcher.go
v2/tools/generator/internal/config/type_matcher.go
v2/tools/generator/internal/config/type_transformer.go
v2/tools/generator/internal/config/type_transformer_test.go

Tightens our validation of TypeTransformer configuration to ensure that all parts of the TypeMatcher are used, and to leverage our `TypoAdvisor` to generate good error messages.
Also fixes ineffective removal of the property `CustomerManagedKeyStatus`, dating back to #3967
Closes #4867 
Sample error (line-breaks added):
```
ERR failed to execute root command error="
error generating code: 
failed to execute stage 9: 
Modify types using configured type transforms: 
type transformer: 
type matcher [Group: 'dataprotection'; Name: 'BackupVaults_BackupPolicySpec'; Because: 'This property should be marked readonly in Swagger'], incomplete match for name: 
no match for \"BackupVaults_BackupPolicySpec\" (did you mean BackupVaults_BackupPolicy_Spec?)"
```
Much of the infrastructure needed was …

Improve diagnostics from TypeTransformers
